<h3 class="headerTitle"> AJOUTER UN ARTICLE </h3>

<form method="POST" action="add_article" enctype="multipart/form-data" class="formAddArticle">
    <div class="article">
        <div class="article-item">
            <label  for="label"> Article </label>
            <input type="text" class="form-control" id="label" name="label" value="<?=$params['label'];?>">
        </div>
        <div class="article-item">
            <label  for="origine">Origine</label>
            <input type="text" class="form-control" id="origine" name="origine" value="<?=$params['origine'];?>">
        </div>
        <div class="article-item">
            <label  for="prix">Prix</label>
            <input type="text" class="form-control" id="prix" name="prix" value="<?=$params['prix'];?>">
        </div>
        <div class="article-item">
            <label for="poids">Poids</label>
            <input type="text" class="form-control" id="poids" name="poids" value="<?=$params['poids'];?>">
        </div>
        <div class="article-item">
            <label for="image">Image</label>
            <input type="file" class="form-control" id="image" name="image">
        </div>


        <div class="article-item">
            <label class="" for="unite">Unite</label>
            <select class="form-control" name="unite" id="unite">
                <option value="0">Sélectionner une unitée</option>
                <?php foreach ($params['unites'] as $unite): ?>
                    <option value="<?=$unite['id_unite'];?>"><?=$unite['unite'];?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="article-item">
            <label class="" for="famille">Famille</label>
            <select class="form-control" name="famille" id="famille">
                <option value="0">Sélectionner une famille</option>
                <?php foreach ($params['familles'] as $famille): ?>
                    <option value="<?=$famille['id_famille'];?>"><?=$famille['famille'];?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="article-item">
            <label  for="statut">Disponibilité</label>
            <select class="form-control" name="statut" id="statut">
                <option value="0">Sélectionner une unitée</option>
                <?php foreach ($params['statut'] as $statut): ?>
                    <option value="<?=$statut['id_statutArticle'];?>"><?=$statut['statutArticle'];?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="article-item">
            <button type="submit" >Ajouter</button>
        </div>
    </div>

</form>
