<main>


<h3 class="text-center p-0 m-0 text-custom-color-red"><?=$dateDuJour?></h3>


<div class="container-fluid">
<div class="row">

<div class="col-12 col-lg-8 ml-lg-auto mr-lg-3 p-0 mt-5">

<!--    <div class="col-12 pb-3 pt-2 mb-3 bg-light">-->
<!--    <h4 class="text-center  ">Infos</h4>-->
<!--    <span class="">Info à communiquer : Sit enim idem caecus, debilis. Sint ista Graecorum; Quae cum dixisset, finem ille. Cave putes quicquam esse verius. Nam Pyrrho, Aristo, Erillus iam diu abiecti. </span>-->
<!--    </div>-->

    <div class="col-12 mb-3 pb-3 pt-2  bg-light ">
        <h4 class=" text-center p-2 mb-4 ">Commande du jour</h4>
        <?php foreach ($commandeDuJour as $commande): ?>
            <div class="row commande">
                <div class="col-4"><p class=""><?=$commande['society'];?></p> </div>
                <div class="col-4"><p><?=$commande['date_livraison'] ;?></p> </div>
                <div class="col-3"><p><?=$commande['montant'] ." €" ;?></p> </div>
                <div class="col-1 p-1"><a href="<?='commande_details?id='.$commande['id_commande'] ;?>">Voir</a> </div>
            </div>
        <?php endforeach; ?>
        <div class="text-center pt-2 pb-2 ">
            <a class="w-100  badge badge-success d-inline" href="commande_admin">Liste des commandes</a>
        </div>
    </div>

    <div class="col-12 mb-3 pb-3 pt-2  bg-light">
        <h4 class="text-center mb-4 ">Inscription en attente</h4>

        <?php foreach ($users as $user): ?>
            <?php if($user['label_status']=='En attente') : ?>

            <div class="row ">
                <div class="col-3"><p><?= $user["society"];?></p> </div>
                <div class="col-5"><p><?= $user["email"];?></p> </div>
                <div class="col-3"><p><?= $user["postal"];?></p> </div>
                <div class="col-1 p-1"><a href="<?='edit_user?id='.$user["id_user"];?>"><i class="fa-solid fa-eye"></i> </a> </div>
            </div>
            <?php endif; ?>
        <?php endforeach; ?>

        <div class="text-center justify-content-end pt-2 pb-2">
            <a class="w-25  badge badge-success d-inline" href="users_admin">Liste des clients</a>
        </div>
    </div>

</div>

<div class="col-12 col-lg-3  mt-lg-5 ml-lg-2 mr-lg-3 p-0">
    <div class="row d-flex justify-content-around mr-0 ml-0">
        <div class="col-5 col-lg-10  mb-3 bg-success ">
            <h4 class="text-center">Franco</h4>
            <form method="post" action="admin" id="submit-franco" class="d-flex flex-column align-items-center">
                <input class="w-75 m-1" type="text" name="franco" placeholder="<?=$franco['franco'];?>">
                <button class="w-50 m-1" type="submit" class="button-franco">Modifier</button>
            </form>
        </div>
        <div class="col-5 col-lg-10  mb-3 bg-danger ">
            <h4 class="text-center">Messagerie</h4>
            <p class="text-center">(3) Message(s) en attente <a class="text-dark" href="#">Voir</a></p>
        </div>
        <div class="col-5 col-lg-10  mb-3 bg-primary ">
            <h4 class="text-center">CA du jour</h4>
            <p class="text-center mt-2 mb-2">250,67 €</p>
        </div>
        <div class="col-5 col-lg-10  mb-3 ">
        </div>
    </div>

</div>

</div>
</div>
</main>
<!--Chargement des scripts pour le dashboard admin-->
<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/admin/ajax_admin.js" defer></script>
<!--<div class="container p-0 bg-light border border-dark rounded">-->
<!--    <h2 class="text-center p-0 m-0 bg-primary">Date du jour</h2>-->
<!--    <h4 class="text-center pb-1  bg-primary">--><?//=$dateDuJour?><!--</h4>-->
<!--    <div class="row">-->
<!--        <span class="p-3 ml-1 mr-1">Info à communiquer : Sit enim idem caecus, debilis. Sint ista Graecorum; Quae cum dixisset, finem ille. Cave putes quicquam esse verius. Nam Pyrrho, Aristo, Erillus iam diu abiecti. </span>-->
<!--    </div>-->
<!--</div>-->

<!--<div class="container mt-2  ">-->
<!--    <div class="row d-flex justify-content-between">-->
<!--        <div class="col-12 col-md-3 p-0 mb-3 border border-dark rounded bg-light d-none d-md-block">-->
<!--            <h3 class="text-center p-0 m-0 bg-primary">CA du jour</h3>-->
<!--            <p class="text-center mt-2 mb-2">250,67 €</p>-->
<!--        </div>-->
<!--        <div class="col-12 col-md-3  border p-0 mb-3 border-dark rounded bg-light">-->
<!--            <h3 class="text-center p-0 m-0 bg-primary">Franco</h3>-->
<!--            <p class="text-center">300 € <a class="text-dark" href="#">Modifier</a></p>-->
<!--        </div>-->
<!--        <div class="col-12 col-md-3  border p-0 mb-3 border-dark rounded bg-light">-->
<!--            <h3 class="text-center p-0 m-0 bg-primary">Messagerie</h3>-->
<!--            <p class="text-center">(3) Message(s) en attente <a class="text-dark" href="#">Voir</a></p>-->
<!--        </div>-->
<!---->
<!--    </div>-->
<!--</div>-->

<!--<div class="container">-->
<!--    <div class="row">-->
<!--        <div class="border border-dark rounded bg-light p-0 mb-3 col-12 col-md-7 col-lg-5">-->
<!--            <h3 class="p-0 m-0 text-center bg-primary">Inscription en attente</h3>-->
<!--            <div class=" container bg-light p-1">-->
<!--                <div class="row">-->
<!--                    <div class="col-4"><p>Société</p> </div>-->
<!--                    <div class="col-4"><p>Email</p> </div>-->
<!--                    <div class="col-4"><p>Adresse</p> </div>-->
<!--                </div>-->
<!--            </div>-->
<!--            <div class="text-center justify-content-end bg-light pt-2 pb-2">-->
<!--                <a class="w-25  badge badge-success d-inline" href="users">Voir tous les clients</a>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="col-12 col-md-4 offset-md-1 col-lg-5 offset-lg-2 d-none d-md-block border border-dark rounded bg-light p-0 mb-3 ">-->
<!--            <h3 class="p-0 m-0 text-center bg-primary">Top 5 Articles</h3>-->
<!--            <div class="bg-light p-1">-->
<!--                <p>Pomme</p>-->
<!--                <p>Banane</p>-->
<!--                <p>Kiwi</p>-->
<!--            </div>-->
<!--            <div class="text-center pt-2 pb-2">-->
<!--                <a class="w-25  badge badge-success d-inline" href="articles">Voir tous les articles</a>-->
<!--            </div>-->
<!--        </div>-->
<!--        <div class="border border-dark rounded p-0 bg-light mb-3 col-12 col-md-12">-->
<!--            <h3 class="p-0 m-0 text-center bg-primary">Commande du jour</h3>-->
<!--            <div class=" container p-0">-->
<!--                <div class="row  commande mr-auto ml-auto">-->
<!--                    <div class="col-4"><p>Société</p> </div>-->
<!--                    <div class="col-4"><p>Date de livraison</p> </div>-->
<!--                    <div class="col-3"><p>Montant</p> </div>-->
<!--                    <div class="col-1"><a href="#">Voir</a> </div>-->
<!--                </div>-->
<!--                <div class="row commande mr-auto ml-auto">-->
<!--                    <div class="col-4"><p>Société</p> </div>-->
<!--                    <div class="col-4"><p>Date de livraison</p> </div>-->
<!--                    <div class="col-3"><p>Montant</p> </div>-->
<!--                    <div class="col-1"><a href="#">Voir</a> </div>-->
<!--                </div>-->
<!--                <div class="row commande mr-auto ml-auto">-->
<!--                    <div class="col-4"><p>Société</p> </div>-->
<!--                    <div class="col-4"><p>Date de livraison</p> </div>-->
<!--                    <div class="col-3"><p>Montant</p> </div>-->
<!--                    <div class="col-1"><a href="#">Voir</a> </div>-->
<!--                </div>-->
<!--                <div class="row commande mr-auto ml-auto">-->
<!--                    <div class="col-4"><p>Société</p> </div>-->
<!--                    <div class="col-4"><p>Date de livraison</p> </div>-->
<!--                    <div class="col-3"><p>Montant</p> </div>-->
<!--                    <div class="col-1"><a href="#">Voir</a> </div>-->
<!--                </div>-->
<!---->
<!---->
<!--            </div>-->
<!--            <div class="text-center pt-2 pb-2 bg-light pb-1 pt-1">-->
<!--                <a class="w-100  badge badge-success d-inline" href="commande_admin">Voir toutes les commandes</a>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
