<div class="headerDate">
    <div class="headerDate-date">
        <h4 class=""> TERRANAS</h4>
        <p><?=$params['dateDuJour']?></p>
    </div>
    <div class="headerDate-inscription">
        <h4 class="">INSCRIPTION</h4>
        <p>En attente ( <?=$params['usersInt']?> ) <a href="users_admin">Voir</a> </p>
    </div>
</div>

<div class="templateListe">
    <h4 class="headerTitle">COMMANDE EN ATTENTE</h4>
    <div class="liste">
        <div class="liste-commande head">
            <div class="liste-commande-item">COMMANDE N°</div>
            <div class="liste-commande-item">DATE COMMANDE</div>
            <div class="liste-commande-item">DATE LIVRAISON</div>
            <div class="liste-commande-item">MONTANT</div>
            <div class="liste-commande-item detail">DETAILS</div>
        </div>

<?php if($params['commandeDuJour']) : ?>
    <?php foreach ($params['commandeDuJour'] as $commande): ?>
        <div class="liste-commande" >
            <div class="liste-commande-item" ><?=$commande['id_commande'];?></div>
            <div class="liste-commande-item" ><?=date('d/m/y', strtotime($commande['date_commande']));?></div>
            <div class="liste-commande-item" ><?=date('d/m/y', strtotime($commande['date_livraison'])) ;?></div>
            <div class="liste-commande-item" ><?=($commande['montant']/100) ." €" ;?></div>
            <div class="liste-commande-item detail" ><a href="<?='commande_details?id='.$commande['id_commande'] ;?>"><i class="fa-solid fa-eye"></i></a> </div>
        </div>
    <?php endforeach; ?>
<?php else:?>
        <div class="emptyCommande">
            <p>Aucune commande</p>
        </div>
<?php endif;?>
</div>

<h4 class="headerTitle">COMMANDE VALIDEE</h4>
<div class="liste">
    <div class="liste-commande head">
        <div class="liste-commande-item">COMMANDE N°</div>
        <div class="liste-commande-item">DATE COMMANDE</div>
        <div class="liste-commande-item">DATE LIVRAISON</div>
        <div class="liste-commande-item">MONTANT</div>
        <div class="liste-commande-item detail">DETAILS</div>
    </div>

    <?php if($params['commandeValidee']) : ?>
        <?php foreach ($params['commandeValidee'] as $commande): ?>
            <div class="liste-commande" >
                <div class="liste-commande-item" ><?=$commande['id_commande'];?></div>
                <div class="liste-commande-item" ><?=date('d/m/y', strtotime($commande['date_commande']));?></div>
                <div class="liste-commande-item" ><?=date('d/m/y', strtotime($commande['date_livraison'])) ;?></div>
                <div class="liste-commande-item" ><?=($commande['montant']/100) ." €" ;?></div>
                <div class="liste-commande-item detail" ><a href="<?='commande_details?id='.$commande['id_commande'] ;?>"><i class="fa-solid fa-eye"></i></a> </div>
            </div>
        <?php endforeach; ?>
    <?php else:?>
        <div class="emptyCommande">
            <p>Aucune commande</p>
        </div>
    <?php endif;?>
</div>
</div>

<!--Chargement des scripts pour le dashboard admin-->
<!--<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/admin/ajax_admin.js" defer></script>-->
