<main class="mt-3">
    <div class="container mt-3 mb-3">
        <h2 class="text-center text-red"> Listes des articles</h2>
        <div class="row">
            <div class="col-10 ">
                <form method="POST" action ="articles_admin" class="navbar-form navbar-right" id="form-commande" role="search">
                    <div class="input-group w-75 ">
                        <?php if(empty($_SESSION['articleSearch'])) :?>
                            <input type="search" class="form-control" name="articleSearch" id="articleSearch" placeholder="Rechercher un article" >
                        <?php else : ?>
                            <input type="search" class="form-control" name="articleSearch" id="articleSearch" value="<?=$params['articleSearch'];?>">
                        <?php endif;?>
                    </div>
                </form>
            </div>

            <div class="col-2 col-md-2 text-center">
                <a href="add_article" > <img src="http://localhost/TerrAnanas/public/images/add_icon.png" class="img-responsive mw-100" > <span class="d-none d-md-block">Ajouter un article</span></a>
            </div>
        </div>
    </div>

<div class="container">
    <div class="row">
        <div class="col-12 border-custom bg-second-background-color pt-2 pb-3 pl-0 pr-0 view">

<!--            --><?php //include $params['view'];?>
            <?php $this->render($this->file, 'liste_articles_admin', '', $params);?>

<!---->
<!--            --><?php //if(empty($_SESSION['articleSearch'])) :?>
<!--                <div class="container-fluide">-->
<!--                    <h3 class="text-center text-red m-0 p-2">Légumes</h3>-->
<!--                    <div class="container p-0 bg-light">-->
<!--                        <div class="row bg-first-lightbackground-color pt-2 pb-2 m-0">-->
<!---->
<!--                            <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Article</p> </div>-->
<!--                            <div class="col-2 d-md-none text-center font-weight-bold"> <p>Art</p> </div>-->
<!--                            <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Origine</p> </div>-->
<!--                            <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Ori</p> </div>-->
<!--                            <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prix/Unitée</p> </div>-->
<!--                            <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prx/Ute</p> </div>-->
<!--                            <div class="col-2 d-none d-sm-block text-center font-weight-bold"> <p>Poids</p> </div>-->
<!--                            <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Statut</p> </div>-->
<!--                            <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p class="d-md-none">Détails</p> </div>-->
<!--                            <div class="col-2 d-md-none text-center font-weight-bold"> <p class="d-md-none">Dts</p> </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                        --><?php //foreach ($params['articles'] as $article): ?>
<!--                            --><?php //if($article['famille']=="Légume" && $article['id_statutArticle']!=3):?>
<!--                                <div class="row line-out pt-2 pb-2 m-0">-->
<!--                                    <div class="col-2 text-center">--><?//= $article["article"];?><!-- </div>-->
<!--                                    <div class="col-4 col-sm-3 col-md-2 text-center ">--><?//= $article["origine"];?><!-- </div>-->
<!--                                    <div class="col-4 col-sm-3 col-md-2 text-center ">--><?//= ($article["prix"]/100)." €/".$article['unite'];?><!--  </div>-->
<!--                                    <div class="col-2 d-none d-sm-block text-center ">--><?//= $article["poids"] ." " .$article['unite'];?><!-- </div>-->
<!--                                    <div class="col-2 d-none d-md-block text-center ">--><?//= $article["statutArticle"];?><!-- </div>-->
<!--                                    <div class="col-1 d-none d-md-block text-center"> <a href="--><?//='edit_article?id='.$article["id_article"];?><!--"><i class="fa-solid fa-pen-to-square"></i></a></div>-->
<!--                                    <div class="col-1 d-none d-md-block text-center"> <a href="--><?//='delete_article?id='.$article["id_article"];?><!--"><i class="fa-solid fa-trash-can"></i></a> </div>-->
<!--                                    <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>-->
<!--                                </div>-->
<!--                            --><?php //endif ;?>
<!--                        --><?php //endforeach; ?>
<!--                </div>-->
<!---->
<!--                <div class="container-fluide ">-->
<!--                    <h3 class="text-center text-red m-0 p-2 " >Fruits</h3>-->
<!--                    <div class="container p-0 bg-light">-->
<!--                        <div class="row bg-first-lightbackground-color pt-2 pb-2 m-0">-->
<!--                            <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Article</p> </div>-->
<!--                            <div class="col-2 d-md-none text-center font-weight-bold"> <p>Art</p> </div>-->
<!--                            <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Origine</p> </div>-->
<!--                            <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Ori</p> </div>-->
<!--                            <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prix/Unitée</p> </div>-->
<!--                            <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prx/Ute</p> </div>-->
<!--                            <div class="col-2 d-none d-sm-block text-center font-weight-bold"> <p>Poids</p> </div>-->
<!--                            <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Statut</p> </div>-->
<!--                            <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p class="d-md-none">Détails</p> </div>-->
<!--                            <div class="col-2 d-md-none text-center font-weight-bold"> <p class="d-md-none">Dts</p> </div>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                        --><?php //foreach ($params['articles'] as $article): ?>
<!--                            --><?php //if($article['famille']=="Fruit" && $article['id_statutArticle']!=3):?>
<!--                                <div class="row line-out pt-2 pb-2 m-0">-->
<!--                                    <div class="col-2 text-center">--><?//= $article["article"];?><!-- </div>-->
<!--                                    <div class="col-4 col-sm-3 col-md-2 text-center">--><?//= $article["origine"];?><!-- </div>-->
<!--                                    <div class="col-4 col-sm-3 col-md-2 text-center">--><?//= ($article["prix"]/100)." €/".$article['unite'];?><!--  </div>-->
<!--                                    <div class="col-2 d-none d-sm-block text-center">--><?//= $article["poids"] ." " .$article['unite'];?><!-- </div>-->
<!--                                    <div class="col-2 d-none d-md-block text-center">--><?//= $article["statutArticle"];?><!-- </div>-->
<!--                                    <div class="col-1 d-none d-md-block text-center"> <a href="--><?//='edit_article?id='.$article["id_article"];?><!--"><i class="fa-solid fa-pen-to-square"></i></a></div>-->
<!--                                    <div class="col-1 d-none d-md-block text-center"> <a href="--><?//='delete_article?id='.$article["id_article"];?><!--"><i class="fa-solid fa-trash-can"></i></a> </div>-->
<!--                                    <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>-->
<!--                                </div>-->
<!--                            --><?php //endif ;?>
<!--                        --><?php //endforeach; ?>
<!--                </div>-->
<!---->
<!--            --><?php //else : ?>
<!--                <div class="container-fluid p-0 bg-light">-->
<!--                    --><?php //foreach ($_SESSION['articleSearch'] as $article): ?>
<!--                        <div class="container p-0 bg-light">-->
<!--                            <div class="row bg-first-lightbackground-color pt-2 pb-2 m-0">-->
<!---->
<!--                                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Article</p> </div>-->
<!--                                <div class="col-2 d-md-none text-center font-weight-bold"> <p>Art</p> </div>-->
<!--                                <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Origine</p> </div>-->
<!--                                <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Ori</p> </div>-->
<!--                                <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prix/Unitée</p> </div>-->
<!--                                <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prx/Ute</p> </div>-->
<!--                                <div class="col-2 d-none d-sm-block text-center font-weight-bold"> <p>Poids</p> </div>-->
<!--                                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Statut</p> </div>-->
<!--                                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p class="d-md-none">Détails</p> </div>-->
<!--                                <div class="col-2 d-md-none text-center font-weight-bold"> <p class="d-md-none">Dts</p> </div>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <div class="row line-out pt-2 pb-2 m-0">-->
<!--                            <div class="col-2 text-center">--><?//= $article["article"];?><!-- </div>-->
<!--                            <div class="col-4 col-sm-3 col-md-2 text-center">--><?//= $article["origine"];?><!-- </div>-->
<!--                            <div class="col-4 col-sm-3 col-md-2 text-center">--><?//= ($article["prix"]/100)." €/".$article['unite'];?><!--  </div>-->
<!--                            <div class="col-2 d-none d-sm-block text-center">--><?//= $article["poids"] ." " .$article['unite'];?><!-- </div>-->
<!--                            <div class="col-2 d-none d-md-block text-center">--><?//= $article["statutArticle"];?><!-- </div>-->
<!--                            <div class="col-1 d-none d-md-block text-center"> <a href="--><?//='edit_article?id='.$article["id_article"];?><!--"><i class="fa-solid fa-pen-to-square"></i></a></div>-->
<!--                            <div class="col-1 d-none d-md-block text-center"> <a href="--><?//='delete_article?id='.$article["id_article"];?><!--"><i class="fa-solid fa-trash-can"></i></a> </div>-->
<!--                            <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>-->
<!--                        </div>-->
<!--                    --><?php //endforeach; ?>
<!--                </div>-->
<!--            --><?php //endif;?>

        </div>
    </div>
</div>

</main>
<script src="http://localhost/TerrAnanas/public/js/articles_admin.js" defer></script>