<main>


<head>
    <div class="container mt-3 mb-3">
        <div class="row">
            <div class="col-10 col-md-8">
                <form method="GET" action ="articles_admin" class="navbar-form navbar-right" role="search">
                    <div class="input-group w-75 ">
                        <?php if(empty($_SESSION['articleSearch'])) :?>
                            <input type="search" class="form-control" name="articleSearch" placeholder="Rechercher un article" >

                        <?php else : ?>
                            <input type="search" class="form-control" name="articleSearch" value="<?= $params['articleSearch'];?>">
                        <?php endif;?>

                        <span class="input-group-btn">
                        <button type="submit" class="btn btn-default bg-custom-red" >
                            Valider
                        <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                </form>
            </div>
            <div class="col-2 col-md-4 text-center">
                <a href="add_article" > <img src="http://localhost/TerrAnanas/public/images/add_icon.png" class="img-responsive mw-100" > <span class="d-none d-md-block">Ajouter un article</span></a>
            </div>

        </div>
    </div>

</head>
<div class="container">
    <div class="row">
        <div class="col-12 border rounded-2 tableColor-green pt-2 pb-3 pl-0 pr-0">
            <h2 class="text-center"> Listes des articles</h2>
            <div class="container p-0 bg-light">
                <div class="row pt-2 pb-2 m-0">

                    <div class="col-2  text-center"> <p>Label</p> </div>
                    <div class="col-4 col-sm-3 col-md-2 text-center"> <p>Origine</p> </div>
                    <div class="col-4 col-sm-3 col-md-2 text-center"> <p>Prix/Unitée</p> </div>
                    <div class="col-2 d-none d-sm-block text-center"> <p>Poids</p> </div>
                    <div class="col-2 d-none d-md-block text-center"> <p>Statut</p> </div>
                    <div class="col-2  text-center"> <p class="d-md-none">Détails</p> </div>
                </div>
            </div>

            <?php if(empty($_SESSION['articleSearch'])) :?>
                <div class="container-fluide bg-light ">
                    <h3 class="text-center m-0 p-2">Légumes</h3>
                        <?php foreach ($params['articles'] as $article): ?>
                            <?php if($article['label_famille']=="Légume"):?>
                                <div class="row commande pt-2 pb-2 m-0">
                                    <div class="col-2 text-center"><?= $article["label_article"];?> </div>
                                    <div class="col-4 col-sm-3 col-md-2 text-center"><?= $article["origine"];?> </div>
                                    <div class="col-4 col-sm-3 col-md-2 text-center"><?= ($article["prix"]/100)." €/".$article['label_unite'];?>  </div>
                                    <div class="col-2 d-none d-sm-block text-center"><?= $article["poids"] ." " .$article['label_unite'];?> </div>
                                    <div class="col-2 d-none d-md-block text-center"><?= translateStatusArticle($article["status"]);?> </div>
                                    <div class="col-1 d-none d-md-block text-center"> <a href="<?='edit_article?id='.$article["id_article"];?>"><i class="fa-solid fa-pen-to-square"></i></a></div>
                                    <div class="col-1 d-none d-md-block text-center"> <a href="<?='delete_article?id='.$article["id_article"];?>"><i class="fa-solid fa-trash-can"></i></a> </div>
                                    <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>
                                </div>
                            <?php endif ;?>
                        <?php endforeach; ?>
                </div>

                <div class="container-fluide bg-light">
                    <h3 class="text-center m-0 p-2 " >Fruits</h3>
                        <?php foreach ($params['articles'] as $article): ?>
                            <?php if($article['label_famille']=="Fruit"):?>
                                <div class="row commande pt-2 pb-2 m-0">
                                    <div class="col-2 text-center"><?= $article["label_article"];?> </div>
                                    <div class="col-4 col-sm-3 col-md-2 text-center"><?= $article["origine"];?> </div>
                                    <div class="col-4 col-sm-3 col-md-2 text-center"><?= ($article["prix"]/100)." €/".$article['label_unite'];?>  </div>
                                    <div class="col-2 d-none d-sm-block text-center"><?= $article["poids"] ." " .$article['label_unite'];?> </div>
                                    <div class="col-2 d-none d-md-block text-center"><?= translateStatusArticle($article["status"]);?> </div>
                                    <div class="col-1 d-none d-md-block text-center"> <a href="<?='edit_article?id='.$article["id_article"];?>"><i class="fa-solid fa-pen-to-square"></i></a></div>
                                    <div class="col-1 d-none d-md-block text-center"> <a href="<?='delete_article?id='.$article["id_article"];?>"><i class="fa-solid fa-trash-can"></i></a> </div>
                                    <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>
                                </div>
                            <?php endif ;?>
                        <?php endforeach; ?>
                </div>

            <?php else : ?>
                <div class="container-fluid p-0 bg-light">
                    <?php foreach ($_SESSION['articleSearch'] as $article): ?>
                        <div class="row commande pt-2 pb-2 m-0">
                            <div class="col-2 text-center"><?= $article["label_article"];?> </div>
                            <div class="col-4 col-sm-3 col-md-2 text-center"><?= $article["origine"];?> </div>
                            <div class="col-4 col-sm-3 col-md-2 text-center"><?= ($article["prix"]/100)." €/".$article['label_unite'];?>  </div>
                            <div class="col-2 d-none d-sm-block text-center"><?= $article["poids"] ." " .$article['label_unite'];?> </div>
                            <div class="col-2 d-none d-md-block text-center"><?= translateStatusArticle($article["status"]);?> </div>
                            <div class="col-1 d-none d-md-block text-center"> <a href="<?='edit_article?id='.$article["id_article"];?>"><i class="fa-solid fa-pen-to-square"></i></a></div>
                            <div class="col-1 d-none d-md-block text-center"> <a href="<?='delete_article?id='.$article["id_article"];?>"><i class="fa-solid fa-trash-can"></i></a> </div>
                            <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif;?>

        </div>
    </div>
</div>

</main>