<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="http://localhost/TerrAnanas/public/css/adminStyles.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oxygen&display=swap" rel="stylesheet">

<!--    <script type="text/javascript" src="http://localhost/TerrAnanas/public/js/responsive.js" defer></script>-->
    <script type="module" src="http://localhost/TerrAnanas/public/js/admin.js" defer></script>

    <title><?=$params['title'];?></title>
</head>

<body>
<header>

    <nav class="adminNavbar">
        <div class="adminNavbar-function" >
            <div class="adminNavbar-function-burger" id="menuresp">
                <i class="fa-solid fa-bars" id="burger"></i>
                <i class="fa-sharp fa-solid fa-xmark hide" id="cross"></i>
            </div>
            <ul class="adminNavbar-function-list "  >
                <li class="adminNavbar-function-list-item">
                    <a class="adminNavbar-function-list-item-link" href="admin">Dashboard</a>
                </li>
                <li class="adminNavbar-function-list-item">
                    <a class="adminNavbar-function-list-item-link" href="articles_admin">Articles</a>
                </li>
                <li class="adminNavbar-function-list-item">
                    <a class="adminNavbar-function-list-item-link" href="users_admin">Clients</a>
                </li>
                <li class="adminNavbar-function-list-item">
                    <a class="adminNavbar-function-list-item-link" href="commandes_admin">Commandes</a>
                </li>
                <li class="adminNavbar-function-list-item">
                    <a class="adminNavbar-function-list-item-link" href="messages">Messages</a>
                </li>
            </ul>
        </div>


        <div class="adminNavbar-info" >
            <ul class="adminNavbar-info-list">
                <li class="adminNavbar-info-list-item">
                    <p class="adminNavbar-info-list-item-dropdown">
                        <?=getUserName()?>
                        <i class="fa-solid fa-caret-down"></i>
                    </p>
                    <ul class="adminNavbar-info-list-item-dropdownContent">
                        <li><a class="" href="home">Accueil TerrAnanas</a></li>
                        <li><a class="" href="client">Faire un test</a></li>
                        <li><a class="" href="parametre_admin">Paramètre</a></li>
                        <li class="logout"><a  href="logout">Se déconnecter</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>

</header>

<main>
    <?php include $template; ?>

</main>

<!--Chargement des scripts pour Bootstrap-->
<!--<script type="text/javascript" src="http://localhost/TerrAnanas/public/js/jquery-3.3.1.min.js" defer></script>-->
<!--<script type="text/javascript" src="http://localhost/TerrAnanas/public/js/bootstrap.js" defer></script>-->

<!-- Script pour activation du datepicker -->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" defer></script>-->
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" defer></script>-->
<!--<script src="http://localhost/TerrAnanas/public/js/script.js" defer></script>-->
</body>

</html>