<h3 class="headerTitle"> Commandes </h3>

<form method="post" action="historique_commandes" id="form-commande" class="formCommande">
    <div class="headerCommande">
        <div class="headerCommande-date">
            <?php if(empty($_SESSION['commandeByDate'])) :?>
                <input type="date" class="form-control" name="searchDate" placeholder="Choisir une date"id="reservationDate">
            <?php else : ?>
                <input type="date" class="form-control" name="searchDate" value="<?= $params['date'];?>"id="reservationDate">
            <?php endif;?>
            <input type="reset" class="buttonReset" value="Réinitialiser">
        </div>

        <div class="headerCommande-statut">
            <?php if($params['commandes']):?>
                <select class="form-control " name="statut" id="selectStatut">
                    <option value="<?= $params['commandes'][0]['id_statut'] ?>"><?= $params['commandes'][0]['statut'] ?></option>
                    <?php foreach ($params['statut'] as $statut): ?>
                        <?php if($statut['id_statut'] != $params['commandes'][0]['id_statut']): ?>
                            <option value="<?=$statut['id_statut'];?>"><?=$statut['statut'];?></option>
                        <?php endif ;?>
                    <?php endforeach; ?>
                </select>
            <?php else : ?>
                <select class="form-control " name="statut" id="selectStatut">
                    <option value="<?= $params['statutCommande'] ?>"><?= $params['nameStatut']['statut'] ?></option>
                    <?php foreach ($params['statut'] as $statut): ?>
                        <?php if($statut['id_statut'] != $params['statutCommande'] ): ?>
                            <option value="<?=$statut['id_statut'];?>"><?=$statut['statut'];?></option>
                        <?php endif ;?>
                    <?php endforeach; ?>
                </select>
            <?php endif; ?>
        </div>
    </div>

</form>

<div class="templateListe">
    <?php $this->render($this->file, 'liste_commandes_admin', '', $params);?>

</div>

