 <main class="mt-5">
    <div class="container border-custom bg-second-background-color">
        <div class="row">
            <div class="col-12 p-0">
                <h3 class="text-center text-red mt-2 mb-3"> Commande numéro : <?=$params['idCommande'];?> </h3>
                    <div class="container">
                        <div class="row pt-3 bg-second-lightbackground-color text-center form-details">
                            <div class="col-12 col-md-6 mb-3 mb-md-4 ">
                                <label>Client  : </label>
                                <p><?=$params['client']['society'];?></p>
                            </div>
                            <div class="col-12 col-md-6 mb-3 mb-md-4 ">
                                <label>Adresse : </label>
                                <p><?=$params['client']['address'];?></p>
                            </div>
                            <div class="col-12 col-md-6 mb-3 mb-md-4 ">
                                <label>Ville : </label>
                                <p><?=$params['client']['city'];?></p>
                            </div>
                            <div class="col-12 col-md-6  mb-3 mb-md-4 ">
                                <label>Code postal : </label>
                                <p><?=$params['client']['postal'];?></p>
                            </div>
                            <div class="col-12 col-md-6  mb-3 mb-md-4 ">
                                <label>Personne à contacter : </label>
                                <p><?=$params['client']['contact'];?></p>
                            </div>
                            <div class="col-12 col-md-6  mb-3 mb-md-4 ">
                                <label>Téléphone : </label>
                                <p><?=$params['client']['phone'];?></p>
                            </div>
                            <div class="col-12 col-md-6  mb-3 mb-md-4 ">
                                <label>Email : </label>
                                <p><?=$params['client']['email'];?></p>
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
     <div class="container mt-3 border-custom bg-second-background-color">
         <div class="row">
             <div class="col-12">
                <div class="container bg-first-lightbackground-color">
                    <div class="row">
                        <div class="col-3 text-center"> <label>Article </div>
                        <div class="col-3 col-sm-2 text-center"> <label>Origine</label> </div>
                        <div class="col-4 col-md-3 text-center"> <label>Prix</label> </div>
                        <div class="col-2 d-none d-sm-block text-center"> <label>Poids</label> </div>
                        <div class="col-2 text-center"> </div>
                    </div>
                </div>
                <form method="post" action="<?='commande_details?id='.$params['idCommande'];?>">
                    <div class="container ">
                        <?php foreach ($params['articlesCommande'] as $article): ?>
                                    <div class="row line-out">
                                        <input type="hidden" name="id_article[]" value="<?=$article['id_article'];?>">
                                        <input type="hidden" name="label_unite[]" value="<?=$article['label_unite'];?>">
                                        <div class="col-3 text-center"><input type="hidden" name="label_article[]" value="<?= $article["label_article"];?>"><?= $article["label_article"];?> </div>
                                        <div class="col-3 col-sm-2 text-center"><input type="hidden" name="origine[]" value=" <?= $article["origine"];?>"> <?= $article["origine"];?></div>
                                        <div class="col-4 col-sm-3"><input class="w-50 text-center" type="text" name="prix[]" value="<?= ($article["prix"]/100);?>"><?='€/'.$article['label_unite'];?>  </div>
                                        <div class="col-2 d-none d-sm-block text-center"><input type="hidden" name="poids[]" value="<?= $article["poids"];?>"><?= $article["poids"] ." " .$article['label_unite'];?> </div>
                                        <div class="col-2 p-0 text-center"><input class="w-50 text-center" type="number" id="quantite" name="quantite[]" min="0" value="<?=$article['quantite'];?>"></div>                                </div>
                        <?php endforeach; ?>
                    </div>
                    <div class="mt-3 d-flex flex-row justify-content-center">
                        <select class="form-control w-50" name="status" id="status">
                            <option value="<?= $params['commande']['id_status'] ?>"><?= $params['commande']['label_status'] ?></option>
                            <?php foreach ($params['status'] as $status): ?>
                                <?php if($status['id_status'] != $params['commande']['id_status']): ?>
                                    <option value="<?=$status['id_status'];?>"><?=$status['label_status'];?></option>
                                <?php endif ;?>
                            <?php endforeach; ?>
                        </select>
                        <button type="submit" class="btn btn-primary"> Valider </button>
                    </div>
                </form>
             </div>
         </div>
     </div>
        </div>
    </div>
</div>

</main>