<h3 class="headerTitle"> Commande numéro : <?=$params['idCommande'];?>  </h3>

<div class="infos">
    <p>Afficher / Masquer</p>
    <div class="infos-toggle">
<!--        <p>Afficher / Masquer</p>-->
        <i class="fa-solid fa-eye"></i>
        <i class="fa-solid fa-eye-slash hidden"></i>
    </div>
    <div class="infos-client hidden">
        <div class="infos-client-item">
            <label>Client  : </label>
            <p><?=$params['client']['client'];?></p>
        </div>
        <div class="infos-client-item">
            <label>Adresse : </label>
            <p><?=$params['client']['address'];?></p>
        </div>
        <div class="infos-client-item">
            <label>Ville : </label>
            <p><?=$params['client']['city'];?></p>
        </div>
        <div class="infos-client-item">
            <label>Code postal : </label>
            <p><?=$params['client']['postal'];?></p>
        </div>
        <div class="infos-client-item">
            <label>Personne à contacter : </label>
            <p><?=$params['client']['contact'];?></p>
        </div>
        <div class="infos-client-item">
            <label>Téléphone : </label>
            <p><?=$params['client']['phone'];?></p>
        </div>
        <div class="infos-client-item">
            <label>Email : </label>
            <p><?=$params['client']['email'];?></p>
        </div>
    </div>
</div>


<form method="post" action="<?='commande_details_admin?id='.$params['idCommande'];?>" class="formDetailsCommande">

<div class="liste">
    <div class="articleCommande head">
        <div class="col-3 d-none d-md-block  text-center"> <label>Article </div>
        <div class="d-none d-md-block col-3 col-sm-2 text-center"> <label>Origine</label> </div>
        <div class="col-4 col-md-3 text-center"> <label>Prix</label> </div>
        <div class="col-2 d-none d-sm-block text-center"> <label>Poids</label> </div>
        <div class="d-none d-md-block col-2 text-center">Quantitée</div>
    </div>

    <?php foreach ($params['articlesCommande'] as $article): ?>
        <div class="articleCommande">
            <input type="hidden" name="id_article[]" value="<?=$article['id_article'];?>">
            <input type="hidden" name="unite[]" value="<?=$article['unite'];?>">
            <div class="articleCommande-item"><input type="hidden" name="article[]" value="<?= $article["article"];?>"><?= $article["article"];?> </div>
            <div class="articleCommande-item"><input type="hidden" name="origine[]" value=" <?= $article["origine"];?>"> <?= $article["origine"];?></div>
            <div class="articleCommande-item prix"><input type="text" name="prix[]" value="<?= ($article["prix"]/100);?>"><?='€/'.$article['unite'];?>  </div>
            <div class="articleCommande-item"><input type="hidden" name="poids[]" value="<?= $article["poids"];?>"><?= $article["poids"] ." " .$article['unite'];?> </div>
            <div class="articleCommande-item quantite"><input type="number" id="quantite" name="quantite[]" min="0" value="<?=$article['quantite'];?>"></div>
        </div>
    <?php endforeach; ?>

</div>

    <div class="selectCommande">
        <select class="" name="statut" id="statut">
            <option value="<?= $params['commande']['id_statut'] ?>"><?= $params['commande']['statut'] ?></option>
            <?php foreach ($params['statut'] as $statut): ?>
                <?php if($statut['id_statut'] != $params['commande']['id_statut']): ?>
                    <option value="<?=$statut['id_statut'];?>"><?=$statut['statut'];?></option>
                <?php endif ;?>
            <?php endforeach; ?>
        </select>
        <button type="submit" class="btn bg-alt-background-color text-darkgreen"> Valider </button>
    </div>
</form>

 <script src="http://localhost/TerrAnanas/public/js/commande_details.js" defer></script>