<main>

<div class="container">
    <div class="row">
        <div class="col-12 p-0">

            <table class="table border border-dark">
                <h3 class="text-center" >Détails commande</h3>
                <tr>
                    <th scope="row">ID</th>
                    <td><?=$params['idCommande'];?></td>
                </tr>
                <tr>
                    <th scope="col">Société</th>
                    <th scope="col"><?=$params['client']['society'];?></th>
                </tr>
                <tr>
                    <th scope="row">Adresse de livraison</th>
                    <td><?=$params['client']['address'] .", ".$params['client']['city'] ." ".$params['client']['postal'];?></td>
                </tr>
                <tr>
                    <th scope="row">Date de commande</th>
                    <td><?=$params['dateCommande'] ;?></td>
                </tr>
                <tr>
                    <th scope="row">Date de livraison </th>
                    <td><?=$params['dateLivraison'];?></td>
                </tr>
                <tr>
                    <th scope="row">Email</th>
                    <td><?=$params['client']['email'] ;?></td>
                </tr>
                <tr>
                    <th scope="row">Téléphone</th>
                    <td>
                        <?php if(!$params['client']['phone']): ?>
                            <?=$params['client']['phone'];?>
                        <?php endif; ?>
                    </td>
                </tr>
                <tr>
                    <th scope="row">Personne à contacter</th>
                    <td>
                        <?php if(!$params['client']['contact']): ?>
                            <?=$params['client']['contact'];?>
                        <?php endif; ?>
                    </td>
                </tr>
            </table>



            <div class="border border-dark">
            <div class="container ">
                <div class="row">
                    <div class="col-3 text-center"> <p>Article</p> </div>
                    <div class="col-3 col-sm-2 text-center"> <p>Origine</p> </div>
                    <div class="col-4 col-md-3 text-center"> <p>Prix</p> </div>
                    <div class="col-2 d-none d-sm-block text-center"> <p>Poids</p> </div>
                    <div class="col-2 text-center"> </div>
                </div>
            </div>
            <form method="post" action="<?='commande_details?id='.$params['idCommande'];?>">
                <div class="container">
                    <?php foreach ($params['articlesCommande'] as $article): ?>
                                <div class="row commande">
                                    <input type="hidden" name="id_article[]" value="<?=$article['id_article'];?>">
                                    <input type="hidden" name="label_unite[]" value="<?=$article['label_unite'];?>">
                                    <div class="col-3 text-center"><input type="hidden" name="label_article[]" value="<?= $article["label_article"];?>"><?= $article["label_article"];?> </div>
                                    <div class="col-3 col-sm-2 text-center"><input type="hidden" name="origine[]" value=" <?= $article["origine"];?>"> <?= $article["origine"];?></div>
                                    <div class="col-4 col-sm-3"><input class="w-50 text-center" type="text" name="prix[]" value="<?= ($article["prix"]/100);?>"><?='€/'.$article['label_unite'];?>  </div>
                                    <div class="col-2 d-none d-sm-block text-center"><input type="hidden" name="poids[]" value="<?= $article["poids"];?>"><?= $article["poids"] ." " .$article['label_unite'];?> </div>
                                    <div class="col-2 p-0 text-center"><input class="w-50 text-center" type="number" id="quantite" name="quantite[]" min="0" value="<?=$article['quantite'];?>"></div>                                </div>
                    <?php endforeach; ?>
                </div>
                <div class="mt-3 d-flex flex-row justify-content-center">
                    <select class="form-control w-50" name="status" id="status">
                        <option value="<?= $params['commande']['id_status'] ?>"><?= $params['commande']['label_status'] ?></option>
                        <?php foreach ($params['status'] as $status): ?>
                            <?php if($status['id_status'] != $params['commande']['id_status']): ?>
                                <option value="<?=$status['id_status'];?>"><?=$status['label_status'];?></option>
                            <?php endif ;?>
                        <?php endforeach; ?>
                    </select>
                    <button type="submit" class="btn btn-primary"> Valider </button>
                </div>
            </form>

            </div>

        </div>
    </div>
</div>

</main>