<h3 class="headerTitle">Modification : <?=$params['label'];?></h3>


<form method="POST" action="<?='edit_article?id='.$params['article']['id_article'];?>" enctype="multipart/form-data" class="formAddArticle">

    <div class="article">
        <div class="article-item">
            <label class="" for="label"> Article </label>
            <input type="text" class="form-control" id="label" name="label" value="<?=$params['label'];?>">
        </div>

        <div class="article-item">
            <label class="mb-1 font-weight-bold" for="origine">Origine</label>
            <input type="text" class="form-control" id="origine" name="origine" value="<?=$params['origine'];?>">
        </div>

        <div class="article-item">
            <label class="mb-1 font-weight-bold" for="prix">Prix</label>
            <input type="text" class="form-control" id="prix" name="prix" value="<?=$params['prix']/100;?>">
        </div>

        <div class="article-item">
            <label class="mb-1 font-weight-bold" for="poids">Poids</label>
            <input type="text" class="form-control" id="poids" name="poids" value="<?=$params['poids'];?>">
        </div>

        <div class="article-item">
            <label for="image">Image</label>
            <input type="file" class="form-control" id="image" name="image">
        </div>

        <div class="article-item">
            <label class="mb-1 font-weight-bold" for="unite">Unite</label>
            <select class="form-control" name="unite" id="unite">
                <option value="<?=$params['article']['id_unite'];?>"><?=$params['article']['unite'];?></option>
                <?php foreach ($params['unites'] as $unite): ?>
                    <?php if($unite['id_unite']!=$params['article']['id_unite']): ?>
                        <option value="<?=$unite['id_unite'];?>"><?=$unite['unite'];?></option>
                    <?php endif ;?>
                <?php endforeach; ?>
            </select>
            <?php if (isset($error['unite'])): ?>
                <p class="error"><?=htmlspecialchars($error['unite']);?></p>
            <?php endif; ?>
        </div>
        <div class="article-item">
            <label class="" for="famille">Famille</label>
            <select class="form-control" name="famille" id="famille">
                <option value="<?=$params['article']['id_famille'];?>"><?=$params['article']['famille'];?></option>
                <?php foreach ($params['familles'] as $famille): ?>
                    <?php if($famille['id_famille']!=$params['article']['id_famille']): ?>
                        <option value="<?=$famille['id_famille'];?>"><?=$famille['famille'];?></option>
                    <?php endif ;?>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="article-item">
            <label class="" for="statut">Disponibilité</label>
            <select class="form-control" name="statutArticle" id="statutArticle">
                <option value="<?=$params['article']['id_statutArticle'];?>"><?=$params['article']['statutArticle'];?></option>
                <?php foreach ($params['statut'] as $statut): ?>
                    <?php if($statut['id_statutArticle']!=$params['article']['id_statutArticle']): ?>
                        <option value="<?=$statut['id_statutArticle'];?>"><?=$statut['statutArticle'];?></option>
                    <?php endif ;?>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="article-item">
            <button type="submit" >Modifier</button>
        </div>
    </div>

</form>
