<main class="p-0 pt-md-4 pb-md-4">

    <div class="container border rounded-2 tableColor-green ">
        <div class="row">
            <div class="col-12 p-0">
                <h3 class="text-center text-custom-color-red mt-2 mb-3"> Modification : <?=$params['label'];?> </h3>
                <form method="POST" action="<?='edit_article?id='.$params['article']['id_article'];?>">
                    <div class="container">
                        <div class="row mt-2">
                            <div class="col-12 col-md-6 text-center mb-3 mb-md-5 ">
                                <label class="mb-1" for="label" > Article </label>
                                <input type="text" class="form-control" id="label" name="label" value="<?=$params['label'];?>">
                            </div>
                            <div class="col-12 col-md-6 text-center mb-3 mb-md-5">
                                <label class="mb-1" for="origine">Origine</label>
                                <input type="text" class="form-control" id="origine" name="origine" value="<?=$params['origine'];?>">
                            </div>
                            <div class="col-12 col-md-6  text-center mb-3 mb-md-5">
                                <label class="mb-1" for="prix">Prix</label>
                                <input type="text" class="form-control" id="prix" name="prix" value="<?=$params['prix']/100;?>">
                            </div>
                            <div class="col-12 col-md-6  text-center mb-3 mb-md-5">
                                <label class="mb-1" for="poids">Poids</label>
                                <input type="text" class="form-control" id="quantité" name="poids" value="<?=$params['poids'];?>">
                            </div>
                            <div class="col-12 col-md-6  text-center mb-3 mb-md-5">
                                <label class="mb-1" for="unite">Unite</label>
                                <select class="form-control" name="unite" id="unite">
                                    <option value="<?=$params['article']['id_unite'];?>"><?=$params['article']['label_unite'];?></option>
                                    <?php foreach ($params['unites'] as $unite): ?>
                                        <?php if($unite['id_unite']!=$params['article']['id_unite']): ?>
                                            <option value="<?=$unite['id_unite'];?>"><?=$unite['label_unite'];?></option>
                                        <?php endif ;?>
                                    <?php endforeach; ?>
                                </select>
                                <?php if (isset($error['unite'])): ?>
                                    <p class="error"><?=htmlspecialchars($error['unite']);?></p>
                                <?php endif; ?>
                            </div>
                            <div class="col-12 col-md-6  text-center mb-3 mb-md-5">
                                <label class="mb-1" for="famille">Famille</label>
                                <select class="form-control" name="famille" id="famille">
                                    <option value="<?=$params['article']['id_famille'];?>"><?=$params['article']['label_famille'];?></option>
                                    <?php foreach ($params['familles'] as $famille): ?>
                                        <?php if($famille['id_famille']!=$params['article']['id_famille']): ?>
                                            <option value="<?=$famille['id_famille'];?>"><?=$famille['label_famille'];?></option>
                                        <?php endif ;?>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <div class="col-12 col-md-6 offset-md-3 text-center mb-3 mb-md-5">
                                <label class="mb-1" for="famille">Disponibilité</label>
                                <select class="form-control" name="status" id="status">
                                    <option value="<?=$params['status'];?>"><?=translateStatusArticle($params['status']);?></option>
<!--                                    --><?php //foreach ($status as $statu): ?>
                                        <?php if($params['status']== 0 ): ?>
                                            <option value="1"><?=translateStatusArticle(1);?></option>
                                        <?php else : ?>
                                            <option value="0"><?=translateStatusArticle(0);?></option>
                                        <?php endif ;?>
<!--                                    --><?php //endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="text-center justify-content-end ">
                        <button type="submit" class="btn mb-2 bg-custom-red ">Valider</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>