<div class="liste bg">
    <div class="liste-client head">
        <div class="liste-client-item"> Société </div>
        <div class="liste-client-item address"> Adresse </div>
        <div class="liste-client-item"> Contact </div>
        <div class="liste-client-item"> Téléphone </div>
        <div class="liste-client-item"> Email </div>
        <div class="liste-client-item action">
            <div class="action-edit"> Editer </div>
            <div class="action-delete"> Supprimer </div>
        </div>
    </div>

<?php if(isset($_SESSION['userSearch'])) :?>
    <?php if(empty($_SESSION['userSearch'])):?>
            <div class="liste-client-aucun">
                <p>Aucun client trouvé</p>
            </div>

    <?php else : ?>
        <?php foreach ($_SESSION['userSearch'] as $user): ?>
        <div class="liste-client">
            <div class="liste-client-item"><?= $user["client"];?>  </div>
            <div class="liste-client-item address"><?= $user["address"] .', '.$user["city"].' '.$user["postal"];?>  </div>
            <div class="liste-client-item"><?= $user["contact"];?> </div>
            <div class="liste-client-item"><?= $user["phone"];?> </div>
            <div class="liste-client-item"><?= $user["email"];?> </div>
            <div class="liste-client-item action">
                <div class="action-edit"> <a href="<?='edit_user?id='.$user["id_user"];?>"><i class="fa-solid fa-pen-to-square"></i></a></div>
                <div class="action-delete"> <a href="<?='delete_user?id='.$user["id_user"];?>"><i class="fa-solid fa-trash-can"></i></a></div>
            </div>
        </div>
        <?php endforeach; ?>
    <?php endif;?>
<?php else:?>
    <?php if($params['users']) : ?>
        <?php foreach ($params['users'] as $user): ?>
            <div class="liste-client">
                <div class="liste-client-item"><?= $user["client"];?>  </div>
                <div class="liste-client-item address"><?= $user["address"] .', '.$user["city"].' '.$user["postal"];?>  </div>
                <div class="liste-client-item"><?= $user["contact"];?> </div>
                <div class="liste-client-item"><?= $user["phone"];?> </div>
                <div class="liste-client-item"><?= $user["email"];?> </div>
                <div class="liste-client-item action">
                    <div class="action-edit"> <a href="<?='edit_user?id='.$user["id_user"];?>"><i class="fa-solid fa-pen-to-square"></i></a></div>
                    <div class="action-delete"> <a href="<?='delete_user?id='.$user["id_user"];?>"><i class="fa-solid fa-trash-can"></i></a></div>
                </div>
            </div>
    <?php endforeach; ?>
    <?php else : ?>
        <div class="liste-client-aucun">
            <p>Aucun client trouvé</p>
        </div>
    <?php endif;?>
<?php endif;?>
</div>