
<div class="liste">
    <div class="liste-commande head">
        <div class="liste-commande-item"> Commande </div>
        <div class="liste-commande-item"> Montant </div>
        <div class="liste-commande-item"> Date commande </div>
        <div class="liste-commande-item"> Date livraison </div>
        <div class="liste-commande-item action">
            <div class="action-edit"> Editer </div>
            <div class="action-delete"> Supprimer </div>
        </div>
    </div>


    <?php if($params['commandes']):?>
    <?php if(empty($_SESSION['commandeByDate'])) :?>
        <?php foreach ($params['commandes'] as $commande): ?>
            <div class="liste-commande" >
                <div class="liste-commande-item" ><?=$commande['id_commande'];?></div>
                <div class="liste-commande-item" ><?=($commande['montant']/100) ." €" ;?> </div>
                <div class="liste-commande-item" ><?= date('d/m/y', strtotime($commande['date_commande'])) ;?> </div>
                <div class="liste-commande-item" ><?= date('d/m/y', strtotime($commande['date_livraison'])) ;?> </div>
                <div class="liste-commande-item action">
                    <div class="action-edit" ><a href="<?='commande_details_admin?id='.$commande['id_commande'] ;?>"><i class="fa-solid fa-pen-to-square"></i></a></div>
                    <div class="action-delete"><a href="<?='delete_commande?id='.$commande['id_commande'] ;?>"><i class="fa-solid fa-trash-can"></i></a></div>
                </div>
            </div>
        <?php endforeach; ?>
    <?php else :?>
        <?php foreach ($_SESSION['commandeByDate'] as $commande): ?>
            <div class="liste-commande" >
                <div class="liste-commande-item" ><?=$commande['id_commande'];?></div>
                <div class="liste-commande-item" ><?=($commande['montant']/100) ." €" ;?> </div>
                <div class="liste-commande-item" ><?= date('d/m/y', strtotime($commande['date_commande'])) ;?> </div>
                <div class="liste-commande-item" ><?= date('d/m/y', strtotime($commande['date_livraison'])) ;?> </div>
                <div class="liste-commande-item action">
                    <div class="action-edit" ><a href="<?='commande_details_admin?id='.$commande['id_commande'] ;?>"><i class="fa-solid fa-pen-to-square"></i></a></div>
                    <div class="action-delete"><a href="<?='delete_commande?id='.$commande['id_commande'] ;?>"><i class="fa-solid fa-trash-can"></i></a></div>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif;?>
<!--</div>-->
<?php else:?>
    <div class="emptyCommande">
        <p>Aucune commande</p>
    </div>



<?php endif;?>

</div>


