<?php if(isset($_SESSION['articleSearch'])) :?>
    <?php if(empty($_SESSION['articleSearch'])) :?>
        <div class="container-fluide">
        <h3 class="text-center text-red m-0 p-2">Légumes</h3>
        <div class="container p-0 bg-light">
            <div class="row bg-first-lightbackground-color pt-2 pb-2 m-0">

                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Article</p> </div>
                <div class="col-2 d-md-none text-center font-weight-bold"> <p>Art</p> </div>
                <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Origine</p> </div>
                <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Ori</p> </div>
                <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prix/Unitée</p> </div>
                <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prx/Ute</p> </div>
                <div class="col-2 d-none d-sm-block text-center font-weight-bold"> <p>Poids</p> </div>
                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Statut</p> </div>
                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p class="d-md-none">Détails</p> </div>
                <div class="col-2 d-md-none text-center font-weight-bold"> <p class="d-md-none">Dts</p> </div>
            </div>
        </div>
        <div class="row line-out pt-2 pb-2 m-0">
            <div class="col-12 mt-3 mb-3 text-center "> Aucun article trouvé</div>
        </div>
    </div>

    <?php else : ?>
        <div class="container p-0 bg-light">
            <div class="row bg-first-lightbackground-color pt-2 pb-2 m-0">
                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Article</p> </div>
                <div class="col-2 d-md-none text-center font-weight-bold"> <p>Art</p> </div>
                <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Origine</p> </div>
                <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Ori</p> </div>
                <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prix/Unitée</p> </div>
                <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prx/Ute</p> </div>
                <div class="col-2 d-none d-sm-block text-center font-weight-bold"> <p>Poids</p> </div>
                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Statut</p> </div>
                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p class="d-md-none">Détails</p> </div>
                <div class="col-2 d-md-none text-center font-weight-bold"> <p class="d-md-none">Dts</p> </div>
            </div>

            <?php foreach ($_SESSION['articleSearch'] as $article): ?>

                <div class="row line-out pt-2 pb-2 m-0">
                    <div class="col-2 text-center"><?= $article["article"];?> </div>
                    <div class="col-4 col-sm-3 col-md-2 text-center"><?= $article["origine"];?> </div>
                    <div class="col-4 col-sm-3 col-md-2 text-center"><?= ($article["prix"]/100)." €/".$article['unite'];?>  </div>
                    <div class="col-2 d-none d-sm-block text-center"><?= $article["poids"] ." " .$article['unite'];?> </div>
                    <div class="col-2 d-none d-md-block text-center"><?= $article["statutArticle"];?> </div>
                    <div class="col-1 d-none d-md-block text-center"> <a href="<?='edit_article?id='.$article["id_article"];?>"><i class="fa-solid fa-pen-to-square"></i></a></div>
                    <div class="col-1 d-none d-md-block text-center"> <a href="<?='delete_article?id='.$article["id_article"];?>"><i class="fa-solid fa-trash-can"></i></a> </div>
                    <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php endif;?>
<?php else : ?>
    <div class="container-fluide">
        <h3 class="text-center text-red m-0 p-2">Légumes</h3>
        <div class="container p-0 bg-light">
            <div class="row bg-first-lightbackground-color pt-2 pb-2 m-0">

                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Article</p> </div>
                <div class="col-2 d-md-none text-center font-weight-bold"> <p>Art</p> </div>
                <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Origine</p> </div>
                <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Ori</p> </div>
                <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prix/Unitée</p> </div>
                <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prx/Ute</p> </div>
                <div class="col-2 d-none d-sm-block text-center font-weight-bold"> <p>Poids</p> </div>
                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Statut</p> </div>
                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p class="d-md-none">Détails</p> </div>
                <div class="col-2 d-md-none text-center font-weight-bold"> <p class="d-md-none">Dts</p> </div>
            </div>
        </div>
        <?php foreach ($params['articles'] as $article): ?>
            <?php if($article['famille']=="Légume" && $article['id_statutArticle']!=3):?>
                <div class="row line-out pt-2 pb-2 m-0">
                    <div class="col-2 text-center"><?= $article["article"];?> </div>
                    <div class="col-4 col-sm-3 col-md-2 text-center "><?= $article["origine"];?> </div>
                    <div class="col-4 col-sm-3 col-md-2 text-center "><?= ($article["prix"]/100)." €/".$article['unite'];?>  </div>
                    <div class="col-2 d-none d-sm-block text-center "><?= $article["poids"] ." " .$article['unite'];?> </div>
                    <div class="col-2 d-none d-md-block text-center "><?= $article["statutArticle"];?> </div>
                    <div class="col-1 d-none d-md-block text-center"> <a href="<?='edit_article?id='.$article["id_article"];?>"><i class="fa-solid fa-pen-to-square"></i></a></div>
                    <div class="col-1 d-none d-md-block text-center"> <a href="<?='delete_article?id='.$article["id_article"];?>"><i class="fa-solid fa-trash-can"></i></a> </div>
                    <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>
                </div>
            <?php endif ;?>
        <?php endforeach; ?>
    </div>

    <div class="container-fluide ">
        <h3 class="text-center text-red m-0 p-2 " >Fruits</h3>
        <div class="container p-0 bg-light">
            <div class="row bg-first-lightbackground-color pt-2 pb-2 m-0">
                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Article</p> </div>
                <div class="col-2 d-md-none text-center font-weight-bold"> <p>Art</p> </div>
                <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Origine</p> </div>
                <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Ori</p> </div>
                <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prix/Unitée</p> </div>
                <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prx/Ute</p> </div>
                <div class="col-2 d-none d-sm-block text-center font-weight-bold"> <p>Poids</p> </div>
                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Statut</p> </div>
                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p class="d-md-none">Détails</p> </div>
                <div class="col-2 d-md-none text-center font-weight-bold"> <p class="d-md-none">Dts</p> </div>
            </div>
        </div>
        <?php foreach ($params['articles'] as $article): ?>
            <?php if($article['famille']=="Fruit" && $article['id_statutArticle']!=3):?>
                <div class="row line-out pt-2 pb-2 m-0">
                    <div class="col-2 text-center"><?= $article["article"];?> </div>
                    <div class="col-4 col-sm-3 col-md-2 text-center"><?= $article["origine"];?> </div>
                    <div class="col-4 col-sm-3 col-md-2 text-center"><?= ($article["prix"]/100)." €/".$article['unite'];?>  </div>
                    <div class="col-2 d-none d-sm-block text-center"><?= $article["poids"] ." " .$article['unite'];?> </div>
                    <div class="col-2 d-none d-md-block text-center"><?= $article["statutArticle"];?> </div>
                    <div class="col-1 d-none d-md-block text-center"> <a href="<?='edit_article?id='.$article["id_article"];?>"><i class="fa-solid fa-pen-to-square"></i></a></div>
                    <div class="col-1 d-none d-md-block text-center"> <a href="<?='delete_article?id='.$article["id_article"];?>"><i class="fa-solid fa-trash-can"></i></a> </div>
                    <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>
                </div>
            <?php endif ;?>
        <?php endforeach; ?>
    </div>
<?php endif;?>











<!---->
<!---->
<?php //if(empty($_SESSION['articleSearch'])) :?>
<!--    <div class="container-fluide">-->
<!--        <h3 class="text-center text-red m-0 p-2">Légumes</h3>-->
<!--        <div class="container p-0 bg-light">-->
<!--            <div class="row bg-first-lightbackground-color pt-2 pb-2 m-0">-->
<!---->
<!--                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Article</p> </div>-->
<!--                <div class="col-2 d-md-none text-center font-weight-bold"> <p>Art</p> </div>-->
<!--                <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Origine</p> </div>-->
<!--                <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Ori</p> </div>-->
<!--                <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prix/Unitée</p> </div>-->
<!--                <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prx/Ute</p> </div>-->
<!--                <div class="col-2 d-none d-sm-block text-center font-weight-bold"> <p>Poids</p> </div>-->
<!--                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Statut</p> </div>-->
<!--                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p class="d-md-none">Détails</p> </div>-->
<!--                <div class="col-2 d-md-none text-center font-weight-bold"> <p class="d-md-none">Dts</p> </div>-->
<!--            </div>-->
<!--        </div>-->
<!--        --><?php //foreach ($params['articles'] as $article): ?>
<!--            --><?php //if($article['famille']=="Légume" && $article['id_statutArticle']!=3):?>
<!--                <div class="row line-out pt-2 pb-2 m-0">-->
<!--                    <div class="col-2 text-center">--><?//= $article["article"];?><!-- </div>-->
<!--                    <div class="col-4 col-sm-3 col-md-2 text-center ">--><?//= $article["origine"];?><!-- </div>-->
<!--                    <div class="col-4 col-sm-3 col-md-2 text-center ">--><?//= ($article["prix"]/100)." €/".$article['unite'];?><!--  </div>-->
<!--                    <div class="col-2 d-none d-sm-block text-center ">--><?//= $article["poids"] ." " .$article['unite'];?><!-- </div>-->
<!--                    <div class="col-2 d-none d-md-block text-center ">--><?//= $article["statutArticle"];?><!-- </div>-->
<!--                    <div class="col-1 d-none d-md-block text-center"> <a href="--><?//='edit_article?id='.$article["id_article"];?><!--"><i class="fa-solid fa-pen-to-square"></i></a></div>-->
<!--                    <div class="col-1 d-none d-md-block text-center"> <a href="--><?//='delete_article?id='.$article["id_article"];?><!--"><i class="fa-solid fa-trash-can"></i></a> </div>-->
<!--                    <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>-->
<!--                </div>-->
<!--            --><?php //endif ;?>
<!--        --><?php //endforeach; ?>
<!--    </div>-->
<!---->
<!--    <div class="container-fluide ">-->
<!--        <h3 class="text-center text-red m-0 p-2 " >Fruits</h3>-->
<!--        <div class="container p-0 bg-light">-->
<!--            <div class="row bg-first-lightbackground-color pt-2 pb-2 m-0">-->
<!--                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Article</p> </div>-->
<!--                <div class="col-2 d-md-none text-center font-weight-bold"> <p>Art</p> </div>-->
<!--                <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Origine</p> </div>-->
<!--                <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Ori</p> </div>-->
<!--                <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prix/Unitée</p> </div>-->
<!--                <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prx/Ute</p> </div>-->
<!--                <div class="col-2 d-none d-sm-block text-center font-weight-bold"> <p>Poids</p> </div>-->
<!--                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Statut</p> </div>-->
<!--                <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p class="d-md-none">Détails</p> </div>-->
<!--                <div class="col-2 d-md-none text-center font-weight-bold"> <p class="d-md-none">Dts</p> </div>-->
<!--            </div>-->
<!--        </div>-->
<!--        --><?php //foreach ($params['articles'] as $article): ?>
<!--            --><?php //if($article['famille']=="Fruit" && $article['id_statutArticle']!=3):?>
<!--                <div class="row line-out pt-2 pb-2 m-0">-->
<!--                    <div class="col-2 text-center">--><?//= $article["article"];?><!-- </div>-->
<!--                    <div class="col-4 col-sm-3 col-md-2 text-center">--><?//= $article["origine"];?><!-- </div>-->
<!--                    <div class="col-4 col-sm-3 col-md-2 text-center">--><?//= ($article["prix"]/100)." €/".$article['unite'];?><!--  </div>-->
<!--                    <div class="col-2 d-none d-sm-block text-center">--><?//= $article["poids"] ." " .$article['unite'];?><!-- </div>-->
<!--                    <div class="col-2 d-none d-md-block text-center">--><?//= $article["statutArticle"];?><!-- </div>-->
<!--                    <div class="col-1 d-none d-md-block text-center"> <a href="--><?//='edit_article?id='.$article["id_article"];?><!--"><i class="fa-solid fa-pen-to-square"></i></a></div>-->
<!--                    <div class="col-1 d-none d-md-block text-center"> <a href="--><?//='delete_article?id='.$article["id_article"];?><!--"><i class="fa-solid fa-trash-can"></i></a> </div>-->
<!--                    <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>-->
<!--                </div>-->
<!--            --><?php //endif ;?>
<!--        --><?php //endforeach; ?>
<!--    </div>-->
<!---->
<?php //else : ?>
<!--    <div class="container p-0 bg-light">-->
<!--        <div class="row bg-first-lightbackground-color pt-2 pb-2 m-0">-->
<!--            <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Article</p> </div>-->
<!--            <div class="col-2 d-md-none text-center font-weight-bold"> <p>Art</p> </div>-->
<!--            <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Origine</p> </div>-->
<!--            <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Ori</p> </div>-->
<!--            <div class="col-4 d-none d-md-block col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prix/Unitée</p> </div>-->
<!--            <div class="col-4 d-md-none col-sm-3 col-md-2 text-center font-weight-bold"> <p>Prx/Ute</p> </div>-->
<!--            <div class="col-2 d-none d-sm-block text-center font-weight-bold"> <p>Poids</p> </div>-->
<!--            <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p>Statut</p> </div>-->
<!--            <div class="col-2 d-none d-md-block text-center font-weight-bold"> <p class="d-md-none">Détails</p> </div>-->
<!--            <div class="col-2 d-md-none text-center font-weight-bold"> <p class="d-md-none">Dts</p> </div>-->
<!--        </div>-->
<!---->
<!--        --><?php //foreach ($_SESSION['articleSearch'] as $article): ?>
<!---->
<!--            <div class="row line-out pt-2 pb-2 m-0">-->
<!--                <div class="col-2 text-center">--><?//= $article["article"];?><!-- </div>-->
<!--                <div class="col-4 col-sm-3 col-md-2 text-center">--><?//= $article["origine"];?><!-- </div>-->
<!--                <div class="col-4 col-sm-3 col-md-2 text-center">--><?//= ($article["prix"]/100)." €/".$article['unite'];?><!--  </div>-->
<!--                <div class="col-2 d-none d-sm-block text-center">--><?//= $article["poids"] ." " .$article['unite'];?><!-- </div>-->
<!--                <div class="col-2 d-none d-md-block text-center">--><?//= $article["statutArticle"];?><!-- </div>-->
<!--                <div class="col-1 d-none d-md-block text-center"> <a href="--><?//='edit_article?id='.$article["id_article"];?><!--"><i class="fa-solid fa-pen-to-square"></i></a></div>-->
<!--                <div class="col-1 d-none d-md-block text-center"> <a href="--><?//='delete_article?id='.$article["id_article"];?><!--"><i class="fa-solid fa-trash-can"></i></a> </div>-->
<!--                <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>-->
<!--            </div>-->
<!--        --><?php //endforeach; ?>
<!--    </div>-->
<?php //endif;?>