<main class="mt-3">
    <div class="container border-custom bg-second-background-color">
        <div class="row">
            <div class="col-12 p-0">
                <h3 class="text-center text-red mt-2 mb-3"> Message de : <?=$params['message']['email'];?> </h3>
                <div class="container">
                    <div class="row pt-3 bg-second-lightbackground-color text-center form-details">
                        <div class="col-12 col-md-6 mb-3 mb-md-4 ">
                            <label>Client  : </label>
                            <p><?=$params['message']['client'];?></p>
                        </div>
                        <div class="col-12 col-md-6 mb-3 mb-md-4 ">
                            <label>Email : </label>
                            <p><?=$params['message']['email'];?></p>
                        </div>
                        <div class="col-12 col-md-6 mb-3 mb-md-4 ">
                            <label>Date : </label>
                            <p><?=$params['message']['date'];?></p>
                        </div>
                    </div>
                </div>
                <div class="container">
                    <div class="row pt-3 bg-second-lightbackground-color">
                        <div class="col-12 ">
                            <div>
                                <label class="font-weight-bold">Sujet : </label>
                                <?=$params['message']['subject'];?>
                            </div>
                            <div>
                                <label class="font-weight-bold">Message :</label>
                                <?=$params['message']['text'];?>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="container mt-3 border-custom bg-second-background-color">
        <div class="row">
            <div class="col-12">
                <form method="POST" action="<?='message_details?id='.$params['message']["id_message"];?>">
                    <div class="form-group">
                        <label  class="font-weight-bold">Répondre</label>
                        <textarea class="form-control" name="reponse" rows="3"></textarea>
                    </div>
                    <div class=" text-center">
                        <button type="submit" class="btn btn-default bg-alt-background-color text-darkgreen" >
                            Valider
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

</main>