<div class="container">
    <div class="row">
        <div class="col-12 border-custom bg-second-background-color pt-2 pb-3 pl-0 pr-0">
            <h2 class="text-center text-red"> Listes des messages</h2>
            <div class="container p-0 ">
                <div class="row pt-2 pb-2 m-0 bg-first-lightbackground-color font-weight-bold">
                    <div class="col-3 d-none d-md-block col-lg-2 text-center">Client</div>
                    <div class="col-5 col-md-3 text-center">Email </div>
                    <div class="col-5 col-md-4 col-lg-2 text-center"> Sujet </div>
                    <div class="col-3 d-none d-lg-block text-center"> Message</div>
                    <div class="col-2 d-md-none text-center"></div>
                </div>
            </div>

                <div class="container-fluide bg-light ">
                    <?php foreach ($params['messages'] as $message): ?>
                        <div class="row line-out pt-2 pb-2 m-0">
                            <div class="col-3 d-none d-md-block col-lg-2 text-center"><?= $message["client"];?> </div>
                            <div class="col-5 col-md-3 text-center"><?= $message["email"];?> </div>
                            <div class="col-5 col-md-4 col-lg-2 text-center"><?= $message["subject"];?>  </div>
                            <div class="col-3 d-none d-lg-block text-center"><?= substr($message["text"], 0, 20).' ...';?> </div>
<!--                            <div class="col-2 d-none d-md-block text-center">--><?//= $message["status"];?><!-- </div>-->
                            <div class="col-1 d-none d-md-block text-center"> <a href="<?='message_details?id='.$message["id_message"];?>"><i class="fa-solid fa-pen-to-square"></i></a></div>
                            <div class="col-1 d-none d-md-block text-center"> <a href="<?='delete_message?id='.$message["id_message"];?>"><i class="fa-solid fa-trash-can"></i></a> </div>
                            <div class="col-2 d-md-none text-center"> <a href="<?='message_details?id='.$message["id_message"];?>"><i class="fa-solid fa-eye"></i></a> </div>
                        </div>
                    <?php endforeach; ?>
                </div>
        </div>
    </div>
</div>