

<?php if(isset($params['flash'])) : ?>
    <div class="alert alert-danger" role="alert">
        <?= $params['flash'] ;?>
    </div>
<?php endif;?>
<h3 class="headerTitle"> Listes clients</h3>

<form method="POST" action ="users_admin" class="formClient" id="form-commande" role="search">
    <div class="headerClient">
        <div class="headerClient-search">
                <?php if(empty($_SESSION['userSearch'])) :?>
                    <input type="search" class="form-control" name="userSearch" id="userSearch" placeholder="Rechercher un client">

                <?php else : ?>
                    <input type="search" class="form-control" name="userSearch" id="userSearch" value="<?= $params['userSearch'];?>">
                <?php endif;?>
        </div>
        <div class="headerClient-statut">
            <?php if($params['users']):?>
                <select class="form-control " name="userstatut" id="userStatut">
                    <option value="<?= $params['users'][0]['id_statut'] ?>"><?= $params['users'][0]['statut'] ?></option>
                    <?php foreach ($params['statut'] as $statut): ?>
                        <?php if($statut['id_statut'] != $params['users'][0]['id_statut']): ?>
                            <option value="<?=$statut['id_statut'];?>"><?=$statut['statut'];?></option>
                        <?php endif ;?>
                    <?php endforeach; ?>
                </select>
            <?php else : ?>
                <select class="form-control " name="userstatut" id="userStatut">
                    <option value="<?= $params['statutUser'] ?>"><?= $params['namestatut']['statut'] ?></option>
                    <?php foreach ($params['statut'] as $statut): ?>
                        <?php if($statut['id_statut'] != $params['statutUser']): ?>
                            <option value="<?=$statut['id_statut'];?>"><?=$statut['statut'];?></option>
                        <?php endif ;?>
                    <?php endforeach; ?>
                </select>
            <?php endif; ?>
        </div>
    </div>
</form>

<div class="templateListe">
    <?php $this->render($this->file, 'liste_users_admin', '', $params);?>
</div>

<script src="http://localhost/TerrAnanas/public/js/users_admin.js" defer></script>