

    <section class="headContent">
<!--        <img class="headContent-picture" src="http://localhost/TerrAnanas/public/images/123.jpg" alt="#">-->
        <div class="headContent-box">
            <h1>Bienvenue chez TerrAnanas</h1>
            <span>Fournisseur de fruits et légumes 100% BIO</span>
        </div>

    </section>

        <section class="presentation">

            <div class="presentation-texte">
                <h3>Qui sommes-nous ?</h3>
                <p>TerrAnanas est une société de producteurs bio basée en Provence-Alpes-Côte d'Azur distribuant des fruits et légumes biologiques frais…</p>
                <p>Notre vocation est de vous proposer une offre large de fruits et légumes biologiques riches en goûts. Variétés gustatives, variétés oubliées, variétés anciennes... il existe en France et dans le monde une palette de textures et saveurs infinie et notre mission est de sélectionner et vous proposer les meilleurs d'entre elles.</p>
                <p>Pour parvenir à ce resultat, nous effectuons chaque année de nombreux essais, avec des nouvelles variétés, parfois oubliées et avec pour seul objectif, vous proposer des fruits et légumes bio riches en goût.</p>
            </div>
        </section>

        <section class="valeurs">
            <article class="valeurs-article">
                <div class="valeurs-article-image">
                    <img src="http://localhost/ProjetCommande/public/images/producteur.png">
                </div>

                <div class="valeurs-article-texte">
                    <h3>Des partenariats durables et équitables avec nos producteurs</h3>
                    <p>L'agriculture biologique est avant tout une histoire d'hommes passionnés ayant des valeurs communes pour développer la filière dans son ensemble. Un travail collaboratif et de proximité nous à permis, au fil des années de veiller à la viabilité économique des exploitations mais surtout de structurer la production et améliorer la qualité des produits. Nous avons su construire un partenariat unique avec les producteurs des différentes régions. Ce dernier passant par la planification de cultures, la contractualisation des volumes, le conseil agronomique, l'assistance technique, l'accompagnement à la conversion </p>
                    <p>La relation gagnant-gagnant qui en découle encourage les producteurs à cultiver pour nous des variétés de fruits et légumes bio aux qualités nutritionnelles et gustatives éprouvées.</p>
                </div>
            </article>
            <article class="valeurs-article">
                <div class="valeurs-article-image">
                    <img src="http://localhost/ProjetCommande/public/images/champ.png">
                </div>

                <div class="valeurs-article-texte">
                    <h3>Cultivateur de filière 100% BIO</h3>
                    <p>Chez TerrAnanas, nous accompagnons tous les producteurs bio. Animés par la volonté d'améliorer au fil des saisons la qualité et le goût des fruits et légumes biologiques des bassins où nous intervenons (Provence, Bretagne, Roussillon ...), nous accompagnons nos partenaires au quotidien. Nous les orientons sur des variétés adaptées à leur terroirs mais aussi sur vos attentes en terme de goûts.</p>
                    <p> Parce qu'on cultive des filières 100% bio, on récolte forcément des fruits et légumes riches en goûts...</p>
                </div>
            </article>
        </section>

        <section class="mission">
            <article class="mission-article">
                <div class="mission-article-presentation">
                    <h3>Notre mission c’est quoi ?</h3>
                    <p> Tout simplement de commercialiser toute la production de fruits et legumes biologiques de ses exploitations associées et partenaires et de contribuer à leur développement et leur pérennisation à la fois technique et économique.</p>
                </div>
            </article>
        </section>

        <section class="client">
            <article class="client-article">
                <div class="client-article-presentation">
                    <h3>Qui sont nos clients ?</h3>
                    <p class="client-presentation-texte"> Des grossistes, des magasins spécialisés bios, des supermarchés, des sociétés de restauration, des cuisines centrales, des producteurs.</p>
                    <p>Nos fruits et légumes biologiques , sont présentes dans la plupart des magasins spécialisés bio en France. Vous pouvez les retrouver dans de nombreux magasins bio indépendants ainsi que dans les enseignes suivantes :</p>
                    <div class="listeClient">
                        <div class="listeClient-image">
                            <img src="http://localhost/TerrAnanas/public/images/eau_vive.jpg" alt="image_eauvive">
                        </div>
                        <div class="listeClient-image">
                            <img src="http://localhost/TerrAnanas/public/images/biomonde.jpg" alt="image_biomonde">
                        </div>
                        <div class="listeClient-image">
                            <img src="http://localhost/TerrAnanas/public/images/naturalia.png" alt="image_naturalia">
                        </div>
                        <div class="listeClient-image">
                            <img src="http://localhost/TerrAnanas/public/images/bionco.jpg" alt="image_bionco">
                        </div>
                    </div>
                </div>
            </article>
        </section>


        <section class="inscription">
            <div class="inscription-client">
                <h3> Devenir client</h3>
                <p >Vous allez ouvrir un magasin ? Vous êtes restaurateur ?</p>
                <p >Votre structure existe déjà et vous cherchez un fournisseur de fruits et légumes bio fiable et partageant vos valeurs ?</p>
                <p >Que vous soyez acteur de la distribution spécialisée bio ou bien généraliste, que vous soyez en groupe ou indépendant, restaurateur traditionnel ou en collectivité, nos schémas logistiques et commerciaux ont été pensé afin de répondre à toutes les configurations.</p>
                <p>Pour en savoir plus, n'hésitez pas à nous contacter.</p>
                <div class="inscription-client-lien">
                    <a class="inscription-client-lien-link" href="contact" >Nous contacter</a>
                </div>
            </div>
        </section>



