<main>
    <section class="bannière-contact">
        <div class="bannière-contact-text">
            <h4 class="bannière-contact-text-titre">
                Formulaire d'inscription
            </h4>
            <span class="bannière-contact-text-contenu">
                Merci de bien vouloir remplir le formulaire, votre demande sera pris en compte par notre service.
            </span>
        </div>
        <div class="bannière-contact-img">
            <img src="http://localhost/ProjetCommande/public/images/enveloppe.png" alt="logo enveloppe">
        </div>
    </section>

    <section class="section-formulaire">
        <form method="POST" action="<?='inscription';?>">
            <div class="form-group">
                <label for="client">Nom de la société</label>
                <input type="text" class="form-control" id="client" name="client" value="<?=$params['client'];?>">
                <?php if (isset($params['error']['client'])): ?>
                    <p class="error"><?=htmlspecialchars($params['error']['client']);?></p>
                <?php endif; ?>
            </div>
            <div class="form-group">
                <label for="address">Adresse</label>
                <input type="text" class="form-control" id="address" name="address" value="<?=$params['address'];?>">
                <?php if (isset($params['error']['address'])): ?>
                    <p class="error"><?=htmlspecialchars($params['error']['address']);?></p>
                <?php endif; ?>
            </div>
            <div class="form-group">
                <label for="city">Ville</label>
                <input type="text" class="form-control" id="city" name="city" value="<?=$params['city'];?>">
                <?php if (isset($params['error']['city'])): ?>
                    <p class="error"><?=htmlspecialchars($params['error']['city']);?></p>
                <?php endif; ?>
            </div>
            <div class="form-group">
                <label for="postal">Code postal</label>
                <input type="text" class="form-control" id="postal" name="postal" value="<?=$params['postal'];?>">
                <?php if (isset($params['error']['postal'])): ?>
                    <p class="error"><?=htmlspecialchars($params['error']['postal']);?></p>
                <?php endif; ?>
            </div>
            <div class="form-group">
                <label for="contact">Personne à contacter</label>
                <input type="text" class="form-control" id="quantité" name="contact" value="<?=$params['contact'];?>">
                <?php if (isset($params['error']['contact'])): ?>
                    <p class="error"><?=htmlspecialchars($params['error']['contact']);?></p>
                <?php endif; ?>
            </div>
            <div class="form-group">
                <label for="phone">Téléphone</label>
                <input type="text" class="form-control" id="phone" name="phone" value="<?=$params['phone'];?>">
                <?php if (isset($params['error']['phone'])): ?>
                    <p class="error"><?=htmlspecialchars($params['error']['phone']);?></p>
                <?php endif; ?>
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input type="text" class="form-control" id="email" name="email" value="<?=$params['email'];?>">
                <?php if (isset($params['error']['email'])): ?>
                    <p class="error"><?=htmlspecialchars($params['error']['email']);?></p>
                <?php endif; ?>
            </div>
            <div class="form-group">
                <label for="password">Mot de passe</label>
                <input type="password" class="form-control" id="password" name="password">
                <?php if (isset($params['error']['password'])): ?>
                    <p class="error"><?=htmlspecialchars($params['error']['password']);?></p>
                <?php endif; ?>
            </div>
            <div class="form-group">
                <label for="confirmPassword">Mot de passe à confirmer</label>
                <input type="password" class="form-control" id="confirmPassword" name="confirmPassword">
                <?php if (isset($params['error']['confirmPassword'])): ?>
                    <p class="error"><?=htmlspecialchars($params['error']['confirmPassword']);?></p>
                <?php endif; ?>
            </div>

            <button type="submit" class="btn btn-primary">Envoyer la demande</button>
        </form>
    </section>
</main>

