<main>
    <?php displayFlashMessages() ;?>
    <section class="bannière-contact">
        <div class="bannière-contact-text">
            <h4 class="bannière-contact-text-titre">
                Mon Espace pro
            </h4>
            <span class="bannière-contact-text-contenu">
                Vous êtes déja client TerrAnanas, accédez à votre espace dédié.
            </span>
        </div>
        <div class="bannière-contact-img">
            <img src="http://localhost/ProjetCommande/public/images/enveloppe.png" alt="logo enveloppe">
        </div>
    </section>

    <section class="section-formulaire">
        <form action="login" method="POST" class="">
            <div class="form-group">
                <label for="">Email</label>
                <input type="email" class="form-control" name="email">
            </div>
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Mot de passe </label>
                <input type="password" class="form-control" name="password">
            </div>
            <input type="submit" value="Connexion" class="button-submit">
        </form>
    </section>

    <section class="section-insciption">
        <h2 class="section-insciption-titre">Vous n'êtes pas client et souhaitez vous inscrire ?</h2>
        <p class="section-insciption-text">Remplissez le formulaire en suivant ce lien : </p>
        <div class="section-insciption-lien">
            <a href="signup" >Inscription</a>
        </div>
    </section>
</main>
