<main>
    <section class="bannière-contact">
        <div class="bannière-contact-text">
            <h4 class="bannière-contact-text-titre">
                Calendrier des fruits et légumes de saison en France Métropolitaine
            </h4>
            <span class="bannière-contact-text-contenu">
                Parce que manger des produits de qualité rime avec respect de la saisonnalité, TerrAnanas a élaboré un calendrier de saisonnalité pour ses fruits et légumes bio.
            </span>
        </div>
    </section>

    <section class="calendrier">
        <nav class="calendrier-list">
            <a href="#janvier" class="" data-index="janvier">Janvier</a>
            <a href="#fevrier" class="" data-index="fevrier">Février</a>
            <a href="#mars" class="" data-index="mars">Mars</a>
            <a href="#avril" class="" data-index="avril">Avril</a>
            <a href="#mai" class="" data-index="mai">Mai</a>
            <a href="#juin" class="" data-index="juin">Juin</a>
            <a href="#juillet" class="" data-index="juillet">Juillet</a>
            <a href="#aout" class="" data-index="aout">Aout</a>
            <a href="#septembre" class="" data-index="septembre">Septembre</a>
            <a href="#octobre" class="" data-index="octobre">Octobre</a>
            <a href="#novembre" class="" data-index="novembre">Novembre</a>
            <a href="#decembre" class="" data-index="decembre">Décembre</a>
        </nav>
    </section>
    <section class="resultat" data-month="janvier">

        <div>
            <h3>Fruits</h3>
            <ul>
                <li>Clémentine </li>
                <li>Kiwi</li>
            </ul>
        </div>
        <div>
            <h3>Légumes</h3>
            <ul>
                <li>Carotte </li>
                <li>Chou </li>
            </ul>
        </div>
    </section>
    <section class="resultat hide" data-month="fevrier">

        <div>
            <h3>Fruits</h3>
            <ul>
                <li>Pamplemousse </li>
                <li>Poire</li>
            </ul>
        </div>
        <div>
            <h3>Légumes</h3>
            <ul>
                <li>Endive </li>
                <li>Navet </li>
            </ul>
        </div>
    </section>
    <section class="resultat hide" data-month="mars">

        <div>
            <h3>Fruits</h3>
            <ul>
                <li>Citron</li>
                <li>Orange</li>

            </ul>
        </div>
        <div>
            <h3>Légumes</h3>
            <ul>
                <li>Épinard</li>
                <li>Panais </li>

            </ul>
        </div>
    </section>
    <section class="resultat hide" data-month="avril">

        <div>
            <h3>Fruits</h3>
            <ul>
                <li>Citron</li>
                <li>Orange</li>
            </ul>
        </div>
        <div>
            <h3>Légumes</h3>
            <ul>
                <li>Épinard</li>
                <li>Panais </li>
            </ul>
        </div>
    </section>
    <section class="resultat hide" data-month="mai">

        <div>
            <h3>Fruits</h3>
            <ul>
                <li>Fraise </li>
                <li>Cerise </li>
            </ul>
        </div>
        <div>
            <h3>Légumes</h3>
            <ul>
                <li>Asperge</li>
                <li>Petit pois</li>
            </ul>
        </div>
    </section>
    <section class="resultat hide" data-month="juin">

        <div>
            <h3>Fruits</h3>
            <ul>
                <li>Melon </li>
                <li>Pastèque</li>
            </ul>
        </div>
        <div>
            <h3>Légumes</h3>
            <ul>
                <li>Artichaut </li>
                <li>Blette </li>
            </ul>
        </div>
    </section>
    <section class="resultat hide" data-month="juillet">

        <div>
            <h3>Fruits</h3>
            <ul>
                <li>Melon </li>
                <li>Pastèque</li>
            </ul>
        </div>
        <div>
            <h3>Légumes</h3>
            <ul>
                <li>Chou romanesco </li>
                <li>Fenouil</li>
            </ul>
        </div>
    </section>
    <section class="resultat hide" data-month="aout">

        <div>
            <h3>Fruits</h3>
            <ul>
                <li>Melon </li>
                <li>Pastèque</li>
            </ul>
        </div>
        <div>
            <h3>Légumes</h3>
            <ul>
                <li>Chou romanesco </li>
                <li>Fenouil</li>
            </ul>
        </div>
    </section>
    <section class="resultat hide" data-month="septembre">

        <div>
            <h3>Fruits</h3>
            <ul>
                <li>Nectarine</li>
                <li>Pêche </li>
            </ul>
        </div>
        <div>
            <h3>Légumes</h3>
            <ul>
                <li>Chou romanesco </li>
                <li>Fenouil</li>
            </ul>
        </div>
    </section>
    <section class="resultat hide" data-month="octobre">

        <div>
            <h3>Fruits</h3>
            <ul>
                <li>Nectarine</li>
                <li>Pêche </li>
            </ul>
        </div>
        <div>
            <h3>Légumes</h3>
            <ul>
                <li>Chou romanesco </li>
                <li>Fenouil</li>
            </ul>
        </div>
    </section>
    <section class="resultat hide" data-month="novembre">

        <div>
            <h3>Fruits</h3>
            <ul>
                <li>Kaki </li>
                <li>Pomme </li>
            </ul>
        </div>
        <div>
            <h3>Légumes</h3>
            <ul>
                <li>Chou romanesco </li>
                <li>Fenouil</li>
            </ul>
        </div>
    </section>
    <section class="resultat hide" data-month="decembre">
        <div>
            <h3>Fruits</h3>
            <ul>
                <li>Kaki </li>
                <li>Pomme </li>
            </ul>
        </div>
        <div>
            <h3>Légumes</h3>
            <ul>
                <li>Chou romanesco </li>
                <li>Fenouil</li>
            </ul>
        </div>
    </section>
</main>
<script src="http://localhost/ProjetCommande/public/js/calendrier.js"></script>