
<section class="calendrier">
    <div>
        <input type="text" id="search" placeholder="Recherche">
<!--        <button id="toast">Rechercher</button>-->
    </div>
    <div class="listeMonth">
        <button class="month" data-month="1">Janvier</button>
        <button class="month" data-month="2">Février</button>
        <button class="month" data-month="3">Mars</button>
        <button class="month" data-month="4">Avril</button>
        <button class="month" data-month="5">Mai</button>
        <button class="month" data-month="6">Juin</button>
        <button class="month" data-month="7">Juillet</button>
        <button class="month" data-month="8">Août</button>
        <button class="month" data-month="9">Septembre</button>
        <button class="month" data-month="10">Octobre</button>
        <button class="month" data-month="11">Novembre</button>
        <button class="month" data-month="12">Décembre</button>
    </div>
    <div class="reset">
        <button class="buttonReset">Reset</button>
    </div>
    <div id="result">

    </div>
</section>

<script type="text/javascript" src="http://localhost/TerrAnanas/public/js/calendrier.js" defer></script>
