<section class="hearderCalendrier">
    <h3 class="hearderCalendrier-texte">Retrouver notre calendrier des fruits et légumes !</h3>
</section>


<section class="calendrier">
    <div class="filtre">
        <input class="filtre-search"type="text" id="search" placeholder="Recherche">
        <button class="filtre-reset">Reset</button>
<!--        <div class="filtre-toggle">-->
<!--            <i class="fa-solid fa-eye"></i>-->
<!--            <i class="fa-solid fa-eye-slash hiding"></i>-->
<!--        </div>-->

    </div>
    <div class="listeMonth">
        <button class="month" data-month="1">Janvier</button>
        <button class="month" data-month="2">Février</button>
        <button class="month" data-month="3">Mars</button>
        <button class="month" data-month="4">Avril</button>
        <button class="month" data-month="5">Mai</button>
        <button class="month" data-month="6">Juin</button>
        <button class="month" data-month="7">Juillet</button>
        <button class="month" data-month="8">Août</button>
        <button class="month" data-month="9">Septembre</button>
        <button class="month" data-month="10">Octobre</button>
        <button class="month" data-month="11">Novembre</button>
        <button class="month" data-month="12">Décembre</button>
    </div>

    <div id="result">

    </div>
</section>

<script type="text/javascript" src="http://localhost/TerrAnanas/public/js/calendrier.js" defer></script>
