<main>
    <div class="container p-0 ">
        <div class="row">
            <div class="col-12 p-0">
                <div class="container mt-3 mb-3">
                    <div class="row">
                        <div class="col-9">
                            <form method="GET" action ="articles_client" class="navbar-form navbar-right" role="search">
                                <div class="input-group">
                                    <?php if(empty($_SESSION['articleSearch'])) :?>
                                        <input type="search" class="form-control" name="articleSearch" placeholder="Rechercher un article">

                                    <?php else : ?>
                                        <input type="search" class="form-control" name="articleSearch" value="<?= $articleSearch;?>">
                                    <?php endif;?>

                                    <span class="input-group-btn">
                                <button type="submit" class="btn bg-custom-red" >
                                    Recherche
                                <span class="glyphicon glyphicon-search"></span>
                                </button>
                                </span>
                                </div>
                            </form>
                        </div>

                        <div class="col-3 text-center">
                            <a href="panier"><img src="http://localhost/ProjetCommande/public/images/icon/panier.png" class="img-responsive mw-100" ></i></a>
                        </div>
                    </div>
                </div>

<!--    <div class="container">-->
<!--        <div class="row">-->
<!--            <div class="col-12">-->
<!--                <h2> Listes des articles</h2>-->
<!---->
<!--                <div class="container">-->
<!--                    <div class="row">-->
<!--                        <div class="col-3"> <p>Label</p> </div>-->
<!--                        <div class="col-2"> <p>Origine</p> </div>-->
<!--                        <div class="col-2"> <p>Prix</p> </div>-->
<!--                        <div class="col-3"> <p>Poids</p> </div>-->
<!---->
<!--                    </div>-->
<!--                </div>-->
<!--                --><?php //if(empty($_SESSION['articleSearch'])) :?>
<!---->
<!--                <h3>Légumes</h3>-->
<!--                --><?php //foreach ($articles as $article): ?>
<!--                    --><?php //if($article['label_famille']=="Légume"):;?>
<!--                        --><?php //if($article['label_statusArticle']=="stock"):;?>
<!--                        <form method="post" action="--><?//='article_client';?><!--">-->
<!--                            <div class="container">-->
<!--                                <div class="row">-->
<!--                                    <input type="hidden" name="id_article" value="--><?//=$article['id_article'];?><!--">-->
<!--                                    <input type="hidden" name="label_unite" value="--><?//=$article['label_unite'];?><!--">-->
<!--                                    <input type="hidden" name="label_famille" value="--><?//=$article['label_famille'];?><!--">-->
<!--                                    <div class="col-3"><input type="hidden" name="label_article--><?//=$article['id_article'];?><!--" value="--><?//= $article["label_article"];?><!--">--><?//= $article["label_article"];?><!-- </div>-->
<!--                                    <div class="col-2"><input type="hidden" name="origine--><?//=$article['id_article'];?><!--" value=" --><?//= $article["origine"];?><!--"> --><?//= $article["origine"];?><!--</div>-->
<!--                                    <div class="col-2"><input type="hidden" name="prix--><?//=$article['id_article'];?><!--" value="--><?//= $article["prix"];?><!--">--><?//= $article["prix"]." €/".$article['label_unite'];?><!--  </div>-->
<!--                                    <div class="col-3"><input type="hidden" name="poids--><?//=$article['id_article'];?><!--" value="--><?//= $article["poids"];?><!--">--><?//= $article["poids"] ." " .$article['label_unite'];?><!-- </div>-->
<!--                                    <div class="col-1"><input type="number" id="quantite" name="quantite--><?//=$article['id_article'];?><!--" min="0" value="0"></div>-->
<!--                                    <div class="col-1"><button type="submit" class="btn btn-primary">Ajouter</button></div>-->
<!---->
<!--                                </div>-->
<!--                            </div>-->
<!--                        </form>-->
<!--                        --><?php //endif ;?>
<!--                    --><?php //endif ;?>
<!--                --><?php //endforeach; ?>
<!---->
<!---->
<!--                    <h3>Fruits</h3>-->
<!--                    --><?php //foreach ($articles as $article): ?>
<!--                        --><?php //if($article['label_famille']=="Fruit"):;?>
<!--                            <form method="post" action="--><?//='article_client';?><!--">-->
<!--                                <div class="container">-->
<!--                                    <div class="row">-->
<!--                                        <input type="hidden" name="id_article" value="--><?//=$article['id_article'];?><!--">-->
<!--                                        <input type="hidden" name="label_unite" value="--><?//=$article['label_unite'];?><!--">-->
<!--                                        <input type="hidden" name="label_famille" value="--><?//=$article['label_famille'];?><!--">-->
<!--                                        <div class="col-3"><input type="hidden" name="label_article--><?//=$article['id_article'];?><!--" value="--><?//= $article["label_article"];?><!--">--><?//= $article["label_article"];?><!-- </div>-->
<!--                                        <div class="col-2"><input type="hidden" name="origine--><?//=$article['id_article'];?><!--" value=" --><?//= $article["origine"];?><!--"> --><?//= $article["origine"];?><!--</div>-->
<!--                                        <div class="col-2"><input type="hidden" name="prix--><?//=$article['id_article'];?><!--" value="--><?//= $article["prix"];?><!--">--><?//= $article["prix"]." €/".$article['label_unite'];?><!--  </div>-->
<!--                                        <div class="col-3"><input type="hidden" name="poids--><?//=$article['id_article'];?><!--" value="--><?//= $article["poids"];?><!--">--><?//= $article["poids"] ." " .$article['label_unite'];?><!-- </div>-->
<!--                                        <div class="col-1"><input type="number" id="quantite" name="quantite--><?//=$article['id_article'];?><!--" min="0" value="0"></div>-->
<!--                                        <div class="col-1"><button type="submit" class="btn btn-primary">Ajouter</button></div>-->
<!---->
<!--                                    </div>-->
<!--                                </div>-->
<!--                            </form>-->
<!--                        --><?php //endif ;?>
<!--                    --><?php //endforeach; ?>
<!---->
<!--                --><?php //else : ?>
<!--                    --><?php //foreach ($_SESSION['articleSearch'] as $article): ?>
<!--                   <form method="post" action="--><?//='article_client';?><!--">-->
<!--                       <div class="container">-->
<!--                           <div class="row">-->
<!--                                <div class="col-2"> --><?//= $article["label_article"];?><!-- </div>-->
<!--                                <div class="col-2"> --><?//= $article["origine"];?><!-- </div>-->
<!--                                <div class="col-2"> --><?//= $article["prix"]." €/".$article['label_unite'];?><!--  </div>-->
<!--                                <div class="col-2"> --><?//= $article["poids"] ." " .$article['label_unite'];?><!-- </div>-->
<!--                                <div class="col-2"> --><?//= $article["label_statusArticle"];?><!-- </div>-->
<!--                                <div class="col-1"> <a href="--><?//='edit_article?id='.$article["id_article"];?><!--"><i class="fa-solid fa-pen-to-square"></i></a> </div>-->
<!--                                <div class="col-1"> <a href="--><?//='delete_article?id='.$article["id_article"];?><!--"><i class="fa-solid fa-trash-can"></i></a> </div>-->
<!--                           </div>-->
<!--                       </div>-->
<!--                   </form>-->
<!--                    --><?php //endforeach;?>
<!--                --><?php //endif ;?>
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->

    <div class="container-fluid">
        <div class="row">
            <div class="col-12 tableColor-green pt-2 pb-3 ">
                <h2 class="text-center"> Listes des articles</h2>

                <div class="container ">
                    <div class="row">
                        <div class="col-3 text-center"> <p>Label</p> </div>
                        <div class="col-2 text-center"> <p>Origine</p> </div>
                        <div class="col-3 text-center"> <p>Prix</p> </div>
                        <div class="col-2 text-center"> <p>Poids</p> </div>
                        <div class="col-2 text-center"> </div>
                    </div>
                </div>
                <?php if(empty($_SESSION['articleSearch'])) :?>


                    <form method="post" action="<?='articles_client';?>">
                        <div class="container p-0">
                            <h3 class="text-center">Légumes</h3>
                    <?php foreach ($articles as $article): ?>
                        <?php if($article['label_famille']=="Légume"):?>
                            <?php if($article['label_statusArticle']=="stock"):?>

                                <div class="row commande">
                                    <input type="hidden" name="id_article[]" value="<?=$article['id_article'];?>">
                                    <input type="hidden" name="label_unite[]" value="<?=$article['label_unite'];?>">
                                    <input type="hidden" name="label_famille[]" value="<?=$article['label_famille'];?>">
                                    <div class="col-3 text-center"><input type="hidden" name="label_article[]" value="<?= $article["label_article"];?>"><?= $article["label_article"];?> </div>
                                    <div class="col-2 text-center"><input type="hidden" name="origine[]" value=" <?= $article["origine"];?>"> <?= $article["origine"];?></div>
                                    <div class="col-3 text-center"><input type="hidden" name="prix[]" value="<?= $article["prix"];?>"><?= $article["prix"]." €/".$article['label_unite'];?>  </div>
                                    <div class="col-2 text-center"><input type="hidden" name="poids[]" value="<?= $article["poids"];?>"><?= $article["poids"] ." " .$article['label_unite'];?> </div>
                                    <div class="col-2 p-0 text-center"><input class="w-50" type="number" id="quantite" name="quantite[]" min="0" value="0"></div>
                                </div>

                            <?php endif ;?>
                        <?php endif ;?>
                    <?php endforeach; ?>
                        </div>
                        <div class="container p-0">
                        <h3 class="text-center">Fruits</h3>
                        <?php foreach ($articles as $article): ?>
                            <?php if($article['label_famille']=="Fruit"):?>
                                <?php if($article['label_statusArticle']=="stock"):?>

                                    <div class="row commande">
                                        <input type="hidden" name="id_article[]" value="<?=$article['id_article'];?>">
                                        <input type="hidden" name="label_unite[]" value="<?=$article['label_unite'];?>">
                                        <input type="hidden" name="label_famille[]" value="<?=$article['label_famille'];?>">
                                        <div class="col-3 text-center"><input type="hidden" name="label_article[]" value="<?= $article["label_article"];?>"><?= $article["label_article"];?> </div>
                                        <div class="col-2 text-center"><input type="hidden" name="origine[]" value=" <?= $article["origine"];?>"> <?= $article["origine"];?></div>
                                        <div class="col-3 text-center"><input type="hidden" name="prix[]" value="<?= $article["prix"];?>"><?= $article["prix"]." €/".$article['label_unite'];?>  </div>
                                        <div class="col-2 text-center"><input type="hidden" name="poids[]" value="<?= $article["poids"];?>"><?= $article["poids"] ." " .$article['label_unite'];?> </div>
                                        <div class="col-2 p-0 text-center"><input class="w-50" type="number" id="quantite" name="quantite[]" min="0" value="0"></div>
                                    </div>

                                <?php endif ;?>
                            <?php endif ;?>
                        <?php endforeach; ?>
                        </div>
                    <div class="col-12 text-center pt-3 pb-2"><button type="submit" class="btn bg-custom-red">Valider la commande</button></div>

                    </form>
                <?php else : ?>
                    <?php foreach ($_SESSION['articleSearch'] as $article): ?>
                        <form method="post" action="<?='articles_client';?>">
                            <div class="container">
                                <div class="row">
                                    <input type="hidden" name="id_article[]" value="<?=$article['id_article'];?>">
                                    <input type="hidden" name="label_unite[]" value="<?=$article['label_unite'];?>">
                                    <input type="hidden" name="label_famille[]" value="<?=$article['label_famille'];?>">
                                    <div class="col-3"><input type="hidden" name="label_article[]" value="<?= $article["label_article"];?>"><?= $article["label_article"];?> </div>
                                    <div class="col-2"><input type="hidden" name="origine[]" value=" <?= $article["origine"];?>"> <?= $article["origine"];?></div>
                                    <div class="col-2"><input type="hidden" name="prix[]" value="<?= $article["prix"];?>"><?= $article["prix"]." €/".$article['label_unite'];?>  </div>
                                    <div class="col-3"><input type="hidden" name="poids[]" value="<?= $article["poids"];?>"><?= $article["poids"] ." " .$article['label_unite'];?> </div>
                                    <div class="col-1"><input type="number" id="quantite" name="quantite[]" min="0" value="0"></div>
                                </div>
                            </div>
                        </form>
                    <?php endforeach;?>
                <?php endif ;?>
            </div>
        </div>
    </div>


