<main class="mt-3">
    <?php displayFlashMessages() ; ?>
    <div class="container pt-3 pb-3">
        <h2 class="text-center text-red"> LISTES DES ARTICLES</h2>
        <div class="row">
            <div class="col-8 ">
                <form method="GET" action ="articles_client" class="navbar-form navbar-right" id="form-search" role="search">
                    <div class="input-group d-flex justify-content-center">
                        <?php if(empty($_SESSION['articleSearch'])) :?>
                            <input type="search" class="form-control" name="articleSearch" id="articleSearch" placeholder="Rechercher un article">
                        <?php else : ?>
                            <input type="search" class="form-control" name="articleSearch" id="articleSearch" value="<?=$params['articleSearch'];?>">
                        <?php endif;?>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12 pt-2 pb-2 border-custom bg-second-background-color pt-2 pb-3 pl-0 pr-0 view">

                <?php $this->render($this->file, 'liste_articles_client','', $params);?>

            </div>
        </div>
    </div>
</main>


<script src="http://localhost/TerrAnanas/public/js/articles_client.js" defer></script>