<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="http://localhost/TerrAnanas/public/css/dashboard.css">
    <link rel="stylesheet" type="text/css" href="http://localhost/TerrAnanas/public/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="http://localhost/TerrAnanas/public/css/styles_calendar.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">



    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oxygen&display=swap" rel="stylesheet">

    <title><?=$params['title'];?></title>
</head>

<body>
<header>

    <div class="container-fluid bg-light">
        <div class="row ">
            <div class="col-12 p-0">

                <nav class="navbar navbar-expand-md pl-3 pr-3 w-100">
<!--                    <div class="w-25 text-center">-->
<!--                        <img src="http://localhost/TerrAnanas/public/images/TerrAnanas_logo.png" class="w-25">-->
<!--                    </div>-->
                    <button class="navbar-toggler mr-2 mr-lg-0 border-0" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <img src="http://localhost/TerrAnanas/public/images/icon/hamburger-button.png" class="img-responsive mw-100" >
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarNavDropdown">
<!--                        <ul class="navbar-nav">-->
                        <div class="navbar-nav d-flex flex-row ">
                            <ul class="navbar-nav ">
                                <li class="nav-item">
                                    <a class="nav-link" href="articles_client">Passer une commande</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="historique_commandes">Mes commandes</a>
                                </li>
                            </ul>
                        </div>

                        <div class="navbar-nav d-flex flex-row">
                            <ul class="navbar-nav">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        TerrAnanas
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" href="home">Accueil TerrAnans</a>
                                        <a class="dropdown-item" href="parametre_client">Paramètre</a>
                                        <a class="dropdown-item" href="logout">Se déconnecter</a>
                                    </div>
                                </li>
                            </ul>
                            </ul>
                                <li>

                                </li>
                            </ul>
                        </div>
                    </div>

                    <a class="nav-link" href="panier" >
                        <img src="http://localhost/TerrAnanas/public/images/icon/panier.png" class="img-responsive mw-100" >
                    </a>
                    <div class="">
                        <ul class="navbar-nav ">
                            <li class="nav-item">
                                <a class="nav-link" href="client">Acceuil</a>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>


</header>
<?php include $template; ?>

<?php //include '../templates/client/' . $template . '.phtml'; ?>


<!--Chargement des scripts pour Bootstrap-->
<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/jquery-3.3.1.min.js" defer></script>
<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/bootstrap.js" defer></script>

<!-- Script pour activation du datepicker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" defer></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" defer></script>
<script src="http://localhost/ProjetCommande/public/js/script.js" defer></script>
</body>

</html>