<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="http://localhost/TerrAnanas/public/css/styles.css">



    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oxygen&display=swap" rel="stylesheet">

    <script type="text/javascript" src="http://localhost/TerrAnanas/public/js/responsive.js" defer></script>



    <title><?=$params['title'];?></title>
</head>

<body>
<header>

    <nav class="headerNavbar">
        <div class="headerNavbar-function" >
            <div class="headerNavbar-function-burger" id="menuresp">
                <i class="fa-solid fa-bars" id="burger"></i>
                <i class="fa-sharp fa-solid fa-xmark hide" id="cross"></i>
            </div>
            <ul class="headerNavbar-function-list"  >
                <li class="headerNavbar-function-list-item">
                    <a class="headerNavbar-function-list-item-link" href="client">TerrAnanas</a>
                </li>
                <li class="headerNavbar-function-list-item">
                    <a class="headerNavbar-function-list-item-link" href="articles_client">Passer une commande</a>
                </li>
                <li class="headerNavbar-function-list-item">
                    <a class="headerNavbar-function-list-item-link" href="historique_commandes">Mes commandes</a>
                </li>
            </ul>
        </div>
        <div class="headerNavbar-info" >
            <ul class="headerNavbar-info-list">
                <li class="headerNavbar-info-list-item">
                    <a class="headerNavbar-info-list-item-link" href="panier" >
                        <i class="fa-solid fa-cart-shopping">
                            <?php if(!empty($_SESSION['panier'])): ?>
                                <span><?= count($_SESSION['panier']) ?></span>
                            <?php endif;?>
                        </i>
                    </a>
                </li>
                <li class="headerNavbar-info-list-item">
                    <p class="headerNavbar-info-list-item-dropdown"><?=getUserName()?> <i class="fa-solid fa-caret-down"></i></p>
                    <ul class="headerNavbar-info-list-item-dropdownContent">
                        <li><a href="home">Accueil TerrAnanas</a></li>
                        <li><a href="parametre_client">Paramètre</a></li>
                        <li class="logout"><a  href="logout">Se déconnecter</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>

</header>
<main>
    <?php include $template; ?>
</main>


<footer>
    <div>
        <a href="#">Mention legal</a>
    </div>
    <div>
        <p>contact : terrananas@gmail.com</p>
    </div>
</footer>
<!--Chargement des scripts pour Bootstrap-->
<!--<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/jquery-3.3.1.min.js" defer></script>-->
<!--<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/bootstrap.js" defer></script>-->

<!-- Script pour activation du datepicker -->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" defer></script>-->
<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" defer></script>-->
<!--<script src="http://localhost/ProjetCommande/public/js/script.js" defer></script>-->
</body>

</html>