
<div class="headerDate">
    <div class="headerDate-livraison">
        <h4 class=""><?=$params['dateDuJour']?></h4>
        <p>Livraison du jour : Voir</p>
    </div>
</div>

<div class="templateListeCommande">

    <div class="liste">
        <h4 class="headerTitle">COMMANDE EN ATTENTE</h4>
        <div class="liste-commande head">
                <div class="liste-commande-item">COMMANDE N°</div>
                <div class="liste-commande-item">DATE COMMANDE</div>
                <div class="liste-commande-item">DATE LIVRAISON</div>
                <div class="liste-commande-item">MONTANT</div>
                <div class="liste-commande-item detail">DETAILS</div>
            </div>
        <?php if($params['commandeEnAttente']) : ?>
            <?php foreach ($params['commandeEnAttente'] as $commandeAttente): ?>
                <div class="liste-commande" >
                    <div class="liste-commande-item" ><?=$commandeAttente['id_commande'];?></div>
                    <div class="liste-commande-item" ><?=date('d/m/y', strtotime($commandeAttente['date_commande']));?></div>
                    <div class="liste-commande-item" ><?=date('d/m/y', strtotime($commandeAttente['date_livraison'])) ;?></div>
                    <div class="liste-commande-item" ><?=($commandeAttente['montant']/100) ." €" ;?></div>
                    <div class="liste-commande-item detail" ><a href="<?='one_commande?id='.$commandeAttente["id_commande"];?>"><i class="fa-solid fa-eye"></i></a> </div>
                </div>
            <?php endforeach; ?>
        <?php else:?>
            <div class="emptyCommande">
                <p>Aucune commande</p>
            </div>
        <?php endif;?>
    </div>


    <div class="liste">
        <h4 class="headerTitle">COMMANDE VALIDEE</h4>
        <div class="liste-commande head">
            <div class="liste-commande-item">COMMANDE N°</div>
            <div class="liste-commande-item">DATE COMMANDE</div>
            <div class="liste-commande-item">DATE LIVRAISON</div>
            <div class="liste-commande-item">MONTANT</div>
            <div class="liste-commande-item detail">DETAILS</div>
        </div>
        <?php if($params['commandeValidee']) : ?>
        <?php foreach ($params['commandeValidee'] as $commandeValidee): ?>
            <div class="liste-commande" >
                <div class="liste-commande-item" ><?=$commandeValidee['id_commande'];?></div>
                <div class="liste-commande-item" ><?=date('d/m/y', strtotime($commandeValidee['date_commande']));?></div>
                <div class="liste-commande-item" ><?=date('d/m/y', strtotime($commandeValidee['date_livraison'])) ;?></div>
                <div class="liste-commande-item" ><?=($commandeValidee['montant']/100) ." €" ;?></div>
                <div class="liste-commande-item detail" ><a href="<?='one_commande?id='.$commandeValidee["id_commande"];?>"><i class="fa-solid fa-eye"></i></a> </div>
            </div>
        <?php endforeach; ?>
        <?php else:?>
            <div class="emptyCommande">
                <p>Aucune commande</p>
            </div>
        <?php endif;?>
    </div>
</div>
