<main>
    <h3 class="text-center p-0 m-0 text-custom-color-red"><?=$params['dateDuJour']?></h3>
    <div class="container">
        <div class="row">
            <div class="col-12  ml-lg-auto mr-lg-3 p-0 mt-5">
                <div class="col-12 mb-3 pb-3 pt-2  bg-light ">
                    <h4 class=" text-center p-2 mb-4 ">Livraison du jour</h4>
                    <?php foreach ($params['livraisonDuJour'] as $livraison): ?>
                        <div class="row commande">
                            <div class="col-4"><p class=""><?=date('d/m/y', strtotime($livraison['date_commande']));?></p> </div>
                            <div class="col-4"><p><?=date('d/m/y', strtotime($livraison['date_livraison'])) ;?></p> </div>
                            <div class="col-3"><p><?=($livraison['montant']/100) ." €" ;?></p> </div>
                            <div class="col-1 p-1"><a href="#">Voir</a> </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <div class="col-12 mb-3 pb-3 pt-2  bg-light ">
                    <h4 class=" text-center p-2 mb-4 ">Commande en attente</h4>
                    <div class="row ">
                        <div class="col-4"><p class="">Jour de la commande</p> </div>
                        <div class="col-4"><p>Jour de la livraison</p> </div>
                        <div class="col-3"><p>Montant</p> </div>
                        <div class="col-1 p-1"> </div>
                    </div>
                    <?php foreach ($params['commandeEnAttente'] as $commande): ?>
                        <div class="row commande">
                            <div class="col-4"><p class=""><?=date('d/m/y', strtotime($commande['date_commande']));?></p> </div>
                            <div class="col-4"><p><?=date('d/m/y', strtotime($commande['date_livraison'])) ;?></p> </div>
                            <div class="col-3"><p><?=($commande['montant']/100) ." €" ;?></p> </div>
                            <div class="col-1 p-1"><a href="#">Voir</a> </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
<!--            <div class="col-12 col-lg-3  mt-lg-5 ml-lg-2 mr-lg-3 p-0">-->
<!--                <div class="row d-flex justify-content-around mr-0 ml-0">-->
<!--                    <div class="col-5 col-lg-10  mb-3 bg-success ">-->
<!--                        <h4 class="text-center">Franco</h4>-->
<!--                        <form method="post" action="admin" id="submit-franco" class="d-flex flex-column align-items-center">-->
<!--                            <input class="w-75 m-1" type="text" name="franco" placeholder="--><?//=$franco['franco'];?><!--">-->
<!--                            <button class="w-50 m-1" type="submit" class="button-franco">Modifier</button>-->
<!--                        </form>-->
<!--                    </div>-->
<!--                    <div class="col-5 col-lg-10  mb-3 bg-danger ">-->
<!--                        <h4 class="text-center">Messagerie</h4>-->
<!--                        <p class="text-center">(3) Message(s) en attente <a class="text-dark" href="#">Voir</a></p>-->
<!--                    </div>-->
<!--                    <div class="col-5 col-lg-10  mb-3 bg-primary ">-->
<!--                        <h4 class="text-center">CA du jour</h4>-->
<!--                        <p class="text-center mt-2 mb-2">250,67 €</p>-->
<!--                    </div>-->
<!--                    <div class="col-5 col-lg-10  mb-3 ">-->
<!--                    </div>-->
<!--                </div>-->
<!---->
<!--            </div>-->
        </div>
    </div>
</main>