<main>

    <div class="container mt-3 mb-3">
        <form method="post" action="historique_commandes" id="form-commande">
        <div class="row">
            <div class="col-12 col-md-6">
                <div class="form-group">
                        <div class="form-group">
                            <div class="datepicker date input-group">
                                <?php if(empty($_SESSION['commandeByDate'])) :?>
                                    <input type="search" name="searchDate" placeholder="Choisir une date" class="form-control" id="reservationDate">
                                <?php else : ?>
                                    <input type="search" name="searchDate" value="<?= $params['date'];?>" class="form-control" id="reservationDate">
                                <?php endif;?>

                                <div class="input-group-append"><span class="input-group-text px-"><i class="fa fa-calendar"></i></span></div>
                            </div>
                        </div>
                    </div>
            </div>
            <div class="col-12 col-md-6">
                    <select class="form-control " name="status" id="status">
                        <?php if(!empty($params['commandes'])):?>
                            <option value="<?=$params['commandes'][0]['id_status'] ?>"><?= $params['commandes'][0]['label_status']?></option>
                        <?php endif ;?>

                        <?php foreach ($params['status'] as $status): ?>
                            <?php if($status['id_status'] != $params['commandes'][0]['id_status']): ?>
                                <option value="<?=$status['id_status'];?>"><?=$status['label_status'];?></option>
                            <?php endif ;?>
                        <?php endforeach; ?>
                    </select>
            </div>
        </div>
            <div class="mt-2 text-center justify-content-end">
                <button type="submit" class="btn bg-custom-red mb-2 ">Valider</button>
            </div>
        </form>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12 border-custom bg-second-background-color pt-2 pb-3 pl-0 pr-0">
                <h3 class="text-center text-red"> Mes commandes </h3>
                <div class="container bg-first-lightbackground-color">
                    <div class="row pt-2 pb-2">
                        <div class="col-2 text-center"> <p>Commande</p> </div>
                        <div class="col-4 col-sm-3 col-md-2 text-center"> <p>Montant</p> </div>
                        <div class="col-4 d-none d-md-block col-md-3 text-center"> <p>Date commande</p> </div>
                        <div class="col-4 col-md-3 text-center"> <p>Date livraison</p> </div>
                        <div class="col-2 text-center"> <p>Détails</p> </div>

                    </div>
                </div>

                <?php if(empty($_SESSION['commandeByDate'])) :?>
                    <div class="container">
                        <?php foreach ($params['commandes'] as $commande): ?>
                            <div class="row pt-2 pb-2 line-out" >
                                <div class="col-2 text-center" ><?=$commande['id_commande'];?></div>
                                <div class="col-4 col-sm-3 col-md-2 text-center" ><?=($commande['montant']/100) ." €" ;?> </div>
                                <div class="col-4 d-none d-md-block col-md-3 text-center" ><?= date('d/m/y', strtotime($commande['date_commande'])) ;?> </div>
                                <div class="col-4 col-md-3 text-center" ><?= date('d/m/y', strtotime($commande['date_livraison'])) ;?> </div>
                                <div class="col-2 text-center"><a href="<?='one_commande?id='.$commande["id_commande"];?>"><i class="fa-solid fa-eye"></i></a></div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php else :?>
                    <div class="container">
                        <?php foreach ($_SESSION['commandeByDate'] as $commande): ?>
                                <div class="row pt-2 pb-2 line-out" >
                                    <div class="col-2 text-center" ><?=$commande['id_commande'];?></div>
                                    <div class="col-4 col-sm-2 col-md-2 text-center" ><?=$commande['montant'] ." €" ;?> </div>
                                    <div class="col-4 d-none d-sm-block col-md-3 text-center" ><?= date('d/m/y', strtotime($commande['date_commande'])) ;?> </div>
                                    <div class="col-5 col-sm-4 col-md-3 text-center" ><?= date('d/m/y', strtotime($commande['date_livraison'])) ;?> </div>
                                    <div class="col-2  text-center"> <a href="<?='one_commande?id='.$commande["id_article"];?>"><i class="fa-solid fa-eye"></i></a> </div>
                                </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif;?>
            </div>
        </div>
    </div>

</main>

