<form method="POST" action="<?='add_panier';?>" id="form-article">

<?php if(isset($_SESSION['articleSearch'])) :?>
    <?php if(empty($_SESSION['articleSearch'])) :?>
        <div class="container-fluide">
            <div class="container p-0 ">
                <div class="container p-0 ">
                    <div class="row bg-first-lightbackground-color pt-2 pb-2 m-0 d-grid">
                        <div class="col-6 col-md-3 text-center font-weight-bold "> <p>Article</p> </div>
                        <div class="col-6 col-md-3 text-center font-weight-bold "> <p>Origine</p> </div>
                        <div class="col-6 col-md-2 text-center font-weight-bold "> <p>Prix/Unitée</p> </div>
                        <div class="col-6 col-md-2 text-center font-weight-bold "> <p>Poids</p> </div>
                        <div class="col-12 col-md-2 text-center font-weight-bold "> <p>Quantité</p> </div>
                    </div>
                </div>
            </div>
            <div class="row line-out pt-2 pb-2 m-0 d-grid">
                <div class="col-12 text-center  "> Aucun article trouvé</div>
            </div>
        </div>

    <?php else : ?>
        <div class="container p-0 ">
            <div class="container p-0 ">
                <div class="row bg-first-lightbackground-color pt-2 pb-2 m-0 d-grid">
                    <div class="col-6 col-md-3 text-center font-weight-bold "> <p>Article</p> </div>
                    <div class="col-6 col-md-3 text-center font-weight-bold "> <p>Origine</p> </div>
                    <div class="col-6 col-md-2 text-center font-weight-bold "> <p>Prix/Unitée</p> </div>
                    <div class="col-6 col-md-2 text-center font-weight-bold "> <p>Poids</p> </div>
                    <div class="col-12 col-md-2 text-center font-weight-bold "> <p>Quantité</p> </div>
                </div>
            </div>
            <?php foreach ($_SESSION['articleSearch'] as $article): ?>

                <div class="row line-out pt-2 pb-2 m-0 d-grid">
                    <input type="hidden" name="id_article[]" value="<?=$article['id_article'];?>">
                    <input type="hidden" name="unite[]" value="<?=$article['unite'];?>">
                    <input type="hidden" name="famille[]" value="<?=$article['famille'];?>">
                    <div class="col-6 col-md-3 mt-2 mb-2 text-center "> <input type="hidden" name="article[]" value="<?= $article["article"];?>"><?= $article["article"];?> </div>
                    <div class="col-6 col-md-3 mt-2 mb-2 text-center "> <input type="hidden" name="origine[]" value=" <?= $article["origine"];?>"> <?= $article["origine"];?> </div>
                    <div class="col-6 col-md-2 mt-2 mb-2 text-center "> <input type="hidden" name="prix[]" value="<?= $article["prix"]/100;?>"><?= ($article["prix"]/100)." €/".$article['unite'];?>   </div>
                    <div class="col-6 col-md-2 mt-2 mb-2 text-center "> <input type="hidden" name="poids[]" value="<?= $article["poids"];?>"><?= $article["poids"] ." " .$article['unite'];?>  </div>
                    <div class="col-12 col-md-2 text-center  "> <input class="w-50 text-center quantite" type="number" id="<?=$article['id_article'];?>" name="quantite[]" min="0" value="0"></div>
                </div>
            <?php endforeach; ?>

        </div>
    <?php endif;?>
<?php else : ?>

    <div class="container-fluide">
        <h3 class="text-center text-red m-0 p-2">Légumes</h3>
        <div class="container p-0 ">
            <div class="row bg-first-lightbackground-color pt-2 pb-2 m-0 d-grid">
                <div class="col-6 col-md-3 text-center font-weight-bold "> <p>Article</p> </div>
                <div class="col-6 col-md-3 text-center font-weight-bold "> <p>Origine</p> </div>
                <div class="col-6 col-md-2 text-center font-weight-bold "> <p>Prix/Unitée</p> </div>
                <div class="col-6 col-md-2 text-center font-weight-bold "> <p>Poids</p> </div>
                <div class="col-12 col-md-2 text-center font-weight-bold "> <p>Quantité</p> </div>
            </div>
        </div>
        <?php foreach ($params['articles'] as $article): ?>
            <?php if($article['famille']=="Légume" && $article['id_statutArticle']!=3):?>
                <div class="row line-out pt-2 pb-2 m-0 d-grid">
                    <input type="hidden" name="id_article[]" value="<?=$article['id_article'];?>">
                    <input type="hidden" name="unite[]" value="<?=$article['unite'];?>">
                    <input type="hidden" name="famille[]" value="<?=$article['famille'];?>">
                    <div class="col-6 col-md-3 mt-2 mb-2 text-center ">
                        <input type="hidden" name="article[]" value="<?= $article["article"];?>"><?= $article["article"];?>
                    </div>
                    <div class="col-6 col-md-3 mt-2 mb-2 text-center ">
                        <input type="hidden" name="origine[]" value=" <?= $article["origine"];?>"> <?= $article["origine"];?>
                    </div>
                    <div class="col-6 col-md-2 mt-2 mb-2 text-center ">
                        <input type="hidden" name="prix[]" value="<?= $article["prix"]/100;?>"><?= ($article["prix"]/100)." €/".$article['unite'];?>
                    </div>
                    <div class="col-6 col-md-2 mt-2 mb-2 text-center ">
                        <input type="hidden" name="poids[]" value="<?= $article["poids"];?>"><?= $article["poids"] ." " .$article['unite'];?>
                    </div>
                    <div class="col-12 col-md-2 text-center  ">
                        <input class="w-50 text-center quantite" type="number" id="<?=$article['id_article'];?>" name="quantite[]" min="0" value="0">
                    </div>
                </div>
            <?php endif ;?>
        <?php endforeach; ?>
    </div>

    <div class="container-fluide ">
        <h3 class="text-center text-red m-0 p-2 " >Fruits</h3>
        <div class="container p-0 ">
            <div class="row bg-first-lightbackground-color pt-2 pb-2 m-0 d-grid">
                <div class="col-6 col-md-3 text-center font-weight-bold "> <p>Article</p> </div>
                <div class="col-6 col-md-3 text-center font-weight-bold "> <p>Origine</p> </div>
                <div class="col-6 col-md-2 text-center font-weight-bold "> <p>Prix/Unitée</p> </div>
                <div class="col-6 col-md-2 text-center font-weight-bold "> <p>Poids</p> </div>
                <div class="col-12 col-md-2 text-center font-weight-bold "> <p>Quantité</p> </div>
            </div>
        </div>
        <?php foreach ($params['articles'] as $article): ?>
            <?php if($article['famille']=="Fruit" && $article['id_statutArticle']!=3):?>
                <div class="row line-out pt-2 pb-2 m-0 d-grid">
                    <input type="hidden" name="id_article[]" value="<?=$article['id_article'];?>">
                    <input type="hidden" name="unite[]" value="<?=$article['unite'];?>">
                    <input type="hidden" name="famille[]" value="<?=$article['famille'];?>">
                    <div class="col-6 col-md-3 mt-2 mb-2 text-center "> <input type="hidden" name="article[]" value="<?= $article["article"];?>"><?= $article["article"];?> </div>
                    <div class="col-6 col-md-3 mt-2 mb-2 text-center "> <input type="hidden" name="origine[]" value=" <?= $article["origine"];?>"> <?= $article["origine"];?> </div>
                    <div class="col-6 col-md-2 mt-2 mb-2 text-center "> <input type="hidden" name="prix[]" value="<?= $article["prix"]/100;?>"><?= ($article["prix"]/100)." €/".$article['unite'];?>   </div>
                    <div class="col-6 col-md-2 mt-2 mb-2 text-center "> <input type="hidden" name="poids[]" value="<?= $article["poids"];?>"><?= $article["poids"] ." " .$article['unite'];?>  </div>
                    <div class="col-12 col-md-2 text-center  "> <input class="w-50 text-center quantite" type="number" id="<?=$article['id_article'];?>" name="quantite[]" min="0" value="0"></div>
                </div>
            <?php endif ;?>
        <?php endforeach; ?>
    </div>
<?php endif;?>
    <div class="col-12 text-center pt-3 pb-2"><button type="submit" class="btn bg-alt-background-color text-darkgreen">Valider</button> </div>
</form>