<div class="flash-message">
    <?php displayFlashMessages() ; ?>
</div>
<h3 class="headerTitle">VOTRE PANIER</h3>
<?php if(!empty($_SESSION['panier'])) :?>


<form method="POST" action="<?='validation_commande';?>" id="form-commande">
    <div class="headerPanier">
        <label class="headerPanier-label">Sélectionner une date de livraison</label>
        <select class="headerPanier-select" name="dateLivraison" id="dateLivraison">
            <option value="<?= date('y-m-d', strtotime(($params['date']->format('y-m-d')). ' + 1 days'))  ?>">
                <?= $params['dateLivraison1'] ;?>
            </option>
            <option value="<?= date('y-m-d', strtotime(($params['date']->format('y-m-d')) . ' + 2 days')) ?>">
                <?= $params['dateLivraison2'] ;?>
            </option>
        </select>
        <div class="headerPanier-button">
            <button type="submit">Valider la commande</button>
        </div>
    </div>




<?php endif;?>

<?php if(isset($params['articles'])): ?>


<div class="liste">
    <div class="liste-article head list">
        <div class="liste-article-item"> <p>ARTICLE</p> </div>
        <div class="liste-article-item"> <p>ORIGINE</p> </div>
        <div class="liste-article-item"> <p>PRIX</p> </div>
        <div class="liste-article-item"> <p>POIDS</p> </div>
<!--        <div> </div>-->
    </div>

<?php foreach ($params['articles'] as $article): ?>
    <div class="liste-article list">
        <input type="hidden" name="id_article[]" value="<?=$article['id_article'];?>">
        <input type="hidden" name="unite[]" value="<?=$article['unite'];?>">
        <input type="hidden" name="famille[]" value="<?=$article['famille'];?>">
        <div class="liste-article-item"><input type="hidden" name="article[]" value="<?= $article["article"];?>">
            <?= $article["article"];?>
        </div>
        <div class="liste-article-item"><input type="hidden" name="origine[]" value=" <?= $article["origine"];?>">
            <?= $article["origine"];?>
        </div>
        <div class="liste-article-item"><input type="hidden" name="prix[]" value="<?= $article["prix"];?>">
            <?= $article["prix"]." €/".$article['unite'];?>
        </div>
        <div class="liste-article-item">
            <input type="hidden" name="poids[]" value="<?= $article["poids"];?>"><?= $article["poids"] ." " .$article['unite'];?>
        </div>
        <div class="liste-article-item quantite">
            <input type="number" id="quantite" name="quantite[]" min="0" value="<?=$article['quantite'];?>">
        </div>
    </div>
<?php endforeach; ?>

    </div>

</form>

<?php else:?>

<div class="emptyPanier"><h4><?=$params['message'];?></h4> </div>


<?php endif ;?>
<div class="buttonPanier">
    <div class="buttonPanier-retour">
        <button> <a href="articles_client"> Retourner sur la liste des articles </a></button>
    </div>
    <div class="buttonPanier-vider">
        <button><a href="empty_basket"> Vider son panier </a></button>
    </div>
</div>

