<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="http://localhost/ProjetCommande/public/css/bootstrap.css">
    <title>Articles</title>
</head>
<body>
<form method="POST" action="<?='add_article';?>">
    <div class="form-group">
        <label for="label">Article</label>
        <input type="text" class="form-control" id="label" name="label" value="<?=$label;?>">
        <?php if (isset($error['label'])): ?>
            <p class="error"><?=htmlspecialchars($error['label']);?></p>
        <?php endif; ?>
    </div>
    <div class="form-group">
        <label for="origine">Origine</label>
        <input type="text" class="form-control" id="origine" name="origine" value="<?=$origine;?>">
        <?php if (isset($error['origine'])): ?>
            <p class="error"><?=htmlspecialchars($error['origine']);?></p>
        <?php endif; ?>
    </div>
    <div class="form-group">
        <label for="prix">Prix</label>
        <input type="text" class="form-control" id="prix" name="prix" value="<?=$prix;?>">
        <?php if (isset($error['prix'])): ?>
            <p class="error"><?=htmlspecialchars($error['prix']);?></p>
        <?php endif; ?>
    </div>
    <div class="form-group">
        <label for="poids">Quantité</label>
        <input type="text" class="form-control" id="quantité" name="poids" value="<?=$poids;?>">
        <?php if (isset($error['poids'])): ?>
            <p class="error"><?=htmlspecialchars($error['poids']);?></p>
        <?php endif; ?>
    </div>
    <div class="form-group">
        <label for="unite">Unite</label>
        <select class="form-control" name="unite" id="unite">
            <option value="0">Sélectionner une famille</option>
            <?php foreach ($unites as $unite): ?>
                <option value="<?=$unite['id_unite'];?>"><?=$unite['label_unite'];?></option>
            <?php endforeach; ?>
        </select>
        <?php if (isset($error['unite'])): ?>
            <p class="error"><?=htmlspecialchars($error['unite']);?></p>
        <?php endif; ?>
    </div>
    <div class="form-group">
        <label for="famille">Famille</label>
        <select class="form-control" name="famille" id="famille">
            <option value="0">Sélectionner une famille</option>
            <?php foreach ($familles as $famille): ?>
                <option value="<?=$famille['id_famille'];?>"><?=$famille['label_famille'];?></option>
            <?php endforeach; ?>
        </select>
        <?php if (isset($error['famille'])): ?>
            <p class="error"><?=htmlspecialchars($error['famille']);?></p>
        <?php endif; ?>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>



<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/jquery-3.3.1.min.js" ></script>
<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/bootstrap.js" ></script>
</body>

</html>