<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"-->
<!--          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">-->
    <link rel="stylesheet" type="text/css" href="../public/css/bootstrap.css">
    <title>Mon responsive</title>
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="container ">
                <div class="row">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <div class="col-2">
                            <li class="nav-item">
                                <a class="nav-link " href="#">Accueil</a>
                            </li>
                        </div>
                        <div class="col-2">
                            <li class="nav-item">
                                <a class="nav-link active" href="#">Articles</a>
                            </li>
                        </div>
                        <div class="col-2">
                            <li class="nav-item">
                                <a class="nav-link " href="#">Commandes</a>
                            </li>
                        </div>
                        <div class="col-2">
                            <li class="nav-item">
                                <a class="nav-link " href="#">Clients</a>
                            </li>
                        </div>
                        <div class="col-2">
                            <li class="nav-item">
                                <a class="nav-link " href="#">Paramètre</a>
                            </li>
                        </div>
                    </ul>
                </div>
            </div>

        </div>
    </nav>




<!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"-->
<!--        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"-->
<!--        crossorigin="anonymous"></script>-->
<script type="text/javascript" src="../public/js/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="../public/js/bootstrap.js"></script>

</body>

</html>