<div class="container p-0 bg-light border border-dark rounded">
    <h2 class="text-center p-0 m-0 bg-primary">Date du jour</h2>
    <h4 class="text-center p-0  bg-primary"><?=$dateDuJour?></h4>
    <div class="row">
        <span class="p-3 ml-1 mr-1">Info à communiquer : Sit enim idem caecus, debilis. Sint ista Graecorum; Quae cum dixisset, finem ille. Cave putes quicquam esse verius. Nam Pyrrho, Aristo, Erillus iam diu abiecti. </span>
    </div>
</div>

<div class="container mt-2  ">
    <div class="row d-flex justify-content-between">
        <div class="col-12 col-md-3 p-0 mb-3 border border-dark rounded d-none d-md-block">
            <h3 class="text-center p-0 m-0 bg-primary">CA du jour</h3>
            <p class="text-center">250,67 €</p>
        </div>
        <div class="col-12 col-md-3  border p-0 mb-3 border-dark rounded">
            <h3 class="text-center p-0 m-0 bg-primary">Franco</h3>
            <p class="text-center">300 € <a class="text-dark" href="#">Modifier</a></p>
        </div>
        <div class="col-12 col-md-3  border p-0 mb-3 border-dark rounded">
            <h3 class="text-center p-0 m-0 bg-primary">Messagerie</h3>
            <p class="text-center">(3) Message(s) en attente <a class="text-dark" href="#">Voir</a></p>
        </div>

    </div>
</div>



<div class="container">
    <div class="row">
        <div class="border border-dark rounded bg-light p-0 mb-3 col-12 col-md-7 col-lg-5">
            <h3 class="p-0 m-0 text-center bg-primary">Inscription en attente</h3>
            <div class=" container bg-light p-1">
                <div class="row">
                    <div class="col-4"><p>Société</p> </div>
                    <div class="col-4"><p>Email</p> </div>
                    <div class="col-4"><p>Adresse</p> </div>
                </div>
            </div>
            <div class="text-center justify-content-end bg-light pt-2 pb-2">
                <a class="w-25  badge badge-success d-inline" href="users">Voir tous les clients</a>
            </div>
        </div>
        <div class="col-12 col-md-4 offset-md-1 col-lg-5 offset-lg-2 d-none d-md-block border border-dark rounded bg-light p-0 mb-3 ">
            <h3 class="p-0 m-0 text-center bg-primary">Top 5 Article</h3>
            <div class="bg-light p-1">
                <p>Pomme</p>
                <p>Banane</p>
                <p>Kiwi</p>
            </div>
            <div class="text-center pt-2 pb-2">
                <a class="w-25  badge badge-success d-inline" href="articles">Voir tous les articles</a>
            </div>
        </div>
        <div class="border border-dark rounded p-0 bg-light mb-3 col-12 col-md-12">
            <h3 class="p-0 m-0 text-center bg-primary">Commande du jour</h3>
            <div class=" container p-0">
                <div class="row  commande mr-auto ml-auto">
                    <div class="col-3"><p>Société</p> </div>
                    <div class="col-3"><p>Date de livraison</p> </div>
                    <div class="col-3"><p>Montant</p> </div>
                    <div class="col-3"><a href="#">Voir</a> </div>
                </div>
                <div class="row commande mr-auto ml-auto">
                    <div class="col-3"><p>Société</p> </div>
                    <div class="col-3"><p>Date de livraison</p> </div>
                    <div class="col-3"><p>Montant</p> </div>
                    <div class="col-3"><a href="#">Voir</a> </div>
                </div>
                <div class="row commande mr-auto ml-auto">
                    <div class="col-3"><p>Société</p> </div>
                    <div class="col-3"><p>Date de livraison</p> </div>
                    <div class="col-3"><p>Montant</p> </div>
                    <div class="col-3"><a href="#">Voir</a> </div>
                </div>
                <div class="row commande mr-auto ml-auto">
                    <div class="col-3"><p>Société</p> </div>
                    <div class="col-3"><p>Date de livraison</p> </div>
                    <div class="col-3"><p>Montant</p> </div>
                    <div class="col-3"><a href="#">Voir</a> </div>
                </div>


            </div>
            <div class="text-center pt-2 pb-2 bg-light pb-1 pt-1">
                <a class="w-100  badge badge-success d-inline" href="commande_admin">Voir toutes les commande</a>
            </div>
        </div>
    </div>
</div>
