<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="http://localhost/ProjetCommande/public/css/bootstrap.css">
    <title>Articles</title>
</head>

<body>

    <head>
        <div class="container">
            <div class="row">
                <div class="col-4">
                    <form method="post" class="navbar-form navbar-right" role="search">
                        <div class="input-group">
                            <input type="text" class="form-control" name="search" placeholder="Rechercher un article">
                            <span class="input-group-btn">
                    <button type="submit" class="btn btn-default" >
                        Ok
<!--                    <span class="glyphicon glyphicon-search"></span>-->
                    </button>
<!--                    </span>-->
                        </div>
                    </form>
                </div>
                <div class="col-4">
                    <a href="add_article"> Ajouter un article </a>
                </div>
                <div class="col-4">
                    <form method="post" action="franco" id="submit-franco">
                        <input type="text" name="franco" placeholder="">
                        <button type="submit" class="button-franco">ok</button>
                    </form>
                </div>
            </div>
        </div>

    </head>
    <div class="container">
        <div class="row">
                    <div class="col-12">
                        <h2> Listes des articles</h2>
                        <div class="container">
                            <div class="row">
                                <div class="col-2"> <p>Label</p> </div>
                                <div class="col-2"> <p>Origine</p> </div>
                                <div class="col-2"> <p>Prix</p> </div>
                                <div class="col-2"> <p>Poids</p> </div>
<!--                                <div class="col-2"> <p>Supprimer</p> </div>-->
<!--                                <div class="col-2"> <p>Modifier</p> </div>-->
                            </div>
                        </div>
                        <div class="container">
                            <h3>Légumes</h3>
                            <div class="row">

                                <?php foreach ($articles as $article): ?>
                                <?php if($article['label_famille']=="Légume"):;?>
                                    <div class="col-2"> <?= $article["label_article"];?> </div>
                                    <div class="col-2"> <?= $article["origine"];?> </div>
                                    <div class="col-2"> <?= $article["prix"];?> € </div>
                                    <div class="col-2"> <?= $article["poids"] ." " .$article['label_unite'];?> </div>
                                    <div class="col-2"> <a href="<?='edit_article?id='.$article["id_article"];?>">Modifier</a> </div>
                                    <div class="col-2"> <a href="<?='delete_article?id='.$article["id_article"];?>">Supprimer</a> </div>
                                <?php endif ;?>
                                <?php endforeach; ?>

                            </div>
                        </div>

                        <div class="container">
                            <h3>Fruits</h3>
                            <div class="row">

                                <?php foreach ($articles as $article): ?>
                                <?php if($article['label_famille']=="Fruit"):?>
                                    <div class="col-2"> <?= $article["label_article"];?> </div>
                                    <div class="col-2"> <?= $article["origine"];?> </div>
                                    <div class="col-2"> <?= $article["prix"];?> € </div>
                                    <div class="col-2"> <?= $article["poids"].' ' .$article['label_unite'];?></div>
                                    <div class="col-2"> <a href="<?='edit_article?id='.$article["id_article"];?>">Modifier</a> </div>
                                    <div class="col-2"> <a href="<?='delete_article?id='.$article["id_article"];?>">Supprimer</a> </div>
                                <?php endif ;?>

                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php if(isset($_SESSION['franco'])):  ?>
        <?php if($_SESSION['franco'] >= 100):  ?>

        <p> ok franco atteint</p>
        <?php endif ?>
    <?php endif ?>


<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/jquery-3.3.1.min.js" ></script>
<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/bootstrap.js" ></script>
</body>

</html>