 <head>
    <div class="container">
        <div class="row">
            <div class="col-4">
                <form method="post" action ="articles" class="navbar-form navbar-right" role="search">
                    <div class="input-group">
                        <?php if(empty($_SESSION['articleSearch'])) :?>
                            <input type="search" class="form-control" name="articleSearch" placeholder="Rechercher un article">

                        <?php else : ?>
                            <input type="search" class="form-control" name="articleSearch" value="<?= $_POST['articleSearch'];?>">
                        <?php endif;?>

                        <span class="input-group-btn">
                        <button type="submit" class="btn btn-default" >
                            Ok
                        <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                </form>
            </div>
            <div class="col-4">
                <a href="add_article"> Ajouter un article </a>
            </div>
            <div class="col-4">
                <form method="post" action="articles" id="submit-franco">
                    <input type="text" name="franco" placeholder="<?=$franco['franco'];?>">
                    <button type="submit" class="button-franco">ok</button>
                </form>
            </div>
        </div>
    </div>

</head>
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2> Listes des articles</h2>
            <div class="container">
                <div class="row">
                    <div class="col-2"> <p>Label</p> </div>
                    <div class="col-2"> <p>Origine</p> </div>
                    <div class="col-2"> <p>Prix</p> </div>
                    <div class="col-2"> <p>Poids</p> </div>
                    <div class="col-2"> <p>Statut</p> </div>
                </div>
            </div>

            <?php if(empty($_SESSION['articleSearch'])) :?>
                <div class="container">
                    <h3>Légumes</h3>
                    <div class="row">

                        <?php foreach ($articles as $article): ?>
                            <?php if($article['label_famille']=="Légume"):;?>
                                <div class="col-2"> <?= $article["label_article"];?> </div>
                                <div class="col-2"> <?= $article["origine"];?> </div>
                                <div class="col-2"> <?= $article["prix"]." €/".$article['label_unite'];?>  </div>
                                <div class="col-2"> <?= $article["poids"] ." " .$article['label_unite'];?> </div>
                                <div class="col-2"> <?= $article["label_statusArticle"];?> </div>
                                <div class="col-1"> <a href="<?='edit_article?id='.$article["id_article"];?>"><i class="fa-solid fa-pen-to-square"></i></a> </div>
                                <div class="col-1"> <a href="<?='delete_article?id='.$article["id_article"];?>"><i class="fa-solid fa-trash-can"></i></a> </div>
                            <?php endif ;?>
                        <?php endforeach; ?>

                    </div>
                </div>

                <div class="container">
                    <h3>Fruits</h3>
                    <div class="row">

                        <?php foreach ($articles as $article): ?>
                            <?php if($article['label_famille']=="Fruit"):?>
                                <div class="col-2"> <?= $article["label_article"];?> </div>
                                <div class="col-2"> <?= $article["origine"];?> </div>
                                <div class="col-2"> <?= $article["prix"]." €/".$article['label_unite'];?>  </div>
                                <div class="col-2"> <?= $article["poids"] ." " .$article['label_unite'];?> </div>
                                <div class="col-2"> <?= $article["label_statusArticle"];?> </div>
                                <div class="col-1"> <a href="<?='edit_article?id='.$article["id_article"];?>"><i class="fa-solid fa-pen-to-square"></i></a> </div>
                                <div class="col-1"> <a href="<?='delete_article?id='.$article["id_article"];?>"><i class="fa-solid fa-trash-can"></i></a> </div>
                            <?php endif ;?>
                        <?php endforeach; ?>

                    </div>
                </div>

            <?php else : ?>
                <div class="container">
                    <div class="row">
                        <?php foreach ($_SESSION['articleSearch'] as $article): ?>

                        <div class="col-2"> <?= $article["label_article"];?> </div>
                        <div class="col-2"> <?= $article["origine"];?> </div>
                        <div class="col-2"> <?= $article["prix"]." €/".$article['label_unite'];?>  </div>
                        <div class="col-2"> <?= $article["poids"] ." " .$article['label_unite'];?> </div>
                        <div class="col-2"> <?= $article["label_statusArticle"];?> </div>
                        <div class="col-1"> <a href="<?='edit_article?id='.$article["id_article"];?>"><i class="fa-solid fa-pen-to-square"></i></a> </div>
                        <div class="col-1"> <a href="<?='delete_article?id='.$article["id_article"];?>"><i class="fa-solid fa-trash-can"></i></a> </div>
                        <?php endforeach;?>
                    </div>
                </div>
            <?php endif;?>

        </div>
    </div>
</div>