 <head>
    <div class="container">
        <div class="row">
            <div class="col-4">
                <form method="post" action ="articles" class="navbar-form navbar-right" role="search">
                    <div class="input-group">
                        <?php if(empty($_SESSION['articleSearch'])) :?>
                            <input type="search" class="form-control" name="articleSearch" placeholder="Rechercher un article">

                        <?php else : ?>
                            <input type="search" class="form-control" name="articleSearch" value="<?= $_POST['articleSearch'];?>">
                        <?php endif;?>

                        <span class="input-group-btn">
                        <button type="submit" class="btn btn-default" >
                            Ok
                        <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                </form>
            </div>
            <div class="col-4">
                <a href="add_article"> Ajouter un article </a>
            </div>
<!--            <div class="col-4">-->
<!--                <form method="post" action="articles" id="submit-franco">-->
<!--                    <input type="text" name="franco" placeholder="--><?//=$franco['franco'];?><!--">-->
<!--                    <button type="submit" class="button-franco">ok</button>-->
<!--                </form>-->
<!--            </div>-->
        </div>
    </div>

</head>
<div class="container">
    <div class="row">
        <div class="col-12 border rounded-2 tableColor-green pt-2 pb-3 pl-0 pr-0">
            <h2 class="text-center"> Listes des articles</h2>
            <div class="container-fluid bg-light">
                <div class="row m-0">

                    <div class="col-2  text-center"> <p>Label</p> </div>
                    <div class="col-4 col-sm-3 col-md-2 text-center"> <p>Origine</p> </div>
                    <div class="col-4 col-sm-3 col-md-2 text-center"> <p>Prix</p> </div>
                    <div class="col-2 d-none d-sm-block text-center"> <p>Poids</p> </div>
                    <div class="col-2 d-none d-md-block text-center"> <p>Statut</p> </div>
                    <div class="col-2 d-md-none text-center"> <p>Détails</p> </div>
                </div>
            </div>

            <?php if(empty($_SESSION['articleSearch'])) :?>
                <div class="container-fluide bg-light ">
                    <h3 class="text-center m-0 p-2">Légumes</h3>
                        <?php foreach ($articles as $article): ?>
                            <?php if($article['label_famille']=="Légume"):;?>
                                <div class="row commande m-0">
                                    <div class="col-2 text-center"><?= $article["label_article"];?> </div>
                                    <div class="col-4 col-sm-3 col-md-2 text-center"><?= $article["origine"];?> </div>
                                    <div class="col-4 col-sm-3 col-md-2 text-center"><?= $article["prix"]." €/".$article['label_unite'];?>  </div>
                                    <div class="col-2 d-none d-sm-block text-center"><?= $article["poids"] ." " .$article['label_unite'];?> </div>
                                    <div class="col-2 d-none d-md-block text-center"><?= $article["label_statusArticle"];?> </div>
                                    <div class="col-1 d-none d-md-block text-center"> <a href="<?='edit_article?id='.$article["id_article"];?>"><i class="fa-solid fa-pen-to-square"></i></a></div>
                                    <div class="col-1 d-none d-md-block text-center"> <a href="<?='delete_article?id='.$article["id_article"];?>"><i class="fa-solid fa-trash-can"></i></a> </div>
                                    <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>
                                </div>
                            <?php endif ;?>
                        <?php endforeach; ?>
                </div>

                <div class="container-fluide bg-light">
                    <h3 class="text-center m-0 p-2" >Fruits</h3>
                        <?php foreach ($articles as $article): ?>
                            <?php if($article['label_famille']=="Fruit"):?>
                                <div class="row commande m-0">
                                    <div class="col-2 text-center"><?= $article["label_article"];?> </div>
                                    <div class="col-4 col-sm-3 col-md-2 text-center"><?= $article["origine"];?> </div>
                                    <div class="col-4 col-sm-3 col-md-2 text-center"><?= $article["prix"]." €/".$article['label_unite'];?>  </div>
                                    <div class="col-2 d-none d-sm-block text-center"><?= $article["poids"] ." " .$article['label_unite'];?> </div>
                                    <div class="col-2 d-none d-md-block text-center"><?= $article["label_statusArticle"];?> </div>
                                    <div class="col-1 d-none d-md-block text-center"> <a href="<?='edit_article?id='.$article["id_article"];?>"><i class="fa-solid fa-pen-to-square"></i></a></div>
                                    <div class="col-1 d-none d-md-block text-center"> <a href="<?='delete_article?id='.$article["id_article"];?>"><i class="fa-solid fa-trash-can"></i></a> </div>
                                    <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>
                                </div>
                            <?php endif ;?>
                        <?php endforeach; ?>
                </div>

            <?php else : ?>
                <div class="container-fluid">
                    <?php foreach ($_SESSION['articleSearch'] as $article): ?>
                        <div class="row commande m-0">
                            <div class="col-2 text-center"><?= $article["label_article"];?> </div>
                            <div class="col-4 col-sm-3 col-md-2 text-center"><?= $article["origine"];?> </div>
                            <div class="col-4 col-sm-3 col-md-2 text-center"><?= $article["prix"]." €/".$article['label_unite'];?>  </div>
                            <div class="col-2 d-none d-sm-block text-center"><?= $article["poids"] ." " .$article['label_unite'];?> </div>
                            <div class="col-2 d-none d-md-block text-center"><?= $article["label_statusArticle"];?> </div>
                            <div class="col-1 d-none d-md-block text-center"> <a href="<?='edit_article?id='.$article["id_article"];?>"><i class="fa-solid fa-pen-to-square"></i></a></div>
                            <div class="col-1 d-none d-md-block text-center"> <a href="<?='delete_article?id='.$article["id_article"];?>"><i class="fa-solid fa-trash-can"></i></a> </div>
                            <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            <?php endif;?>

        </div>
    </div>
</div>