<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="http://localhost/ProjetCommande/public/css/styles.css">
    <link rel="stylesheet" type="text/css" href="http://localhost/ProjetCommande/public/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="http://localhost/ProjetCommande/public/css/styles_calendar.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oxygen&display=swap" rel="stylesheet">



    <title><?=$title;?></title>
</head>

<body>
<header>

    <div class="container-fluid bg-light">
        <div class="row ">
            <div class="col-12 p-0">
                <nav class="navbar navbar-expand-md pl-3 pr-3 w-100 navbar-light">
                    <a class="navbar-brand ml-2 ml-lg-0" href="admin"><img src="http://localhost/ProjetCommande/public/images/icon/pineapple-logo2.png" class="img-responsive mw-100"> </a>
                    <button class="navbar-toggler mr-2 mr-lg-0 border-0" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                        <img src="http://localhost/ProjetCommande/public/images/icon/button-navbar.png" class="img-responsive mw-100" >
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link" href="article_client">Passer une commande<span class="sr-only">(current)</span></a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="commande_client">Mes commandes</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="#">Paramètre</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="#">Deconnexion</a>
                            </li>

                        </ul>

                    </div>
                </nav>
            </div>
        </div>
    </div>


</header>


<?php include '../templates/' . $template . '.phtml'; ?>


<!--Chargement des scripts pour Bootstrap-->
<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/jquery-3.3.1.min.js" defer></script>
<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/bootstrap.js" defer></script>

<!-- Script pour activation du datepicker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" defer></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" defer></script>
<script src="http://localhost/ProjetCommande/public/js/script.js" defer></script>
</body>

</html>