<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="http://localhost/ProjetCommande/public/css/bootstrap.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="http://localhost/ProjetCommande/public/css/styles.css">
    <title><?=$title;?></title>

</head>

<body>
<header>
    <div class="container">
        <div class="row align-self-center">
            <div class="col-12">
                <nav class="navbar navbar-expand-lg navbar-light bg-light">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="#">LOGO</a>

                    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                            <li class="nav-item ">
                                <a class="nav-link" href="#">Qui sommes-nous?</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Nos produits</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Nos valeurs</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#" > Contact </a>
                            </li>
                        </ul>

                        <ul class="navbar-nav mr-2 mt-2 mt-lg-0">
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Espace pro<span class="sr-only">(current)</span> </a>
                            </li>
                        </ul>

                    </div>
                </nav>

            </div>
        </div>
    </div>

</header>

<?php include '../templates/' . $template . '.phtml'; ?>

<footer>
    <div class="container-fluid bg-success">
        <div class="row">
            <div class="col">
                <div class="container">
                    <div class="row justify-content-around">
                        <div class="col-3">
                            <p>Mention légale</p>
                        </div>
                        <div class="col-3">
                            <p>Retrouvez-nous sur</p>
                        </div>
                        <div class="col-3">
                            <ul>
                                <li>Qui sommes-nous?</li>
                                <li>Nos produits</li>
                                <li>Nos valeurs</li>
                                <li>Contact</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>


<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/jquery-3.3.1.min.js" defer></script>
<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/bootstrap.js" defer></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js" defer></script>
<!-- Script pour activation du datepicker -->
<script src="http://localhost/ProjetCommande/public/js/script.js" defer></script>
</body>

</html>