<form method="post" action="commande_admin">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="form-group">
                    <div class="form-group">
                        <div class="datepicker date input-group">

                            <?php if(empty($_SESSION['commandeByDate'])) :?>
                                <input type="search" name="searchDate" placeholder="Choisir une date" class="form-control" id="reservationDate">
                            <?php else : ?>
                                <input type="search" name="searchDate" value="<?= $date;?>" class="form-control" id="reservationDate">
                            <?php endif;?>

                            <div class="input-group-append"><span class="input-group-text px-"><i class="fa fa-calendar"></i></span></div>
                            <span class="input-group-btn">
                            <button type="submit" class="btn btn-default" >
                                Recherche
                            <span class="glyphicon glyphicon-search"></span>
                            </button>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

    <div class="container">
        <div class="row">
            <div class="col-12">

                <div class="container">
                    <div class="row">

                        <div class="col-2"> <p>Statut</p> </div>
                        <div class="col-1"> <p>Num Commande</p> </div>
                        <div class="col-2"> <p>Société</p> </div>
                        <div class="col-1"> <p>Montant</p> </div>
                        <div class="col-2"> <p>Date commande</p> </div>
                        <div class="col-2"> <p>Date livraison</p> </div>

                    </div>
                </div>

                <?php if(empty($_SESSION['commandeByDate'])) :?>
                <div class="container">
                    <div class="row">
                        <?php foreach ($commandes as $commande): ?>
                            <div class="col-2"><?=$commande['label_status'];?> </div>
                            <div class="col-1"><?=$commande['id_commande'];?> </div>
                            <div class="col-2"><?=$commande['society'];?> </div>
                            <div class="col-1"><?=$commande['montant'] ." €" ;?> </div>
                            <div class="col-2"><?=$commande['date_commande'] ;?> </div>
                            <div class="col-2"><?=$commande['date_livraison'] ;?> </div>
                            <div class="col-1"> <a href="<?='commande_details?id='.$commande['id_commande'] ;?>">Voir</a> </div>
                            <div class="col-1"> <a href="#">Supprimer</a> </div>
                        <?php endforeach; ?>

                    </div>
                </div>
                <?php else :?>
                    <div class="container">
                        <div class="row">
                            <?php foreach ($_SESSION['commandeByDate'] as $commande): ?>
                                <div class="col-2"><?=$commande['label_status'];?> </div>
                                <div class="col-1"><?=$commande['id_commande'];?> </div>
                                <div class="col-2"><?=$commande['society'];?> </div>
                                <div class="col-1"><?=$commande['montant'] ." €" ;?> </div>
                                <div class="col-2"><?=$commande['date_commande'] ;?> </div>
                                <div class="col-2"><?=$commande['date_livraison'] ;?> </div>
                                <div class="col-1"> <a href="<?='commande_details?id='.$commande['id_commande'] ;?>">Voir</a> </div>
                                <div class="col-1"> <a href="#">Supprimer</a> </div>
                            <?php endforeach; ?>

                        </div>
                    </div>

                <?php endif;?>

            </div>
        </div>
    </div>


