<main>

<div class="container">
    <div class="row">
        <div class="col-12">
            <h2>Détails commande</h2>

            <p>Commande n°<?=$idCommande;?></p>
            <p>Client : <?=$client['society'];?></p>
            <p>Adresse de livraison : <?=$client['address'] .", ".$client['city'] ." ".$client['postal'];?>.</p>
            <?php if( !$client['contact']): ?>
            <p>Personne à contacter : <?=$client['contact'];?></p>
            <?php endif; ?>
            <?php if( !$client['phone']): ?>
                <p>Téléphone : <?=$client['phone'];?></p>
            <?php endif; ?>
            <p>Email : <?=$client['email'] ;?></p>

            <p>Date de commande : <?=$dateCommande ;?></p>
            <p>Date de livraison : <?=$dateLivraison ;?></p>



            <div class="container">
                <div class="row">
                    <div class="col-2"> <p>Article</p> </div>
                    <div class="col-2"> <p>Origine</p> </div>
                    <div class="col-2"> <p>Prix unitaire</p> </div>
                    <div class="col-2"> <p>Quantité</p> </div>
                    <div class="col-1"> <p>Poids</p> </div>
                    <div class="col-1"> <p>Montant</p> </div>
                </div>
            </div>
                <?php foreach ($articlesCommande as $articleCommande) : ?>
                    <form method="POST" action="<?='edit_commande?id='.$idCommande;?>"
                        <div class="container">
                            <div class="row">
                                <input type="hidden" name="id_article" value="<?=$articleCommande['id_article'];?>">
                                <div class="col-2"> <?= $articleCommande["label_article"];?> </div>
                                <div class="col-2"> <?= $articleCommande["origine"];?> </div>
                                <div class="col-2"> <input type="text" class="form-control" name="prix" value="<?= $articleCommande["prix"];?>" >€ </div>
                                <div class="col-2"> <input type="text" class="form-control" name="quantite" value="<?= $articleCommande["quantite"];?>"></div>
                                <div class="col-1"> <?= $articleCommande["poids"] ." " .$articleCommande['label_unite'];?> </div>
                                <div class="col-1"><?= floatval($articleCommande["prix"]*$articleCommande["quantite"])." €";?></div>
                                <div class="col-2"> <button type="submit" class="btn btn-primary"> Modifier </button></div>
                            </div>
                        </div>
                    </form>
                <?php endforeach;?>


            <div class="container">
                <div class="row">
                    <div class="col">
                        <form method="post" action="">

                            <label for="label">Appliquer une remise</label>  <input type="text" class="" id="remise" name="remise" placeholder="%"> <button type="submit" class="btn btn-primary"> Appliquer </button>
                            <p>Montant de la commande : <?= $montantCommande;?> €</p>

                            <?php if ($articlesCommande[0]['remise'] != null || $articlesCommande[0]['remise'] != 0): ?>
                                <p>Remise de : <?= $articlesCommande[0]['remise'] ;?> %  <a href="<?='delete_discount?id='.$idCommande;?>"><i class="fa-solid fa-trash-can"></i></a> </p>
                                <p>Montant après remise : <?= $articlesCommande[0]['montant_remise'];?> € </p>
                            <?php endif;?>

                        </form>
                    </div>
                </div>
            </div>

            <form method="post" action="<?='validation_commande?id='.$idCommande;?>" id="form-commande" class="d-flex flex-row">
                <select class="form-control " name="status" id="status">
                    <?php foreach ($status as $statu): ?>
                        <option value="<?=$statu['id_status'];?>"><?=$statu['label_status'];?></option>
                    <?php endforeach; ?>
                </select>
                <div class="text-center justify-content-end">
                    <button type="submit" class="btn bg-custom-red mb-2 ">Valider</button>
                </div>
            </form>

        </div>
    </div>
</div>

</main>