<main>

    <form method="post" action="commande_admin">
        <div class="container mt-3">
            <div class="row">
                <div class="col-md-6 mx-auto">
                    <div class="form-group">
                        <div class="form-group">
                            <div class="datepicker date input-group">

                                <?php if(empty($_SESSION['commandeByDate'])) :?>
                                    <input type="search" name="searchDate" placeholder="Choisir une date" class="form-control" id="reservationDate">
                                <?php else : ?>
                                    <input type="search" name="searchDate" value="<?= $date;?>" class="form-control" id="reservationDate">
                                <?php endif;?>

                                <div class="input-group-append"><span class="input-group-text px-"><i class="fa fa-calendar"></i></span></div>
                                <span class="input-group-btn">
                                <button type="submit" class="btn btn-default ml-2" >
                                    Recherche
                                <span class="glyphicon glyphicon-search"></span>
                                </button>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div class="container">
        <div class="row">
            <div class="col-12 border rounded-2 tableColor-green pt-2 pb-3 pl-0 pr-0">

                <div class="container ">
                    <div class="row">

<!--                        <div class="col-2"> <p>Statut</p> </div>-->
                        <div class="col-2  text-center"> <p>Commande</p> </div>
                        <div class="col-4 col-sm-3 col-md-2 text-center"> <p>Société</p> </div>
                        <div class="col-4 col-sm-3 col-md-2 text-center"> <p>Montant</p> </div>
                        <div class="col-2 d-none d-sm-block text-center"> <p>Date commande</p> </div>
                        <div class="col-2 d-none d-md-block text-center"> <p>Date livraison</p> </div>
                        <div class="col-2 d-md-none text-center"> <p>Détails</p> </div>

                    </div>
                </div>

                <?php if(empty($_SESSION['commandeByDate'])) :?>
                <div class="container">

                    <?php foreach ($commandes as $commande): ?>
                        <div class="row commande">
<!--                            <div class="col-2">--><?//=$commande['label_status'];?><!-- </div>-->
                            <div class="col-2 text-center"><?=$commande['id_commande'];?> </div>
                            <div class="col-4 col-sm-3 col-md-2 text-center"><?=$commande['society'];?> </div>
                            <div class="col-4 col-sm-3 col-md-2 text-center"><?=$commande['montant'] ." €" ;?> </div>
                            <div class="col-2 d-none d-sm-block text-center"><?=$commande['date_commande'] ;?> </div>
                            <div class="col-2 d-none d-md-block text-center"><?=$commande['date_livraison'] ;?> </div>
                            <div class="col-1 d-none d-md-block text-center"> <a href="<?='commande_details?id='.$commande['id_commande'] ;?>"><i class="fa-solid fa-pen-to-square"></i></i></a> </div>
                            <div class="col-1 d-none d-md-block text-center"> <a href="#"><i class="fa-solid fa-trash-can"></i></a> </div>
                            <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <?php else :?>
                    <div class="container">
                        <?php foreach ($_SESSION['commandeByDate'] as $commande): ?>
                            <div class="row commande">
<!--                                <div class="col-2">--><?//=$commande['label_status'];?><!-- </div>-->
                                <div class="col-2 text-center"><?=$commande['id_commande'];?> </div>
                                <div class="col-4 col-sm-3 col-md-2 text-center"><?=$commande['society'];?> </div>
                                <div class="col-4 col-sm-3 col-md-2 text-center"><?=$commande['montant'] ." €" ;?> </div>
                                <div class="col-2 d-none d-sm-block text-center"><?=$commande['date_commande'] ;?> </div>
                                <div class="col-2 d-none d-md-block text-center"><?=$commande['date_livraison'] ;?> </div>
                                <div class="col-1 d-none d-md-block text-center"> <a href="<?='commande_details?id='.$commande['id_commande'] ;?>"><i class="fa-solid fa-pen-to-square"></i></i></a> </div>
                                <div class="col-1 d-none d-md-block text-center"> <a href="#"><i class="fa-solid fa-trash-can"></i></a> </div>
                                <div class="col-2 d-md-none text-center"> <i class="fa-solid fa-eye"></i> </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif;?>
            </div>
        </div>
    </div>

</main>
