<main>

    <div class="container mt-3 mb-3">
        <form method="post" action="commande_client" id="form-commande">
        <div class="row">
            <div class="col-12 col-md-6">
                <div class="form-group">
                        <div class="form-group">
                            <div class="datepicker date input-group">
                                <?php if(empty($_SESSION['commandeByDate'])) :?>
                                    <input type="search" name="searchDate" placeholder="Choisir une date" class="form-control" id="reservationDate">
                                <?php else : ?>
                                    <input type="search" name="searchDate" value="<?= $date;?>" class="form-control" id="reservationDate">
                                <?php endif;?>

                                <div class="input-group-append"><span class="input-group-text px-"><i class="fa fa-calendar"></i></span></div>
<!--                                <span class="input-group-btn">-->
<!--                                <button type="submit" class="btn btn-default bg-custom-red" >-->
<!--                                    Recherche-->
<!--                                <span class="glyphicon glyphicon-search"></span>-->
<!--                                </button>-->
                            </div>
                        </div>
                    </div>
            </div>
            <div class="col-12 col-md-6">
                    <select class="form-control " name="status" id="status">
                        <option value="<?= $commandes[0]['id_status'] ?>"><?= $commandes[0]['label_status'] ?></option>
                        <?php foreach ($status as $statu): ?>
                            <?php if($statu['id_status'] != $commandes[0]['id_status']): ?>
                                <option value="<?=$statu['id_status'];?>"><?=$statu['label_status'];?></option>
                            <?php endif ;?>
                        <?php endforeach; ?>
                    </select>
            </div>
        </div>
            <div class="mt-2 text-center justify-content-end">
                <button type="submit" class="btn bg-custom-red mb-2 ">Valider</button>
            </div>
        </form>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12 border rounded-2 tableColor-green pt-2 pb-3 pl-0 pr-0">
                <h3 class="text-center "> Mes commandes </h3>
                <div class="container ">
                    <div class="row pt-2 pb-2">
                        <div class="col-2 text-center"> <p>Commande</p> </div>
                        <div class="col-4 col-sm-2 col-md-2 text-center"> <p>Montant</p> </div>
                        <div class="col-2 d-none col-md-2 d-md-block text-center"> <p>Remise</p> </div>
                        <div class="col-3 d-none d-sm-block col-md-2 text-center"> <p>Date commande</p> </div>
                        <div class="col-4 col-sm-3 col-md-2 text-center"> <p>Date livraison</p> </div>
                        <div class="col-2  text-center"> <p>Détails</p> </div>

                    </div>
                </div>

                <?php if(empty($_SESSION['commandeByDate'])) :?>
                    <div class="container">

                        <?php foreach ($commandes as $commande): ?>
                            <div class="row pt-2 pb-2 commande" >
                                <div class="col-2 text-center" ><?=$commande['id_commande'];?></div>
                                <div class="col-4 col-sm-2 col-md-2 text-center" ><?=$commande['montant'] ." €" ;?> </div>
                                <div class="col-2 d-none col-md-2 d-md-block text-center"><?=$commande['montant_remise'];?> </div>
                                <div class="col-3 d-none d-sm-block col-md-2 text-center" ><?= date('d/m/y', strtotime($commande['date_commande'])) ;?> </div>
                                <div class="col-4 col-sm-3 col-md-2 text-center" ><?= date('d/m/y', strtotime($commande['date_livraison'])) ;?> </div>
                                <div class="col-2  text-center"> <i class="fa-solid fa-eye"></i> </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                <?php else :?>
                    <div class="container">
                        <?php foreach ($_SESSION['commandeByDate'] as $commande): ?>
                                <div class="row pt-2 pb-2 commande" >
                                    <div class="col-2 text-center" ><?=$commande['id_commande'];?></div>
                                    <div class="col-4 col-sm-2 col-md-2 text-center" ><?=$commande['montant'] ." €" ;?> </div>
                                    <div class="col-2 d-none col-md-2 d-md-block text-center"><?=$commande['montant_remise'];?> </div>
                                    <div class="col-3 d-none d-sm-block col-md-2 text-center" ><?= date('d/m/y', strtotime($commande['date_commande'])) ;?> </div>
                                    <div class="col-4 col-sm-3 col-md-2 text-center" ><?= date('d/m/y', strtotime($commande['date_livraison'])) ;?> </div>
                                    <div class="col-2  text-center"> <i class="fa-solid fa-eye"></i> </div>
                                </div>
                        <?php endforeach; ?>
                    </div>
                <?php endif;?>
            </div>
        </div>
    </div>

</main>

