<main class="p-0 pt-md-4 pb-md-4">
    <div class="container border rounded-2 tableColor-green ">
        <div class="row">
            <div class="col-12 p-0">
                <form method="POST" action="<?='edit_article?id='.$article['id_article'];?>">
                    <div class="container">
                        <div class="row mt-2">
                            <div class="col-12 col-md-6 text-center mb-3 mb-md-5 ">
                                <label class="mb-1" for="label" > Article </label>
                                <input type="text" class="form-control" id="label" name="label" value="<?=$label;?>">
                            </div>
                            <div class="col-12 col-md-6 text-center mb-3 mb-md-5">
                                <label class="mb-1" for="origine">Origine</label>
                                <input type="text" class="form-control" id="origine" name="origine" value="<?=$origine;?>">
                            </div>
                            <div class="col-12 col-md-6  text-center mb-3 mb-md-5">
                                <label class="mb-1" for="prix">Prix</label>
                                <input type="text" class="form-control" id="prix" name="prix" value="<?=$prix;?>">
                            </div>
                            <div class="col-12 col-md-6  text-center mb-3 mb-md-5">
                                <label class="mb-1" for="poids">Poids</label>
                                <input type="text" class="form-control" id="quantité" name="poids" value="<?=$poids;?>">
                            </div>
                            <div class="col-12 col-md-6  text-center mb-3 mb-md-5">
                                <label class="mb-1" for="unite">Unite</label>
                                <select class="form-control" name="unite" id="unite">
                                    <option value="<?=$article['id_unite'];?>"><?=$article['label_unite'];?></option>
                                    <?php foreach ($unites as $unite): ?>
                                        <?php if($unite['id_unite']!=$article['id_unite']): ?>
                                            <option value="<?=$unite['id_unite'];?>"><?=$unite['label_unite'];?></option>
                                        <?php endif ;?>
                                    <?php endforeach; ?>
                                </select>
                                <?php if (isset($error['unite'])): ?>
                                    <p class="error"><?=htmlspecialchars($error['unite']);?></p>
                                <?php endif; ?>
                            </div>
                            <div class="col-12 col-md-6  text-center mb-3 mb-md-5">
                                <label class="mb-1" for="famille">Famille</label>
                                <select class="form-control" name="famille" id="famille">
                                    <option value="<?=$article['id_famille'];?>"><?=$article['label_famille'];?></option>
                                    <?php foreach ($familles as $famille): ?>
                                        <?php if($famille['id_famille']!=$article['id_famille']): ?>
                                            <option value="<?=$famille['id_famille'];?>"><?=$famille['label_famille'];?></option>
                                        <?php endif ;?>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <div class="col-12 col-md-6 offset-md-3 text-center mb-3 mb-md-5">
                                <label class="mb-1" for="famille">Disponibilité</label>
                                <select class="form-control" name="status" id="status">
                                    <option value="<?=$article['id_statusArticle'];?>"><?=$article['label_statusArticle'];?></option>
                                    <?php foreach ($status as $oneStatus): ?>
                                        <?php if($oneStatus['id_statusArticle']!=$article['id_statusArticle']): ?>
                                            <option value="<?=$oneStatus['id_statusArticle'];?>"><?=$oneStatus['label_statusArticle'];?></option>
                                        <?php endif ;?>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="text-center justify-content-end">
                        <button type="submit" class="btn btn-primary mb-2  ">Valider</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>