<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="http://localhost/ProjetCommande/public/css/bootstrap.css">
    <title>Articles</title>
</head>
<body>
<form method="POST" action="<?='edit_article?id='.$article['id_article'];?>">
    <div class="form-group">
        <label for="label">Article</label>
        <input type="text" class="form-control" id="label" name="label" value="<?=$label;?>">
    </div>
    <div class="form-group">
        <label for="origine">Origine</label>
        <input type="text" class="form-control" id="origine" name="origine" value="<?=$origine;?>">
    </div>
    <div class="form-group">
        <label for="prix">Prix</label>
        <input type="text" class="form-control" id="prix" name="prix" value="<?=$prix;?>">
    </div>
    <div class="form-group">
        <label for="quantite">Quantité</label>
        <input type="text" class="form-control" id="quantité" name="quantite" value="<?=$quantite;?>">
    </div>
    <div class="form-group">
        <label for="unite">Unite</label>
        <select class="form-control" name="unite" id="unite">
            <option value="<?=$article['id_unite'];?>"><?=$article['label_unite'];?></option>
            <?php foreach ($unites as $unite): ?>
                <?php if($unite['id_unite']!=$article['id_unite']): ?>
                    <option value="<?=$unite['id_unite'];?>"><?=$unite['label_unite'];?></option>
                <?php endif ;?>
            <?php endforeach; ?>
        </select>
        <?php if (isset($error['unite'])): ?>
            <p class="error"><?=htmlspecialchars($error['unite']);?></p>
        <?php endif; ?>
    </div>
    <div class="form-group">
        <label for="famille">Famille</label>
        <select class="form-control" name="famille" id="unite">
            <option value="<?=$article['id_famille'];?>"><?=$article['label_famille'];?></option>
            <?php foreach ($familles as $famille): ?>
                <?php if($famille['id_famille']!=$article['id_famille']): ?>
                    <option value="<?=$famille['id_famille'];?>"><?=$famille['label_famille'];?></option>
                <?php endif ;?>
            <?php endforeach; ?>
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>



<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/jquery-3.3.1.min.js" ></script>
<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/bootstrap.js" ></script>
</body>

</html>