<main>
<!--    <h1>Bienvenu chez TerrAnanas</h1>-->
    <section class="haut-contenu">
        <img class="haut-contenu-image" src="http://localhost/ProjetCommande/public/images/ananas_home2.jpg" alt="#">

    </section>

<!--    <h1>Bienvenu chez TerrAnanas</h1>-->

    <article>
        <h1>Bienvenu chez TerrAnanas</h1>
        <div class="contenu-presentation">
            <p class="contenu-presentation-texte">TerrAnanas est une société de producteurs bio basée en Provence-Alpes-Côte d'Azur distribuant des fruits et légumes biologiques frais…</p>
            <p class="contenu-presentation-texte">Notre vocation est de vous proposer une offre large de fruits et légumes biologiques riches en goûts. Variétés gustatives, variétés oubliées, variétés anciennes... il existe en France et dans le monde une palette de textures et saveurs infinie et notre mission est de sélectionner et vous proposer les meilleurs d'entre elles.</p>
            <p class="contenu-presentation-texte">Pour parvenir à ce resultat, nous effectuons chaque année de nombreux essais, avec des nouvelles variétés, parfois oubliées et avec pour seul objectif, vous proposer des fruits et légumes bio riches en goût.</p>
        </div>
    </article>
    <article>
        <div class="contenu-client">
            <h2 class="contenu-client-titre"> Devenir client</h2>
            <p class="contenu-client-text">Vous allez ouvrir un magasin ? Vous êtes restaurateur ?</p>
            <p class="contenu-client-text">Votre structure existe déjà et vous cherchez un fournisseur de fruits et légumes bio fiable et partageant vos valeurs ?</p>
            <p class="contenu-client-text">Que vous soyez acteur de la distribution spécialisée bio ou bien généraliste, que vous soyez en groupe ou indépendant, restaurateur traditionnel ou en collectivité, nos schémas logistiques et commerciaux ont été pensé afin de répondre à toutes les configurations.</p>
            <p class="contenu-client-text">Pour en savoir plus, n'hésitez pas à nous contacter.</p>
            <div class="contenu-client-lien">
                <a href="contact" >Nous contacter</a>
            </div>
        </div>
    </article>

</main>