<div class="container">
    <div class="row">
        <div class="col">
            <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img class="d-block w-100 " style="height: 400px" src="http://localhost/ProjetCommande/public/images/img1.jpg" alt="First slide">
                    </div>
                    <div class="carousel-item">
                        <img class="d-block w-100 " style="height: 400px" src="http://localhost/ProjetCommande/public/images/img2.jpg" alt="Second slide">
                    </div>
                    <!--                <div class="carousel-item">-->
                    <!--                    <img class="d-block w-100" src="..." alt="Third slide">-->
                    <!--                </div>-->
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col">
            <div class="container">
                <div class="row">
                    <div class="col-4">
                        <img src="http://localhost/ProjetCommande/public/images/img1_mini.jpg">
                    </div>

                    <div class="col-6 offset-2">
                        <h3>La diversité variétale et gustative au coeur de nos engagements</h3>
                        <p> Notre vocation est de vous proposer une offre large de fruits et légumes biologiques riches en goûts. Variétés gustatives, variétés oubliées, variétés anciennes... il existe en France et dans le monde une palette de textures et saveurs infinie et notre mission est de sélectionner et vous proposer les meilleurs d'entre elles.</p>
                        <p> Pour parvenir à ce resultat, nous effectuons chaque année de nombreux essais, avec des nouvelles variétés, parfois oubliées et avec pour seul objectif, vous proposer des fruits et légumes bio riches en goût.</p>
                        <p>Afin de vous orienter dans vos choix en magasin, suivez nos marques 100% goût !</p>
                    </div>
                </div>
            </div>

            <div class="container">
                <div class="row">
                    <div class="col-6 ">
                        <h3>Des partenariats durables et équitables avec nos producteurs</h3>
                        <p>Quel que soit le lieu où se trouvent nos producteurs, nos activités et notre développement reposent sur cinq grandes valeurs :</p>
                        <p>Respect - Proximité - Diversité - Bienveillance - Fiabilité</p>
                        <p>L'agriculture biologique est avant tout une histoire d'hommes passionnés ayant des valeurs communes pour développer la filière dans son ensemble. Un travail collaboratif et de proximité nous à permis, au fil des années de veiller à la viabilité économique des exploitations mais surtout de structurer la production et améliorer la qualité des produits. Nous avons su construire un partenariat unique avec les producteurs des différentes régions. Ce dernier passant par la planification de cultures, la contractualisation des volumes, le conseil agronomique, l'assistance technique, l'accompagnement à la conversion.</p>
                        <p>La relation gagnant-gagnant qui en découle encourage les producteurs à cultiver pour nous des variétés de fruits et légumes bio aux qualités nutritionnelles et gustatives éprouvées.</p>
                    </div>
                    <div class="col-4 offset-2">
                        <img src="http://localhost/ProjetCommande/public/images/img1_mini.jpg">
                    </div>
                </div>
            </div>

            <div class="container">
                <div class="row">
                    <div class="col-4">
                        <img src="http://localhost/ProjetCommande/public/images/img1_mini.jpg">
                    </div>

                    <div class="col-6 offset-2">
                        <h3>Chez [ ... ], nous accompagnons tous les producteurs bio</h3>
                        <p> Animés par la volonté d'améliorer au fil des saisons la qualité et le goût des fruits et légumes biologiques des bassins où nous intervenons , nous accompagnons nos partenaires au quotidien. Nous les orientons sur des variétés adaptées à leur terroirs mais aussi sur vos attentes en terme de goûts.</p>
                        <p> Nous leur fournissons une assistance technique sur la conduite des cultures et l'organisation de la récolte. Nous planifions avec eux et à l'avance les volumes de récolte, ce qui les sécurise sur les débouchés. Nous finançons les certifications bio, effectuons des avances sur récolte et proposons des aides à l'investissement.</p>
                    </div>
                </div>
            </div>

            <div class="container">
                <div class="row">
                    <div class="col-6 ">
                        <h3>Des projets équitables, respectueux des hommes et des eco-systèmes</h3>
                        <p>Commercer bio, c’est respecter nos clients et nos producteurs. Comment pourrions-nous concevoir que des conditions de production respectueuses de l’environnement ne s’accompagnent pas de relations équitables envers les producteurs ?</p>
                        <p>Depuis toujours, nous recherchons une plus grande proximité avec nos partenaires agriculteurs ou distributeurs, grâce à de nouvelles implantations ou des accords commerciaux durables reposant sur :</p>
                        <p>-Une rémunération équitable du producteur </p>
                        <p>-Un prix équitable pour le consommateur</p>
                        <p>-La viabilité économique des projets</p>
                        <p>-L’engagement sur le long terme</p>
                    </div>
                    <div class="col-4 offset-2">
                        <img src="http://localhost/ProjetCommande/public/images/img1_mini.jpg">
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


