<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="http://localhost/ProjetCommande/public/css/bootstrap.css">
    <title>Inscription</title>
</head>
<body>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-6">
            <h3>Connexion</h3>
        </div>
    </div>
</div>
<div class="container">

    <div class="row justify-content-center">
        <div class="col-6 ">

            <!-- Pills content -->
            <div class="tab-content">
                <div class="tab-pane fade show active" id="pills-login" role="tabpanel" aria-labelledby="tab-login">
                    <form method="POST" action="<?='login';?>">

                        <!-- Email input -->
                        <div class="form-outline mb-4">
                            <label class="form-label" for="email">Email</label>
                            <input type="email" id="email" name="email" class="form-control" />
                        </div>

                        <!-- Password input -->
                        <div class="form-outline mb-4">
                            <label class="form-label" for="password">Password</label>
                            <input type="password" id="password" name="password" class="form-control" />

                        </div>

                        <!-- 2 column grid layout -->
                        <div class="row mb-4">
<!--                            <div class="col-md-6 d-flex justify-content-center">-->
<!--                                 Checkbox -->
<!--                                <div class="form-check mb-3 mb-md-0">-->
<!--                                    <input class="form-check-input" type="checkbox" value="" id="loginCheck" checked />-->
<!--                                    <label class="form-check-label" for="loginCheck"> Remember me </label>-->
<!--                                </div>-->
<!--                            </div>-->

                            <div class="col-md-6 d-flex justify-content-center">
                                <!-- Simple link -->
                                <a href="#!">Forgot password?</a>
                            </div>
                        </div>

                        <!-- Submit button -->
                        <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>

                        <!-- Register buttons -->
                        <div class="text-center">
                            <p>Not a member? <a href="#!">Register</a></p>
                        </div>
                    </form>
                </div>
<!--                --><?//= $_SESSION['user']['email'] ;?>
            </div>
            <!-- Pills content -->

        </div>
    </div>
</div>


<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/jquery-3.3.1.min.js" ></script>
<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/bootstrap.js" ></script>
</body>

</html>