<div class="article-head container">
    <div class="row">
        <div class="col">

            <img class="d-block w-100 " src="http://localhost/ProjetCommande/public/images/fruits-bio2.jpg" alt="First slide">
            <div class="text-contenant">
                <h2>Nos fruits</h2>
                <span class="d-none d-md-block">Il existe une grande variété de fruits bio cultivés en France et dans le monde. Grâce à notre expérience de plus de 30 ans, nous avons su fédérer de nombreux agriculteurs autour de nos valeurs pour vous proposer une large gamme de fruits bio</span>
            </div>
        </div>
    </div>
</div>

<div class="article container">
    <div class="row">
        <div class="col-12 col-sm-6 col-lg-3"><img class="d-block w-100 " style="height: 400px" src="http://localhost/ProjetCommande/public/images/fruits/pommes.jpg"> </div>
        <div class="col-12 col-sm-6 col-lg-3"><img class="d-block w-100 " style="height: 400px" src="http://localhost/ProjetCommande/public/images/fruits/fraises.jpg"> </div>
        <div class="col-12 col-sm-6 col-lg-3"><img class="d-block w-100 " style="height: 400px" src="http://localhost/ProjetCommande/public/images/fruits/peches-et-nectarines.jpg"> </div>
        <div class="col-12 col-sm-6 col-lg-3"><img class="d-block w-100 " style="height: 400px" src="http://localhost/ProjetCommande/public/images/fruits/fruits-exotiques.jpg"> </div>
        <div class="col-12 col-sm-6 col-lg-3"><img class="d-block w-100 " style="height: 400px" src="http://localhost/ProjetCommande/public/images/fruits/raisins.jpg"> </div>
    </div>
</div>