<main>
    <section class="haut-contenu">
        <img class="haut-contenu-image" src="http://localhost/ProjetCommande/public/images/ananas_nosvaleurs.png" alt="#">
    </section>

    <article>
        <div class="contenu-presentation">
            <h2>Des partenariats durables et équitables avec nos producteurs</h2>
            <p class="contenu-presentation-texte">L'agriculture biologique est avant tout une histoire d'hommes passionnés ayant des valeurs communes pour développer la filière dans son ensemble. Un travail collaboratif et de proximité nous à permis, au fil des années de veiller à la viabilité économique des exploitations mais surtout de structurer la production et améliorer la qualité des produits. Nous avons su construire un partenariat unique avec les producteurs des différentes régions. Ce dernier passant par la planification de cultures, la contractualisation des volumes, le conseil agronomique, l'assistance technique, l'accompagnement à la conversion </p>
            <p class="contenu-presentation-texte"> La relation gagnant-gagnant qui en découle encourage les producteurs à cultiver pour nous des variétés de fruits et légumes bio aux qualités nutritionnelles et gustatives éprouvées.</p>
        </div>
    </article>

    <article>
        <div class="contenu-presentation">
            <h2>Cultivateur de filière 100% BIO</h2>
            <p class="contenu-presentation-texte">Chez TerrAnanas, nous accompagnons tous les producteurs bio. Animés par la volonté d'améliorer au fil des saisons la qualité et le goût des fruits et légumes biologiques des bassins où nous intervenons (Provence, Bretagne, Roussillon ...), nous accompagnons nos partenaires au quotidien. Nous les orientons sur des variétés adaptées à leur terroirs mais aussi sur vos attentes en terme de goûts.</p>
            <p class="contenu-presentation-texte"> Parce qu'on cultive des filières 100% bio, on récolte forcément des fruits et légumes riches en goûts...</p>
        </div>
    </article>
</main>