<main>
    <section class="haut-contenu">
        <img class="haut-contenu-image" src="http://localhost/ProjetCommande/public/images/ananas_qsn.png" alt="#">
    </section>

    <article>
        <div class="contenu-presentation">
            <h2>Qui sommes-nous ?</h2>
            <p class="contenu-presentation-texte">TerrAnanas est une société de producteurs bio basée en Provence-Alpes-Côte d'Azur distribuant des fruits et légumes biologiques frais…</p>
            <p class="contenu-presentation-texte">Notre vocation est de vous proposer une offre large de fruits et légumes biologiques riches en goûts. Variétés gustatives, variétés oubliées, variétés anciennes... il existe en France et dans le monde une palette de textures et saveurs infinie et notre mission est de sélectionner et vous proposer les meilleurs d'entre elles.</p>
            <p class="contenu-presentation-texte">Pour parvenir à ce resultat, nous effectuons chaque année de nombreux essais, avec des nouvelles variétés, parfois oubliées et avec pour seul objectif, vous proposer des fruits et légumes bio riches en goût.</p>
        </div>
        <div class="contenu-presentation">
            <h2>Notre mission c’est quoi ?</h2>
            <p class="contenu-presentation-texte"> Tout simplement de commercialiser toute la production de fruits et legumes biologiques de ses exploitations associées et partenaires et de contribuer à leur développement et leur pérennisation à la fois technique et économique.</p>
        </div>
        <div class="contenu-presentation">
            <h2>Qui sont nos clients ?</h2>
            <p class="contenu-presentation-texte"> Des grossistes, des magasins spécialisés bios, des supermarchés, des sociétés de restauration, des cuisines centrales, des producteurs.</p>
            <p>Nos fruits et légumes biologiques , sont présentes dans la plupart des magasins spécialisés bio en France. Vous pouvez les retrouver dans de nombreux magasins bio indépendants ainsi que dans les enseignes suivantes :</p>
            <div class="contenu-presentation-liste">
                <div class="contenu-presentation-liste-image">
                    <a href="#" class="contenu-presentation-liste-image-lien">
                        <img src="http://localhost/ProjetCommande/public/images/eau_vive.jpg" alt="image_eauvive">
                    </a>
                </div>
                <div class="contenu-presentation-liste-image">
                    <a href="#" class="contenu-presentation-liste-image-lien">
                        <img src="http://localhost/ProjetCommande/public/images/biomonde.jpg" alt="image_biomonde">
                    </a>
                </div>
                <div class="contenu-presentation-liste-image">
                    <a href="#" class="contenu-presentation-liste-image-lien">
                        <img src="http://localhost/ProjetCommande/public/images/naturalia.png" alt="image_naturalia">
                    </a>
                </div>
                <div class="contenu-presentation-liste-image">
                    <a href="#" class="contenu-presentation-liste-image-lien">
                        <img src="http://localhost/ProjetCommande/public/images/bionco.jpg" alt="image_bionco">
                    </a>
                </div>
            </div>
        </div>

</main>