<head>
    <div class="container">
        <div class="row">
            <div class="col-4">
                <form method="POST" action ="users" class="navbar-form navbar-right" role="search">
                    <div class="input-group">
                        <?php if(empty($_SESSION['userSearch'])) :?>
                            <input type="search" class="form-control" name="userSearch" placeholder="Rechercher un client">

                        <?php else : ?>
                            <input type="search" class="form-control" name="userSearch" value="<?= $userSearch;?>">
                        <?php endif;?>

                        <span class="input-group-btn">
                        <button type="submit" class="btn btn-default" >
                            Ok
                        <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                </form>
            </div>

        </div>
    </div>
</head>

<div class="container">
    <div class="row">
        <div class="col-12">
            <h2> Listes clients</h2>
            <div class="container">
                <div class="row">
                    <div class="col-1"> <p>Statut</p> </div>
                    <div class="col-2"> <p>Société</p> </div>
                    <div class="col-2"> <p>Adresse</p> </div>
                    <div class="col-1"> <p>Ville</p> </div>
                    <div class="col-1"> <p>Code postal</p> </div>
                    <div class="col-1"> <p>Personne à contacter</p> </div>
                    <div class="col-1"> <p>Téléphone</p> </div>
                    <div class="col-1"> <p>Email</p> </div>
                    <div class="col-1"> <p> </p> </div>
                    <div class="col-1"> <p> </p> </div>
                </div>
            </div>

            <?php if(empty($_SESSION['userSearch'])) :?>
            <div class="container">
                <div class="row">
                    <?php foreach ($users as $user): ?>
                        <div class="col-1"><?= $user['label_status'] ;?></div>
                        <div class="col-2"> <?= $user["society"];?> </div>
                        <div class="col-2"> <?= $user["address"];?> </div>
                        <div class="col-1"> <?= $user["city"];?> </div>
                        <div class="col-1"> <?= $user["postal"];?> </div>
                        <div class="col-1"> <?= $user["contact"];?> </div>
                        <div class="col-1"> <?= $user["phone"];?> </div>
                        <div class="col-1"> <?= $user["email"];?> </div>
                        <div class="col-1"> <a href="<?='edit_user?id='.$user["id_user"];?>">Modifier</a> </div>
                        <div class="col-1"> <a href="<?='delete_user?id='.$user["id_user"];?>">Supprimer</a> </div>
                    <?php endforeach; ?>

                </div>
            </div>

            <?php else : ?>
            <div class="container">
                <div class="row">

                    <?php foreach ($_SESSION['userSearch'] as $user): ?>
                        <div class="col-1"><?= $user['label_status'] ;?></div>
                        <div class="col-2"> <?= $user["society"];?> </div>
                        <div class="col-2"> <?= $user["address"];?> </div>
                        <div class="col-1"> <?= $user["city"];?> </div>
                        <div class="col-1"> <?= $user["postal"];?> </div>
                        <div class="col-1"> <?= $user["contact"];?> </div>
                        <div class="col-1"> <?= $user["phone"];?> </div>
                        <div class="col-1"> <?= $user["email"];?> </div>
                        <div class="col-1"> <a href="<?='edit_user?id='.$user["id_user"];?>">Modifier</a> </div>
                        <div class="col-1"> <a href="<?='delete_user?id='.$user["id_user"];?>">Supprimer</a> </div>
                    <?php endforeach; ?>
                </div>
            </div>
            <?php endif;?>
            
        </div>
    </div>
</div>

