<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="form-group">
                <div class="form-group">
                    <div class="datepicker date input-group">
                        <input type="text" placeholder="Choisir une date" class="form-control" id="reservationDate">
                        <div class="input-group-append"><span class="input-group-text px-"><i class="fa fa-calendar"></i></span></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-12">
            <h2> Listes clients</h2>
            <div class="container">
                <div class="row">
                    <div class="col-1"> <p>Statut</p> </div>
                    <div class="col-2"> <p>Société</p> </div>
                    <div class="col-2"> <p>Adresse</p> </div>
                    <div class="col-1"> <p>Ville</p> </div>
                    <div class="col-1"> <p>Code postal</p> </div>
                    <div class="col-1"> <p>Personne à contacter</p> </div>
                    <div class="col-1"> <p>Téléphone</p> </div>
                    <div class="col-1"> <p>Email</p> </div>
                    <div class="col-1"> <p> </p> </div>
                    <div class="col-1"> <p> </p> </div>
                    <!--                                <div class="col-2"> <p>Supprimer</p> </div>-->
                    <!--                                <div class="col-2"> <p>Modifier</p> </div>-->
                </div>
            </div>
            <div class="container">
                <div class="row">

                    <?php foreach ($users as $user): ?>
                        <div class="col-1"><?= $user['label_status'] ;?></div>
                        <div class="col-2"> <?= $user["society"];?> </div>
                        <div class="col-2"> <?= $user["address"];?> </div>
                        <div class="col-1"> <?= $user["city"];?> </div>
                        <div class="col-1"> <?= $user["postal"];?> </div>
                        <div class="col-1"> <?= $user["contact"];?> </div>
                        <div class="col-1"> <?= $user["phone"];?> </div>
                        <div class="col-1"> <?= $user["email"];?> </div>
                        <div class="col-1"> <a href="<?='edit_user?id='.$user["id_user"];?>">Modifier</a> </div>
                        <div class="col-1"> <a href="<?='delete_user?id='.$user["id_user"];?>">Supprimer</a> </div>

                    <?php endforeach; ?>

                </div>
            </div>
            
        </div>
    </div>
</div>
<!---->
<!--<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/jquery-3.3.1.min.js" ></script>-->
<!--<script type="text/javascript" src="http://localhost/ProjetCommande/public/js/bootstrap.js" ></script>-->
