<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">

<!--    <link rel="stylesheet" type="text/css" href="http://localhost/ProjetCommande/public/css/base_styles.css">-->
    <link rel="stylesheet" type="text/css" href="<?= getPathCSS('css','styles');?>">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;600&family=Satisfy&display=swap" rel="stylesheet">
<!--    <script type="text/javascript" src="http://localhost/TerrAnanas/public/js/responsive.js" defer></script>-->
<!--    <script type="module" src="http://localhost/TerrAnanas/public/js/main.js" defer></script>-->
    <?=getPathScript('js','main');?>
    <title><?=$params['title'];?></title>

</head>

<body>
<header>

    <nav class="headerNavbar">
        <div class="headerNavbar-function" >
            <div class="headerNavbar-function-burger" id="menuresp">
                <i class="fa-solid fa-bars" id="burger"></i>
                <i class="fa-sharp fa-solid fa-xmark hide" id="cross"></i>
            </div>
            <ul class="headerNavbar-function-list"  >
                <li class="headerNavbar-function-list-item">
                    <a class="headerNavbar-function-list-item-link" href="saisons">Saisons</a>
                </li>
                <li class="headerNavbar-function-list-item">
                    <a class="headerNavbar-function-list-item-link" href="recettes">Recettes</a>
                </li>
                <li class="headerNavbar-function-list-item">
                    <a class="headerNavbar-function-list-item-link" href="contact">Contact</a>
                </li>
                <?php if(!isConnected()):?>
                    <li class="headerNavbar-function-list-item">
                        <a class="headerNavbar-function-list-item-link" href="signup" >
                            Inscription
                        </a>
                    </li>
                    <li class="headerNavbar-function-list-item">
                        <a class="headerNavbar-function-list-item-link" href="login" >
                            Connexion
                        </a>
                    </li>
                <?php endif;?>
            </ul>
        </div>
        <div class="headerNavbar-img">
            <a class="headerNavbar-img-link" href="home">
                <img src="http://localhost/TerrAnanas/public/images/TerrAnanas_logo.png">
            </a>
        </div>

        <div class="headerNavbar-info" >
            <?php if(isConnected()):?>
            <ul class="headerNavbar-info-list">
                <li class="headerNavbar-info-list-item">
                    <a class="headerNavbar-info-list-item-link" href="panier" >
                        <i class="fa-solid fa-cart-shopping">
                            <?php if(!empty($_SESSION['panier'])): ?>
                                <span><?= count($_SESSION['panier']) ?></span>
                            <?php endif;?>
                        </i>
                    </a>
                </li>
                <li class="headerNavbar-info-list-item">
                    <div class="headerNavbar-info-list-item-dropdown">
                            <a class="headerNavbar-info-list-item-link" href="<?=getUserRole()?>">
                            <i class="fa-solid fa-user"></i>
                        </a>
                        <i class="fa-solid fa-caret-down"></i>
                    </div>
                    <ul class="headerNavbar-info-list-item-dropdownContent">
                        <li class="headerNavbar-info-list-item-dropdownContent-item">
                            <a class="headerNavbar-info-list-item-dropdownContent-item-link" href="articles_client">Passer une commande</a>
                        </li>
                        <li class="headerNavbar-info-list-item-dropdownContent-item">
                            <a class="headerNavbar-info-list-item-dropdownContent-item-link" href="historique_commandes">Mes commandes</a>
                        </li>
                        <li class="headerNavbar-info-list-item-dropdownContent-item">
                            <a class="headerNavbar-info-list-item-dropdownContent-item-link" href="parametre_client">Paramètre</a>
                        </li>
                        <li class="headerNavbar-info-list-item-dropdownContent-item logout">
                            <a class="headerNavbar-info-list-item-dropdownContent-item-link" href="logout">Se déconnecter</a>
                        </li>
                    </ul>
                </li>
            </ul>
        <?php endif; ?>
        </div>
    </nav>

</header>

<?php displayFlashMessages() ;?>
<main>
    <?php include $template; ?>
</main>


<footer>

    <nav class="footerNavbar">
        <section class="footerNavbar-info">
            <div class="footerNavbar-info-adresse">
                <h3>Adresse  </h3>
                <p>60 Bd Carnot</p>
                <p>13100, Aix-en-Provence</p>
            </div>
            <div class="footerNavbar-info-navigation">
                <h3>Liens utiles</h3>
                <ul class="footerNavbar-info-navigation-liste">
                    <li class="footerNavbar-info-navigation-liste-item">
                        <a class="footerNavbar-info-navigation-liste-item-link" href="saisons">Saisons</a>
                    </li>
                    <li class="footerNavbar-info-navigation-liste-item">
                        <a class="footerNavbar-info-navigation-liste-item-link" href="recettes">Recettes</a>
                    </li>
                    <li class="footerNavbar-info-navigation-liste-item">
                        <a class="footerNavbar-info-navigation-liste-item-link" href="contact">Contact</a>
                    </li>
                </ul>
            </div>
            <div class="footerNavbar-info-reseau">
                <h3>Retrouvez-nous sur</h3>
                <div class="footerNavbar-info-reseau-lien">
                    <a><i class="fa-brands fa-facebook"></i></a>
                    <a><i class="fa-brands fa-instagram"></i></a>
                </div>

            </div>
        </section>

        <section class="footerNavbar-copyright">
            <p class="footerNavbar-copyright-text">© TerrAnanas 2023 - Tous droits réservés. Site réalisé par LAM David.</p>
        </section>
    </nav>

</footer>
</body>

</html>