<form method="POST" action="<?='add_panier';?>" id="form-article">

<?php if(isset($_SESSION['articleSearch'])) :?>
    <?php if(empty($_SESSION['articleSearch'])) :?>

    <div class="article bg">
        <div class="article-liste-aucun"> <p>Aucun article trouvé</p></div>
    </div>
    <?php else : ?>
        <div class="article">
            <?php foreach ($_SESSION['articleSearch'] as $article): ?>
            <div class="article-liste <?=$article['statutArticle'];?> ">
                <input class="article-liste-item" type="hidden" name="id_article[]" value="<?=$article['id_article'];?>">
                <input class="article-liste-item" type="hidden" name="id_statutArticle[]" value="<?=$article['id_statutArticle'];?>">
                <input class="article-liste-item" type="hidden" name="unite[]" value="<?=$article['unite'];?>">
                <input class="article-liste-item" type="hidden" name="famille[]" value="<?=$article['famille'];?>">
                <div class="article-liste-item image "> <img src="<?=getPathImage('images',$article['image'],true) ;?>"></div>
                <div class="article-liste-item"> <input type="hidden" name="article[]" value="<?= $article["article"];?>"><?= $article["article"];?> </div>
                <div class="article-liste-item"> <input type="hidden" name="origine[]" value=" <?= $article["origine"];?>"> <?= $article["origine"];?> </div>
                <div class="article-liste-item"> <input type="hidden" name="prix[]" value="<?= $article["prix"]/100;?>"><?= ($article["prix"]/100)." €/".$article['unite'];?>   </div>
                <div class="article-liste-item"> <input type="hidden" name="poids[]" value="<?= $article["poids"];?>"><?= $article["poids"] ." " .$article['unite'];?>  </div>
                <div class="article-liste-item quantite">
                    <button class="buttonLess" type="button" data-id=<?=$article['id_article'];?> >-</button>
                    <input type="number" class="<?=$article['statutArticle'];?>" id="<?=$article['id_article'];?>" name="quantite[]" min="0" value="0">
                    <button class="buttonMore" type="button" data-id=<?=$article['id_article'];?> >+</button>
                </div>
            </div>
            <?php endforeach; ?>

        </div>
    <?php endif;?>
<?php else : ?>
    <p class="rayon">Légumes</p>
    <div class="article">
        <?php foreach ($params['articles'] as $article): ?>
            <?php if($article['famille']=="Légume" && $article['id_statutArticle']!=3):?>
                <div class="article-liste <?=$article['statutArticle'];?> ">
                    <input class="article-liste-item" type="hidden" name="id_article[]" value="<?=$article['id_article'];?>">
                    <input class="article-liste-item" type="hidden" name="id_statutArticle[]" value="<?=$article['id_statutArticle'];?>">
                    <input class="article-liste-item" type="hidden" name="unite[]" value="<?=$article['unite'];?>">
                    <input class="article-liste-item" type="hidden" name="famille[]" value="<?=$article['famille'];?>">
                    <div class="article-liste-item image "> <img src="<?=getPathImage('images',$article['image'],true) ;?>"></div>
                    <div class="article-liste-item"> <input type="hidden" name="article[]" value="<?= $article["article"];?>"><?= $article["article"];?> </div>
                    <div class="article-liste-item"> <input type="hidden" name="origine[]" value=" <?= $article["origine"];?>"> <?= $article["origine"];?> </div>
                    <div class="article-liste-item"> <input type="hidden" name="prix[]" value="<?= $article["prix"]/100;?>"><?= ($article["prix"]/100)." €/".$article['unite'];?>   </div>
                    <div class="article-liste-item"> <input type="hidden" name="poids[]" value="<?= $article["poids"];?>"><?= $article["poids"] ." " .$article['unite'];?>  </div>
                    <div class="article-liste-item quantite ">
                        <button class="buttonLess" type="button" data-id=<?=$article['id_article'];?> >-</button>
                        <input type="number" class="<?=$article['statutArticle'];?>" id="<?=$article['id_article'];?>" name="quantite[]" min="0" value="0">
                        <button class="buttonMore" type="button" data-id=<?=$article['id_article'];?> >+</button>
                    </div>
                </div>
            <?php endif ;?>
        <?php endforeach; ?>
    </div>
    <p class="rayon">Fruits</p>
    <div class="article">
        <?php foreach ($params['articles'] as $article): ?>
            <?php if($article['famille']=="Fruit" && $article['id_statutArticle']!=3):?>
                <div class="article-liste <?=$article['statutArticle'];?> ">
                    <input class="article-liste-item" type="hidden" name="id_article[]" value="<?=$article['id_article'];?>">
                    <input class="article-liste-item" type="hidden" name="id_statutArticle[]" value="<?=$article['id_statutArticle'];?>">
                    <input class="article-liste-item" type="hidden" name="unite[]" value="<?=$article['unite'];?>">
                    <input class="article-liste-item" type="hidden" name="famille[]" value="<?=$article['famille'];?>">
                    <div class="article-liste-item image "> <img src="<?=getPathImage('images',$article['image'],true) ;?>"></div>
                    <div class="article-liste-item"> <input type="hidden" name="article[]" value="<?= $article["article"];?>"><?= $article["article"];?> </div>
                    <div class="article-liste-item"> <input type="hidden" name="origine[]" value=" <?= $article["origine"];?>"> <?= $article["origine"];?> </div>
                    <div class="article-liste-item"> <input type="hidden" name="prix[]" value="<?= $article["prix"]/100;?>"><?= ($article["prix"]/100)." €/".$article['unite'];?>   </div>
                    <div class="article-liste-item"> <input type="hidden" name="poids[]" value="<?= $article["poids"];?>"><?= $article["poids"] ." " .$article['unite'];?>  </div>
                    <div class="article-liste-item quantite">
                        <button class="buttonLess" type="button" data-id=<?=$article['id_article'];?> >-</button>
                        <input type="number" class="<?=$article['statutArticle'];?>" id="<?=$article['id_article'];?>" name="quantite[]" min="0" value="0">
                        <button class="buttonMore" type="button" data-id=<?=$article['id_article'];?> >+</button>
                    </div>
                </div>
            <?php endif ;?>
        <?php endforeach; ?>
    </div>
<?php endif;?>
    <div class="liste-button"><button type="submit" class="">Valider </button> </div>
</form>