<section class="hearderPage">
    <div class="hearderPage-item">
        <h3 class="hearderPage-item-title">Connexion</h3>
        <span class="hearderPage-item-text">
            Veuillez rentrer vos identifiant.
        </span>
    </div>
</section>

<?php //displayFlashMessages() ;?>

<section class="formulaire">
    <form action="login" method="POST" >
        <div class="formulaire-item">
            <label >Email</label>
            <input type="email" class="form-control" name="email">
        </div>
        <div class="formulaire-item">
            <label >Mot de passe </label>
            <input type="password" class="form-control" name="password">
        </div>
        <input type="submit" value="Connexion" class="button-submit">
    </form>
</section>


