
<section class="hearderPage">
    <div class="hearderPage-item">
        <h3 class="hearderPage-item-title">Nos recettes</h3>
        <span class="hearderPage-item-text">
            Venez découvrir nos recettes !
        </span>
    </div>
</section>
</section>
<section class="recette">
    <article class="recette-article">
        <div class="recette-article-title tarte">
            <h2 class="recette-article-title-text">Tarte à l'Ananas</h2>
        </div>
        <div class="recette-article-item hidden">
            <div class="ingredient">
                <h3 class="ingredient-title">Ingrédients</h3>
                <ul class="ingredient-list">
                    <li>1 pâte brisée</li>
                    <li>1 ananas frais</li>
                    <li>2 cuillères à soupe de sucre</li>
                    <li>2 cuillères à soupe de farine</li>
                    <li>2 cuillères à soupe de beurre</li>
                    <li>1 cuillère à soupe de jus de citron</li>
                </ul>
            </div>
            <div class="preparation">
                <h3 class="preparation-title">Préparation</h3>
                <ul class="preparation-list">
                    <li>Préchauffez le four à 180°C.</li>
                    <li>Épluchez et coupez l'ananas en morceaux. Faites-les caraméliser dans une poêle avec du sucre et du beurre.</li>
                    <li>Disposez les morceaux d'ananas dans un moule à tarte préalablement beurré et fariné.</li>
                    <li>Préparez une pâte à tarte et recouvrez l'ananas avec celle-ci. Enfournez pendant environ 30 minutes.</li>
                </ul>
            </div>
        </div>
    </article>
    <article class="recette-article">

        <div class="recette-article-title ragout">
            <h2 class="recette-article-title-text">Recette de Ragoût de Porc à l'Ananas</h2>
        </div>
        <div class="recette-article-item hidden">
            <div class="ingredient">
                <h3 class="ingredient-title">Ingrédients</h3>
                <ul class="ingredient-list">
                    <li>600g de morceaux de porc</li>
                    <li>1 ananas frais</li>
                    <li>2 oignons</li>
                    <li>1 cuillère à soupe de gingembre haché</li>
                    <li>1 cuillère à café de curry</li>
                    <li>400ml de lait de coco</li>
                    <li>Coriandre fraîche pour la garniture</li>
                </ul>
            </div>
            <div class="preparation">
                <h3 class="preparation-title">Préparation</h3>
                <ul class="preparation-list">
                    <li>Dans une cocotte, faites dorer les morceaux de porc. Ajoutez les oignons, le gingembre et le curry.</li>
                    <li>Coupez l'ananas en morceaux et ajoutez-les à la cocotte avec le lait de coco. Laissez mijoter pendant environ 45 minutes.</li>
                    <li>Parsemez de coriandre fraîche avant de servir.</li>
                </ul>
            </div>
        </div>
    </article>
    <article class="recette-article ">
        <div class="recette-article-title grille">
            <h2 class="recette-article-title-text">Recette d'Ananas grillé au miel et au romarin</h2>
        </div>
        <div class="recette-article-item hidden">
            <div class="ingredient">
                <h3 class="ingredient-title">Ingrédients</h3>
                <ul class="ingredient-list">
                    <li>1 ananas frais</li>
                    <li>2 cuillères à soupe de miel</li>
                    <li>1 cuillère à soupe de romarin frais</li>
                    <li>2 cuillères à soupe de beurre</li>
                </ul>
            </div>
            <div class="preparation">
                <h3 class="preparation-title">Préparation</h3>
                <ul class="preparation-list">
                    <li>Coupez l'ananas en tranches et retirez le cœur dur.</li>
                    <li>Dans une poêle, faites fondre le beurre et ajoutez les tranches d'ananas. Faites-les griller pendant environ 2 minutes de chaque côté.</li>
                    <li>Arrosez les tranches d'ananas de miel et de romarin avant de servir.</li>
                </ul>
            </div>
        </div>
    </article>
</section>

<?=getPathScript('js','recettes');?>
